import { TEncounter } from 'constants/types';

const B_W: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    id: 1,
    pokemon: null,
    location: 'Nuvema Town',
    status: null,
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 1',
    status: null,
  },
  {
    id: 3,
    pokemon: null,
    location: 'Accumula Town',
    status: null,
  },
  {
    id: 4,
    pokemon: null,
    location: 'Route 2',
    status: null,
  },
  {
    id: 5,
    pokemon: null,
    location: 'Striaton City',
    status: null,
  },
  {
    id: 6,
    pokemon: null,
    location: 'Dreamyard',
    status: null,
  },
  {
    id: 7,
    pokemon: null,
    location: 'Route 3',
    status: null,
  },
  {
    id: 8,
    pokemon: null,
    location: 'Wellspring Cave',
    status: null,
  },
  {
    id: 9,
    pokemon: null,
    location: 'Nacrene City',
    status: null,
  },
  {
    id: 10,
    pokemon: null,
    location: 'Pinwheel Forest',
    status: null,
  },
  {
    id: 11,
    pokemon: null,
    location: 'Castelia City',
    status: null,
  },
  {
    id: 12,
    pokemon: null,
    location: 'Route 4',
    status: null,
  },
  {
    id: 13,
    pokemon: null,
    location: 'Desert Resort',
    status: null,
  },
  {
    id: 14,
    pokemon: null,
    location: 'Relic Castle',
    status: null,
  },
  {
    id: 15,
    pokemon: null,
    location: 'Nimbasa City',
    status: null,
  },
  {
    id: 16,
    pokemon: null,
    location: 'Route 5',
    status: null,
  },
  {
    id: 17,
    pokemon: null,
    location: 'Driftveil Drawbridge',
    status: null,
  },
  {
    id: 18,
    pokemon: null,
    location: 'Driftveil City',
    status: null,
  },
  {
    id: 19,
    pokemon: null,
    location: 'Cold Storage',
    status: null,
  },
  {
    id: 20,
    pokemon: null,
    location: 'Route 6',
    status: null,
  },
  {
    id: 21,
    pokemon: null,
    location: 'Mistralton Cave',
    status: null,
  },
  {
    id: 22,
    pokemon: null,
    location: 'Chargestone Cave',
    status: null,
  },
  {
    id: 23,
    pokemon: null,
    location: 'Mistralton City',
    status: null,
  },
  {
    id: 24,
    pokemon: null,
    location: 'Route 7',
    status: null,
  },
  {
    id: 25,
    pokemon: null,
    location: 'Celestial Tower',
    status: null,
  },
  {
    id: 26,
    pokemon: null,
    location: 'Route 17',
    status: null,
  },
  {
    id: 27,
    pokemon: null,
    location: 'Route 18',
    status: null,
  },
  {
    id: 28,
    pokemon: null,
    location: 'Twist Mountain',
    status: null,
  },
  {
    id: 29,
    pokemon: null,
    location: 'Icirrus City',
    status: null,
  },
  {
    id: 30,
    pokemon: null,
    location: 'Dragonspiral Tower',
    status: null,
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 8',
    status: null,
  },
  {
    id: 32,
    pokemon: null,
    location: 'Moor of Icirrus',
    status: null,
  },
  {
    id: 33,
    pokemon: null,
    location: 'Route 9',
    status: null,
  },
  {
    id: 34,
    pokemon: null,
    location: 'Opelucid City',
    status: null,
  },
  {
    id: 35,
    pokemon: null,
    location: 'Route 10',
    status: null,
  },
  {
    id: 36,
    pokemon: null,
    location: 'Victory Road',
    status: null,
  },
];

export default B_W;
