import type { TEncounter } from 'constants/types';

const B_W: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
    filterKey: 'bw-0',
  },
  {
    id: 1,
    pokemon: null,
    location: 'Nuvema Town',
    status: null,
    filterKey: 'bw-1',
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 1',
    status: null,
    filterKey: 'bw-2',
  },
  {
    id: 4,
    pokemon: null,
    location: 'Route 2',
    status: null,
    filterKey: 'bw-4',
  },
  {
    id: 5,
    pokemon: null,
    location: 'Striaton City',
    status: null,
    filterKey: 'bw-5',
  },
  {
    id: 6,
    pokemon: null,
    location: 'Dreamyard',
    status: null,
    filterKey: 'bw-6',
  },
  {
    id: 7,
    pokemon: null,
    location: 'Route 3',
    status: null,
    filterKey: 'bw-7',
  },
  {
    id: 8,
    pokemon: null,
    location: 'Wellspring Cave',
    status: null,
    filterKey: 'bw-8',
  },
  {
    id: 9,
    pokemon: null,
    location: 'Nacrene City',
    status: null,
    filterKey: 'bw-9',
  },
  {
    id: 10,
    pokemon: null,
    location: 'Pinwheel Forest',
    status: null,
    filterKey: 'bw-10',
  },
  {
    id: 11,
    pokemon: null,
    location: 'Castelia City',
    status: null,
    filterKey: 'bw-11',
  },
  {
    id: 12,
    pokemon: null,
    location: 'Route 4',
    status: null,
    filterKey: 'bw-12',
  },
  {
    id: 13,
    pokemon: null,
    location: 'Desert Resort',
    status: null,
    filterKey: 'bw-13',
  },
  {
    id: 14,
    pokemon: null,
    location: 'Relic Castle',
    status: null,
    filterKey: 'bw-14',
  },
  {
    id: 37,
    pokemon: null,
    location: 'Route 16',
    status: null,
    filterKey: 'bw-37',
  },
  {
    id: 38,
    pokemon: null,
    location: 'Lostlorn Forest',
    status: null,
    filterKey: 'bw-38',
  },
  {
    id: 16,
    pokemon: null,
    location: 'Route 5',
    status: null,
    filterKey: 'bw-16',
  },
  {
    id: 17,
    pokemon: null,
    location: 'Driftveil Drawbridge',
    status: null,
    filterKey: 'bw-17',
  },
  {
    id: 18,
    pokemon: null,
    location: 'Driftveil City',
    status: null,
    filterKey: 'bw-18',
  },
  {
    id: 19,
    pokemon: null,
    location: 'Cold Storage',
    status: null,
    filterKey: 'bw-19',
  },
  {
    id: 20,
    pokemon: null,
    location: 'Route 6',
    status: null,
    filterKey: 'bw-20',
  },
  {
    id: 21,
    pokemon: null,
    location: 'Mistralton Cave',
    status: null,
    filterKey: 'bw-21',
  },
  {
    id: 22,
    pokemon: null,
    location: 'Chargestone Cave',
    status: null,
    filterKey: 'bw-22',
  },
  {
    id: 24,
    pokemon: null,
    location: 'Route 7',
    status: null,
    filterKey: 'bw-24',
  },
  {
    id: 25,
    pokemon: null,
    location: 'Celestial Tower',
    status: null,
    filterKey: 'bw-25',
  },
  {
    id: 26,
    pokemon: null,
    location: 'Route 17',
    status: null,
    filterKey: 'bw-26',
  },
  {
    id: 27,
    pokemon: null,
    location: 'Route 18',
    status: null,
    filterKey: 'bw-27',
  },
  {
    id: 28,
    pokemon: null,
    location: 'Twist Mountain',
    status: null,
    filterKey: 'bw-28',
  },
  {
    id: 29,
    pokemon: null,
    location: 'Icirrus City',
    status: null,
    filterKey: 'bw-29',
  },
  {
    id: 30,
    pokemon: null,
    location: 'Dragonspiral Tower',
    status: null,
    filterKey: 'bw-30',
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 8',
    status: null,
    filterKey: 'bw-31',
  },
  {
    id: 32,
    pokemon: null,
    location: 'Moor of Icirrus',
    status: null,
    filterKey: 'bw-32',
  },
  {
    id: 33,
    pokemon: null,
    location: 'Route 9',
    status: null,
    filterKey: 'bw-33',
  },
  {
    id: 35,
    pokemon: null,
    location: 'Route 10',
    status: null,
    filterKey: 'bw-35',
  },
  {
    id: 36,
    pokemon: null,
    location: 'Victory Road',
    status: null,
    filterKey: 'bw-36',
  },
  {
    id: 39,
    pokemon: null,
    location: 'P2 Laboratory',
    status: null,
    filterKey: 'bw-39',
  },
  {
    id: 40,
    pokemon: null,
    location: 'Liberty Garden',
    status: null,
    filterKey: 'bw-40',
  },
];

export default B_W;
