import { TEncounter } from 'constants/types';

const B_W: TEncounter[] = [
  {
    filter: ['Snivy', 'Tepig', 'Oshawott'],
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    filter: ['Snivy', 'Tepig', 'Oshawott'],
    id: 1,
    pokemon: null,
    location: 'Nuvema Town',
    status: null,
  },
  {
    filter: [
      'Feebas',
      'Milotic',
      'Patrat',
      'Watchog',
      'Lillipup',
      'Herdier',
      'Audino',
      'Basculin',
      'Scraggy',
    ],
    id: 2,
    pokemon: null,
    location: 'Route 1',
    status: null,
  },
  {
    filter: ['Patrat', 'Lillipup', 'Purrloin', 'Audino'],
    id: 4,
    pokemon: null,
    location: 'Route 2',
    status: null,
  },
  {
    filter: ['Goldeen', 'Seaking', 'Basculin'],
    id: 5,
    pokemon: null,
    location: 'Striaton City',
    status: null,
  },
  {
    filter: [
      'Raticate',
      'Venomoth',
      'Ledian',
      'Ariados',
      'Kricketune',
      'Patrat',
      'Watchog',
      'Purrloin',
      'Liepard',
      'Pansage',
      'Pansear',
      'Panpour',
      'Munna',
      'Musharna',
      'Audino',
    ],
    id: 6,
    pokemon: null,
    location: 'Dreamyard',
    status: null,
  },
  {
    filter: [
      'Raticate',
      'Venomoth',
      'Ledian',
      'Ariados',
      'Kricketune',
      'Patrat',
      'Watchog',
      'Purrloin',
      'Liepard',
      'Pansage',
      'Pansear',
      'Panpour',
      'Munna',
      'Musharna',
      'Audino',
    ],
    id: 7,
    pokemon: null,
    location: 'Route 3',
    status: null,
  },
  {
    filter: ['Poliwag', 'Poliwhirl', 'Poliwrath', 'Roggenrola', 'Woobat', 'Drilbur', 'Basculin'],
    id: 8,
    pokemon: null,
    location: 'Wellspring Cave',
    status: null,
  },
  {
    filter: [
      'Omanyte',
      'Kabuto',
      'Aerodactyl',
      'Lileep',
      'Anorith',
      'Cranidos',
      'Shieldon',
      'Tirtouga',
      'Archen',
      'Cottonee',
      'Petilil',
    ],
    id: 9,
    pokemon: null,
    location: 'Nacrene City',
    status: null,
  },
  {
    filter: [
      'Tympole',
      'Throh',
      'Sawk',
      'Timburr',
      'Goldeen',
      'Seaking',
      'Pansage',
      'Pansear',
      'Panpour',
      'Pidove',
      'Tranquill',
      'Audino',
      'Sewaddle',
      'Swadloon',
      'Venipede',
      'Whirlipede',
      'Cottonee',
      'Whimsicott',
      'Petilil',
      'Lilligant',
      'Basculin',
    ],
    id: 10,
    pokemon: null,
    location: 'Pinwheel Forest',
    status: null,
  },
  {
    filter: ['Zorua'],
    id: 11,
    pokemon: null,
    location: 'Castelia City',
    status: null,
  },
  {
    filter: [
      'Krabby',
      'Kingler',
      'Clamperl',
      'Huntail',
      'Gorebyss',
      'Relicanth',
      'Luvdisc',
      'Sandile',
      'Darumaka',
      'Scraggy',
      'Frillish',
      'Jellicent',
      'Alomomola',
    ],
    id: 12,
    pokemon: null,
    location: 'Route 4',
    status: null,
  },
  {
    filter: ['Sandile', 'Darumaka', 'Maractus', 'Dwebble', 'Sigilyph'],
    id: 13,
    pokemon: null,
    location: 'Desert Resort',
    status: null,
  },
  {
    filter: [
      'Sandile',
      'Yamask',
      'Krokorok',
      'Cofagrigus',
      'Sandslash',
      'Onix',
      'Claydol',
      'Volcarona',
    ],
    id: 14,
    pokemon: null,
    location: 'Relic Castle',
    status: null,
  },
  {
    filter: [
      'Liepard',
      'Audino',
      'Trubbish',
      'Minccino',
      'Cinccino',
      'Gothita',
      'Solosis',
      'Emolga',
    ],
    id: 16,
    pokemon: null,
    location: 'Route 5',
    status: null,
  },
  {
    filter: ['Ducklett'],
    id: 17,
    pokemon: null,
    location: 'Driftveil Drawbridge',
    status: null,
  },
  {
    filter: [
      'Krabby',
      'Kingler',
      'Chinchou',
      'Lanturn',
      'Luvdisc',
      'Frillish',
      'Jellicent',
      'Alomomola',
    ],
    id: 18,
    pokemon: null,
    location: 'Driftveil City',
    status: null,
  },
  {
    filter: ['Herdier', 'Stoutland', 'Audino', 'Timburr', 'Minccino', 'Cinccino', 'Vanillite'],
    id: 19,
    pokemon: null,
    location: 'Cold Storage',
    status: null,
  },
  {
    filter: [
      'Poliwag',
      'Poliwhirl',
      'Politoed',
      'Tranquill',
      'Unfezant',
      'Audino',
      'Swadloon',
      'Leavanny',
      'Basculin',
      'Vanillite',
      'Deerling',
      'Emolga',
      'Karrablast',
      'Foongus',
    ],
    id: 20,
    pokemon: null,
    location: 'Route 6',
    status: null,
  },
  {
    filter: ['Boldore', 'Woobat', 'Drilbur', 'Axew'],
    id: 21,
    pokemon: null,
    location: 'Mistralton Cave',
    status: null,
  },
  {
    filter: ['Boldore', 'Joltik', 'Ferroseed', 'Klink', 'Tynamo', 'Drilbur'],
    id: 22,
    pokemon: null,
    location: 'Chargestone Cave',
    status: null,
  },
  {
    filter: [
      'Watchog',
      'Tranquill',
      'Unfezant',
      'Zebstrika',
      'Audino',
      'Deerling',
      'Emolga',
      'Foongus',
      'Cubchoo',
    ],
    id: 24,
    pokemon: null,
    location: 'Route 7',
    status: null,
  },
  {
    filter: ['Litwick', 'Elgyem'],
    id: 25,
    pokemon: null,
    location: 'Celestial Tower',
    status: null,
  },
  {
    filter: [
      'Horsea',
      'Seadra',
      'Qwilfish',
      'Kingdra',
      'Finneon',
      'Lumineon',
      'Frillish',
      'Jellicent',
      'Alomomola',
    ],
    id: 26,
    pokemon: null,
    location: 'Route 17',
    status: null,
  },
  {
    filter: [
      'Horsea',
      'Seadra',
      'Chinchou',
      'Qwilfish',
      'Kingdra',
      'Finneon',
      'Lumineon',
      'Watchog',
      'Audino',
      'Throh',
      'Sawk',
      'Dwebble',
      'Crustle',
      'Scraggy',
      'Frillish',
      'Jellicent',
      'Alomomola',
      'Larvesta',
    ],
    id: 27,
    pokemon: null,
    location: 'Route 18',
    status: null,
  },
  {
    filter: ['Boldore', 'Woobat', 'Drilbur', 'Gurdurr', 'Cubchoo', 'Cryogonal'],
    id: 28,
    pokemon: null,
    location: 'Twist Mountain',
    status: null,
  },
  {
    filter: ['Barboach', 'Whiscash', 'Palpitoad', 'Seismitoad', 'Shelmet', 'Stunfisk'],
    id: 29,
    pokemon: null,
    location: 'Icirrus City',
    status: null,
  },
  {
    filter: [
      'Tranquill',
      'Vanillite',
      'Deerling',
      'Mienfoo',
      'Druddigon',
      'Cubchoo',
      'Vanillish',
      'Sawsbuck',
      'Beartic',
      'Audino',
      'Emolga',
      'Unfezant',
      'Basculin',
      'Dratini',
      'Dragonair',
    ],
    id: 30,
    pokemon: null,
    location: 'Dragonspiral Tower',
    status: null,
  },
  {
    filter: ['Barboach', 'Whiscash', 'Palpitoad', 'Seismitoad', 'Shelmet', 'Stunfisk'],
    id: 31,
    pokemon: null,
    location: 'Route 8',
    status: null,
  },
  {
    filter: ['Barboach', 'Whiscash', 'Palpitoad', 'Seismitoad', 'Shelmet', 'Stunfisk'],
    id: 32,
    pokemon: null,
    location: 'Moor of Icirrus',
    status: null,
  },
  {
    filter: [
      'Liepard',
      'Audino',
      'Garbodor',
      'Minccino',
      'Cinccino',
      'Gothorita',
      'Gothitelle',
      'Duosion',
      'Reuniclus',
      'Emolga',
      'Pawniard',
    ],
    id: 33,
    pokemon: null,
    location: 'Route 9',
    status: null,
  },
  {
    filter: [
      'Herdier',
      'Stoutland',
      'Audino',
      'Throh',
      'Sawk',
      'Emolga',
      'Foongus',
      'Amoonguss',
      'Bouffalant',
      'Rufflet',
      'Vullaby',
    ],
    id: 35,
    pokemon: null,
    location: 'Route 10',
    status: null,
  },
  {
    filter: [
      'Fraxure',
      'Mienfoo',
      'Rufflet',
      'Vullaby',
      'Heatmor',
      'Boldore',
      'Woobat',
      'Durant',
      'Deino',
      'Excadrill',
      'Basculin',
      'Poliwag',
      'Poliwhirl',
      'Terrakion',
    ],
    id: 36,
    pokemon: null,
    location: 'Victory Road',
    status: null,
  },
];

export default B_W;
