import type { TEncounter } from 'constants/types';

const B_W_2: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
    filterKey: 'bw2-0',
  },
  {
    id: 1,
    pokemon: null,
    location: 'Aspertia City',
    status: null,
    filterKey: 'bw2-1',
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 19',
    status: null,
    filterKey: 'bw2-2',
  },
  {
    id: 3,
    pokemon: null,
    location: 'Floccesy Town',
    status: null,
    filterKey: 'bw2-3',
  },
  {
    id: 4,
    pokemon: null,
    location: 'Route 20',
    status: null,
    filterKey: 'bw2-4',
  },
  {
    id: 5,
    pokemon: null,
    location: 'Floccesy Ranch',
    status: null,
    filterKey: 'bw2-5',
  },
  {
    id: 6,
    pokemon: null,
    location: 'Virbank City',
    status: null,
    filterKey: 'bw2-6',
  },
  {
    id: 7,
    pokemon: null,
    location: 'Virbank Complex',
    status: null,
    filterKey: 'bw2-7',
  },
  {
    id: 8,
    pokemon: null,
    location: 'Castelia City',
    status: null,
    filterKey: 'bw2-8',
  },
  {
    id: 9,
    pokemon: null,
    location: 'Castelia Sewers',
    status: null,
    filterKey: 'bw2-9',
  },
  {
    id: 10,
    pokemon: null,
    location: 'Relic Passage',
    status: null,
    filterKey: 'bw2-10',
  },
  {
    id: 11,
    pokemon: null,
    location: 'Route 4',
    status: null,
    filterKey: 'bw2-11',
  },
  {
    id: 12,
    pokemon: null,
    location: 'Desert Resort',
    status: null,
    filterKey: 'bw2-12',
  },
  {
    id: 13,
    pokemon: null,
    location: 'Relic Castle',
    status: null,
    filterKey: 'bw2-13',
  },
  {
    id: 14,
    pokemon: null,
    location: 'Route 16',
    status: null,
    filterKey: 'bw2-14',
  },
  {
    id: 15,
    pokemon: null,
    location: 'Lostlorn Forest',
    status: null,
    filterKey: 'bw2-15',
  },
  {
    id: 16,
    pokemon: null,
    location: 'Route 5',
    status: null,
    filterKey: 'bw2-16',
  },
  {
    id: 43,
    pokemon: null,
    location: 'Hidden Grotto',
    status: null,
    filterKey: 'bw2-43',
  },
  {
    id: 17,
    pokemon: null,
    location: 'Driftveil Drawbridge',
    status: null,
    filterKey: 'bw2-17',
  },
  {
    id: 18,
    pokemon: null,
    location: 'Driftveil City',
    status: null,
    filterKey: 'bw2-18',
  },
  {
    id: 19,
    pokemon: null,
    location: 'Route 6',
    status: null,
    filterKey: 'bw2-19',
  },
  {
    id: 21,
    pokemon: null,
    location: 'Mistralton Cave',
    status: null,
    filterKey: 'bw2-21',
  },
  {
    id: 22,
    pokemon: null,
    location: 'Chargestone Cave',
    status: null,
    filterKey: 'bw2-22',
  },
  {
    id: 24,
    pokemon: null,
    location: 'Route 7',
    status: null,
    filterKey: 'bw2-24',
  },
  {
    id: 25,
    pokemon: null,
    location: 'Celestial Tower',
    status: null,
    filterKey: 'bw2-25',
  },
  {
    id: 26,
    pokemon: null,
    location: 'Reversal Mountain',
    status: null,
    filterKey: 'bw2-26',
  },
  {
    id: 27,
    pokemon: null,
    location: 'Strange House',
    status: null,
    filterKey: 'bw2-27',
  },
  {
    id: 28,
    pokemon: null,
    location: 'Undella Town',
    status: null,
    filterKey: 'bw2-28',
  },
  {
    id: 29,
    pokemon: null,
    location: 'Undella Bay',
    status: null,
    filterKey: 'bw2-29',
  },
  {
    id: 30,
    pokemon: null,
    location: 'Route 13',
    status: null,
    filterKey: 'bw2-30',
  },
  {
    id: 42,
    pokemon: null,
    location: 'Route 14',
    status: null,
    filterKey: 'bw2-42',
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 12',
    status: null,
    filterKey: 'bw2-31',
  },
  {
    id: 32,
    pokemon: null,
    location: 'Village Bridge',
    status: null,
    filterKey: 'bw2-32',
  },
  {
    id: 33,
    pokemon: null,
    location: 'Route 11',
    status: null,
    filterKey: 'bw2-33',
  },
  {
    id: 34,
    pokemon: null,
    location: 'Route 9',
    status: null,
    filterKey: 'bw2-34',
  },
  {
    id: 35,
    pokemon: null,
    location: 'Seaside Cave',
    status: null,
    filterKey: 'bw2-35',
  },
  {
    id: 36,
    pokemon: null,
    location: 'Route 21',
    status: null,
    filterKey: 'bw2-36',
  },
  {
    id: 37,
    pokemon: null,
    location: 'Humilau City',
    status: null,
    filterKey: 'bw2-37',
  },
  {
    id: 38,
    pokemon: null,
    location: 'Route 22',
    status: null,
    filterKey: 'bw2-38',
  },
  {
    id: 39,
    pokemon: null,
    location: 'Giant Chasm',
    status: null,
    filterKey: 'bw2-39',
  },
  {
    id: 40,
    pokemon: null,
    location: 'Route 23',
    status: null,
    filterKey: 'bw2-40',
  },
  {
    id: 41,
    pokemon: null,
    location: 'Victory Road',
    status: null,
    filterKey: 'bw2-41',
  },
];

export default B_W_2;
