import { TEncounter } from 'constants/types';

const B_W_2: TEncounter[] = [
  {
    filter: ['Snivy', 'Tepig', 'Oshawott'],
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    filter: ['Snivy', 'Tepig', 'Oshawott'],
    id: 1,
    pokemon: null,
    location: 'Aspertia City',
    status: null,
  },
  {
    filter: ['Poliwag', 'Poliwhirl', 'Politoed', 'Patrat', 'Purrloin', 'Basculin'],
    id: 2,
    pokemon: null,
    location: 'Route 19',
    status: null,
  },
  {
    id: 3,
    pokemon: null,
    location: 'Floccesy Town',
    status: null,
  },
  {
    filter: [
      'Poliwag',
      'Poliwhirl',
      'Marill',
      'Azumarill',
      'Politoed',
      'Sunkern',
      'Dunsparce',
      'Azurill',
      'Patrat',
      'Purrloin',
      'Pidove',
      'Audino',
      'Sewaddle',
      'Venipede',
      'Basculin',
    ],
    id: 4,
    pokemon: null,
    location: 'Route 20',
    status: null,
  },
  {
    filter: [
      'Poliwag',
      'Poliwhirl',
      'Marill',
      'Azumarill',
      'Politoed',
      'Azurill',
      'Basculin',
      'Psyduck',
      'Mareep',
      'Dunsparce',
      'Riolu',
      'Patrat',
      'Lillipup',
      'Pidove',
      'Audino',
    ],
    id: 5,
    pokemon: null,
    location: 'Floccesy Ranch',
    status: null,
  },
  {
    filter: [
      'Krabby',
      'Kingler',
      'Qwilfish',
      'Finneon',
      'Lumineon',
      'Frillish',
      'Jellicent',
      'Alomomola',
    ],
    id: 6,
    pokemon: null,
    location: 'Virbank City',
    status: null,
  },
  {
    filter: [
      'Koffing',
      'Growlithe',
      'Magnemite',
      'Krabby',
      'Kingler',
      'Qwilfish',
      'Elekid',
      'Magby',
      'Finneon',
      'Lumineon',
      'Patrat',
      'Pidove',
      'Audino',
      'Frillish',
      'Jellicent',
      'Alomomola',
    ],
    id: 7,
    pokemon: null,
    location: 'Virbank Complex',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Eevee',
      'Skitty',
      'Delcatty',
      'Buneary',
      'Lopunny',
      'Pidove',
      'Audino',
      'Cottonee',
      'Whimsicott',
      'Petilil',
      'Lilligant',
    ],
    id: 8,
    pokemon: null,
    location: 'Castelia City',
    status: null,
  },
  {
    filter: ['Rattata', 'Zubat', 'Grimer', 'Muk'],
    id: 9,
    pokemon: null,
    location: 'Castelia Sewers',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Onix',
      'Roggenrola',
      'Woobat',
      'Timburr',
      'Drilbur',
      'Raticate',
      'Boldore',
      'Gurdurr',
      'Marill',
      'Basculin',
      'Azumarill',
      'Poliwhirl',
    ],
    id: 10,
    pokemon: null,
    location: 'Relic Passage',
    status: null,
  },
  {
    filter: [
      'Qwilfish',
      'Clamperl',
      'Huntail',
      'Gorebyss',
      'Relicanth',
      'Finneon',
      'Lumineon',
      'Sandile',
      'Darumaka',
      'Scraggy',
      'Trubbish',
      'Minccino',
      'Frillish',
      'Jellicent',
      'Alomomola',
    ],
    id: 11,
    pokemon: null,
    location: 'Route 4',
    status: null,
  },
  {
    filter: ['Sandshrew', 'Trapinch', 'Sandile', 'Darumaka', 'Maractus', 'Dwebble', 'Sigilyph'],
    id: 12,
    pokemon: null,
    location: 'Desert Resort',
    status: null,
  },
  {
    filter: [
      'Sandile',
      'Sandshrew',
      'Yamask',
      'Krokorok',
      'Cofagrigus',
      'Sandslash',
      'Onix',
      'Baltoy',
      'Volcarona',
    ],
    id: 13,
    pokemon: null,
    location: 'Relic Castle',
    status: null,
  },
  {
    filter: [
      'Liepard',
      'Audino',
      'Trubbish',
      'Minccino',
      'Cinccino',
      'Gothita',
      'Solosis',
      'Emolga',
    ],
    id: 14,
    pokemon: null,
    location: 'Route 16',
    status: null,
  },
  {
    filter: [
      'Poliwag',
      'Poliwhirl',
      'Pinsir',
      'Politoed',
      'Heracross',
      'Roselia',
      'Roserade',
      'Combee',
      'Vespiquen',
      'Buizel',
      'Floatzel',
      'Pansage',
      'Pansear',
      'Panpour',
      'Audino',
      'Swadloon',
      'Leavanny',
      'Venipede',
      'Whirlipede',
      'Cottonee',
      'Whimsicott',
      'Petilil',
      'Lilligant',
      'Basculin',
      'Emolga',
    ],
    id: 15,
    pokemon: null,
    location: 'Lostlorn Forest',
    status: null,
  },
  {
    filter: [
      'Liepard',
      'Audino',
      'Trubbish',
      'Minccino',
      'Cinccino',
      'Gothita',
      'Solosis',
      'Emolga',
    ],
    id: 16,
    pokemon: null,
    location: 'Route 5',
    status: null,
  },
  {
    filter: ['Ducklett'],
    id: 17,
    pokemon: null,
    location: 'Driftveil Drawbridge',
    status: null,
  },
  {
    filter: ['Zorua'],
    id: 18,
    pokemon: null,
    location: 'Driftveil City',
    status: null,
  },
  {
    filter: [
      'Poliwag',
      'Poliwhirl',
      'Marill',
      'Azumarill',
      'Politoed',
      'Dunsparce',
      'Castform',
      'Tranquill',
      'Unfezant',
      'Audino',
      'Swadloon',
      'Leavanny',
      'Basculin',
      'Deerling',
      'Emolga',
      'Karrablast',
      'Foongus',
      'Shelmet',
    ],
    id: 19,
    pokemon: null,
    location: 'Route 6',
    status: null,
  },
  {
    filter: ['Aron', 'Boldore', 'Woobat', 'Drilbur', 'Axew'],
    id: 21,
    pokemon: null,
    location: 'Mistralton Cave',
    status: null,
  },
  {
    filter: ['Boldore', 'Joltik', 'Ferroseed', 'Klink', 'Tynamo', 'Drilbur', 'Nosepass'],
    id: 22,
    pokemon: null,
    location: 'Chargestone Cave',
    status: null,
  },
  {
    filter: [
      'Zangoose',
      'Seviper',
      'Watchog',
      'Tranquill',
      'Unfezant',
      'Zebstrika',
      'Audino',
      'Deerling',
      'Emolga',
      'Foongus',
      'Cubchoo',
    ],
    id: 23,
    pokemon: null,
    location: 'Mistralton City',
    status: null,
  },
  {
    filter: [
      'Zangoose',
      'Seviper',
      'Watchog',
      'Tranquill',
      'Unfezant',
      'Zebstrika',
      'Audino',
      'Deerling',
      'Emolga',
      'Foongus',
      'Cubchoo',
    ],
    id: 24,
    pokemon: null,
    location: 'Route 7',
    status: null,
  },
  {
    filter: ['Litwick', 'Elgyem', 'Golbat', 'Mesprit'],
    id: 25,
    pokemon: null,
    location: 'Celestial Tower',
    status: null,
  },
  {
    filter: [
      'Skarmory',
      'Numel',
      'Camerupt',
      'Spoink',
      'Grumpig',
      'Drifblim',
      'Skorupi',
      'Vibrava',
      'Audino',
      'Cacturne',
      'Trapinch',
      'Boldore',
      'Woobat',
      'Excadrill',
      'Heatran',
    ],
    id: 26,
    pokemon: null,
    location: 'Reversal Mountain',
    status: null,
  },
  {
    filter: [
      'Raticate',
      'Golbat',
      'Banette',
      'Gothita',
      'Gothorita',
      'Solosis',
      'Duosion',
      'Litwick',
    ],
    id: 27,
    pokemon: null,
    location: 'Strange House',
    status: null,
  },
  {
    filter: [
      'Shellder',
      'Cloyster',
      'Staryu',
      'Starmie',
      'Luvdisc',
      'Basculin',
      'Frillish',
      'Jellicent',
    ],
    id: 28,
    pokemon: null,
    location: 'Undella Town',
    status: null,
  },
  {
    filter: [
      'Chinchou',
      'Lanturn',
      'Remoraid',
      'Octillery',
      'Mantine',
      'Wailmer',
      'Wailord',
      'Spheal',
      'Sealeo',
      'Walrein',
      'Mantyke',
      'Frillish',
      'Jellicent',
    ],
    id: 29,
    pokemon: null,
    location: 'Undella Bay',
    status: null,
  },
  {
    filter: [
      'Shellder',
      'Cloyster',
      'Tangela',
      'Staryu',
      'Starmie',
      'Pelipper',
      'Lunatone',
      'Solrock',
      'Absol',
      'Luvdisc',
      'Drifblim',
      'Tangrowth',
      'Audino',
      'Basculin',
      'Emolga',
      'Frillish',
      'Jellicent',
    ],
    id: 30,
    pokemon: null,
    location: 'Route 13',
    status: null,
  },
  {
    filter: [
      'Pinsir',
      'Dunsparce',
      'Heracross',
      'Roselia',
      'Roserade',
      'Combee',
      'Vespiquen',
      'Tranquill',
      'Unfezant',
      'Audino',
      'Sewaddle',
      'Leavanny',
      'Emolga',
    ],
    id: 31,
    pokemon: null,
    location: 'Route 12',
    status: null,
  },
  {
    filter: [
      'Golduck',
      'Lapras',
      'Marill',
      'Azumarill',
      'Dunsparce',
      'Carvanha',
      'Sharpedo',
      'Zangoose',
      'Seviper',
      'Audino',
      'Basculin',
      'Emolga',
    ],
    id: 32,
    pokemon: null,
    location: 'Village Bridge',
    status: null,
  },
  {
    filter: [
      'Golduck',
      'Goldeen',
      'Seaking',
      'Marill',
      'Azumarill',
      'Gligar',
      'Zangoose',
      'Seviper',
      'Buizel',
      'Floatzel',
      'Gliscor',
      'Audino',
      'Basculin',
      'Emolga',
      'Karrablast',
      'Amoonguss',
      'Shelmet',
    ],
    id: 33,
    pokemon: null,
    location: 'Route 11',
    status: null,
  },
  {
    filter: [
      'Muk',
      'Liepard',
      'Audino',
      'Garbodor',
      'Minccino',
      'Cinccino',
      'Gothorita',
      'Gothitelle',
      'Duosion',
      'Reuniclus',
      'Emolga',
      'Pawniard',
    ],
    id: 34,
    pokemon: null,
    location: 'Route 9',
    status: null,
  },
  {
    filter: [
      'Golduck',
      'Shuckle',
      'Seel',
      'Dewgong',
      'Shellder',
      'Cloyster',
      'Luvdisc',
      'Boldore',
      'Woobat',
      'Excadrill',
      'Frillish',
      'Jellicent',
      'Tynamo',
      'Eelektrik',
    ],
    id: 35,
    pokemon: null,
    location: 'Seaside Cave',
    status: null,
  },
  {
    filter: [
      'Remoraid',
      'Octillery',
      'Mantine',
      'Luvdisc',
      'Mantyke',
      'Frillish',
      'Jellicent',
      'Alomomola',
    ],
    id: 36,
    pokemon: null,
    location: 'Route 21',
    status: null,
  },
  {
    filter: [
      'Shellder',
      'Cloyster',
      'Staryu',
      'Starmie',
      'Corsola',
      'Luvdisc',
      'Basculin',
      'Frillish',
      'Jellicent',
    ],
    id: 37,
    pokemon: null,
    location: 'Humilau City',
    status: null,
  },
  {
    filter: [
      'Golduck',
      'Goldeen',
      'Seaking',
      'Marill',
      'Azumarill',
      'Delibird',
      'Pelipper',
      'Lunatone',
      'Solrock',
      'Audino',
      'Emolga',
      'Amoonguss',
      'Mienfoo',
      'Basculin',
    ],
    id: 38,
    pokemon: null,
    location: 'Route 22',
    status: null,
  },
  {
    filter: [
      'Golbat',
      'Tangela',
      'Swellow',
      'Lunatone',
      'Solrock',
      'Absol',
      'Drifblim',
      'Crobat',
      'Tangrowth',
      'Audino',
      'Emolga',
      'Piloswine',
      'Delibird',
      'Sneasel',
      'Pelipper',
      'Vanillish',
      'Boldore',
      'Excadrill',
      'Basculin',
      'Dewgong',
      'Poliwag',
      'Poliwhirl',
      'Poliwrath',
      'Clefairy',
      'Ditto',
      'Metang',
      'Mamoswine',
      'Clefable',
      'Metagross',
    ],
    id: 39,
    pokemon: null,
    location: 'Giant Chasm',
    status: null,
  },
  {
    filter: [
      'Golduck',
      'Poliwag',
      'Poliwhirl',
      'Poliwrath',
      'Gligar',
      'Buizel',
      'Floatzel',
      'Gliscor',
      'Audino',
      'Throh',
      'Sawk',
      'Basculin',
      'Emolga',
      'Amoonguss',
      'Mienfoo',
      'Mienshao',
      'Bouffalant',
      'Rufflet',
      'Vullaby',
    ],
    id: 40,
    pokemon: null,
    location: 'Route 23',
    status: null,
  },
  {
    filter: [
      'Banette',
      'Golurk',
      'Marill',
      'Basculin',
      'Azumarill',
      'Poliwag',
      'Poliwhirl',
      'Roselia',
      'Cottonee',
      'Petilil',
      'Dunsparce',
      'Whimsicott',
      'Lilligant',
      'Audino',
      'Roserade',
      'Altaria',
      'Tranquill',
      'Unfezant',
      'Buizel',
      'Politoed',
      'Onix',
      'Boldore',
      'Excadrill',
      'Druddigon',
      'Zweilous',
      'Gurdurr',
      'Throh',
      'Sawk',
    ],
    id: 41,
    pokemon: null,
    location: 'Victory Road',
    status: null,
  },
];

export default B_W_2;
