import { TEncounter } from 'constants/types';

const B_W_2: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    id: 1,
    pokemon: null,
    location: 'Aspertia City',
    status: null,
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 19',
    status: null,
  },
  {
    id: 3,
    pokemon: null,
    location: 'Floccesy Town',
    status: null,
  },
  {
    id: 4,
    pokemon: null,
    location: 'Route 20',
    status: null,
  },
  {
    id: 5,
    pokemon: null,
    location: 'Floccesy Ranch',
    status: null,
  },
  {
    id: 6,
    pokemon: null,
    location: 'Virbank City',
    status: null,
  },
  {
    id: 7,
    pokemon: null,
    location: 'Virbank Complex',
    status: null,
  },
  {
    id: 8,
    pokemon: null,
    location: 'Castelia City',
    status: null,
  },
  {
    id: 9,
    pokemon: null,
    location: 'Castelia Sewers',
    status: null,
  },
  {
    id: 10,
    pokemon: null,
    location: 'Relic Passage',
    status: null,
  },
  {
    id: 11,
    pokemon: null,
    location: 'Route 4',
    status: null,
  },
  {
    id: 12,
    pokemon: null,
    location: 'Desert Resort',
    status: null,
  },
  {
    id: 13,
    pokemon: null,
    location: 'Relic Castle',
    status: null,
  },
  {
    id: 14,
    pokemon: null,
    location: 'Route 16',
    status: null,
  },
  {
    id: 15,
    pokemon: null,
    location: 'Lostlorn Forest',
    status: null,
  },
  {
    id: 16,
    pokemon: null,
    location: 'Route 5',
    status: null,
  },
  {
    id: 17,
    pokemon: null,
    location: 'Driftveil Drawbridge',
    status: null,
  },
  {
    id: 18,
    pokemon: null,
    location: 'Driftveil City',
    status: null,
  },
  {
    id: 19,
    pokemon: null,
    location: 'Route 6',
    status: null,
  },
  {
    id: 21,
    pokemon: null,
    location: 'Mistralton Cave',
    status: null,
  },
  {
    id: 22,
    pokemon: null,
    location: 'Chargestone Cave',
    status: null,
  },
  {
    id: 23,
    pokemon: null,
    location: 'Mistralton City',
    status: null,
  },
  {
    id: 24,
    pokemon: null,
    location: 'Route 7',
    status: null,
  },
  {
    id: 25,
    pokemon: null,
    location: 'Celestial Tower',
    status: null,
  },
  {
    id: 26,
    pokemon: null,
    location: 'Reversal Mountain',
    status: null,
  },
  {
    id: 27,
    pokemon: null,
    location: 'Strange House',
    status: null,
  },
  {
    id: 28,
    pokemon: null,
    location: 'Undella Town',
    status: null,
  },
  {
    id: 29,
    pokemon: null,
    location: 'Undella Bay',
    status: null,
  },
  {
    id: 30,
    pokemon: null,
    location: 'Route 13',
    status: null,
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 12',
    status: null,
  },
  {
    id: 32,
    pokemon: null,
    location: 'Village Bridge',
    status: null,
  },
  {
    id: 33,
    pokemon: null,
    location: 'Route 11',
    status: null,
  },
  {
    id: 34,
    pokemon: null,
    location: 'Route 9',
    status: null,
  },
  {
    id: 35,
    pokemon: null,
    location: 'Seaside Cave',
    status: null,
  },
  {
    id: 36,
    pokemon: null,
    location: 'Route 21',
    status: null,
  },
  {
    id: 37,
    pokemon: null,
    location: 'Humilau City',
    status: null,
  },
  {
    id: 38,
    pokemon: null,
    location: 'Route 22',
    status: null,
  },
  {
    id: 39,
    pokemon: null,
    location: 'Giant Chasm',
    status: null,
  },
  {
    id: 40,
    pokemon: null,
    location: 'Route 23',
    status: null,
  },
  {
    id: 41,
    pokemon: null,
    location: 'Victory Road',
    status: null,
  },
];

export default B_W_2;
