import type { TEncounter } from 'constants/types';

const BD_SP: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
    filterKey: 'bdsp-0',
  },
  {
    id: 1,
    pokemon: null,
    location: 'Twinleaf Town',
    status: null,
    filterKey: 'bdsp-1',
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 201',
    status: null,
    filterKey: 'bdsp-2',
  },
  {
    id: 3,
    pokemon: null,
    location: 'Lake Verity',
    status: null,
    filterKey: 'bdsp-3',
  },
  {
    id: 5,
    pokemon: null,
    location: 'Route 202',
    status: null,
    filterKey: 'bdsp-5',
  },
  {
    id: 7,
    pokemon: null,
    location: 'Route 203',
    status: null,
    filterKey: 'bdsp-7',
  },
  {
    id: 8,
    pokemon: null,
    location: 'Oreburgh Gate',
    status: null,
    filterKey: 'bdsp-8',
  },
  {
    id: 9,
    pokemon: null,
    location: 'Oreburgh City',
    status: null,
    filterKey: 'bdsp-9',
  },
  {
    id: 10,
    pokemon: null,
    location: 'Oreburgh Mine',
    status: null,
    filterKey: 'bdsp-10',
  },
  {
    id: 11,
    pokemon: null,
    location: 'Route 204',
    status: null,
    filterKey: 'bdsp-11',
  },
  {
    id: 12,
    pokemon: null,
    location: 'Ravaged Path',
    status: null,
    filterKey: 'bdsp-12',
  },
  {
    id: 14,
    pokemon: null,
    location: 'Floaroma Meadow',
    status: null,
    filterKey: 'bdsp-14',
  },
  {
    id: 15,
    pokemon: null,
    location: 'Valley Windworks',
    status: null,
    filterKey: 'bdsp-15',
  },
  {
    id: 16,
    pokemon: null,
    location: 'Route 205',
    status: null,
    filterKey: 'bdsp-16',
  },
  {
    id: 17,
    pokemon: null,
    location: 'Eterna Forest',
    status: null,
    filterKey: 'bdsp-17',
  },
  {
    id: 18,
    pokemon: null,
    location: 'Eterna City',
    status: null,
    filterKey: 'bdsp-18',
  },
  {
    id: 63,
    pokemon: null,
    location: 'Grand Underground',
    status: null,
    filterKey: 'bdsp-63',
  },
  {
    id: 19,
    pokemon: null,
    location: 'Old Chateau',
    status: null,
    filterKey: 'bdsp-19',
  },
  {
    id: 20,
    pokemon: null,
    location: 'Route 206',
    status: null,
    filterKey: 'bdsp-20',
  },
  {
    id: 21,
    pokemon: null,
    location: 'Wayward Cave',
    status: null,
    filterKey: 'bdsp-21',
  },
  {
    id: 22,
    pokemon: null,
    location: 'Route 207',
    status: null,
    filterKey: 'bdsp-22',
  },
  {
    id: 23,
    pokemon: null,
    location: 'Mt. Coronet',
    status: null,
    filterKey: 'bdsp-23',
  },
  {
    id: 24,
    pokemon: null,
    location: 'Route 208',
    status: null,
    filterKey: 'bdsp-24',
  },
  {
    id: 26,
    pokemon: null,
    location: 'Hearthome City',
    status: null,
    filterKey: 'bdsp-26',
  },
  {
    id: 27,
    pokemon: null,
    location: 'Route 209',
    status: null,
    filterKey: 'bdsp-27',
  },
  {
    id: 29,
    pokemon: null,
    location: 'Solaceon Ruins',
    status: null,
    filterKey: 'bdsp-29',
  },
  {
    id: 30,
    pokemon: null,
    location: 'Lost Tower',
    status: null,
    filterKey: 'bdsp-30',
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 215',
    status: null,
    filterKey: 'bdsp-31',
  },
  {
    id: 32,
    pokemon: null,
    location: 'Veilstone City',
    status: null,
    filterKey: 'bdsp-32',
  },
  {
    id: 33,
    pokemon: null,
    location: 'Route 214',
    status: null,
    filterKey: 'bdsp-33',
  },
  {
    id: 34,
    pokemon: null,
    location: 'Maniac Tunnel',
    status: null,
    filterKey: 'bdsp-34',
  },
  {
    id: 35,
    pokemon: null,
    location: 'Valor Lakefront',
    status: null,
    filterKey: 'bdsp-35',
  },
  {
    id: 36,
    pokemon: null,
    location: 'Route 213',
    status: null,
    filterKey: 'bdsp-36',
  },
  {
    id: 37,
    pokemon: null,
    location: 'Pastoria City',
    status: null,
    filterKey: 'bdsp-37',
  },
  {
    id: 62,
    pokemon: null,
    location: 'The Great Marsh',
    status: null,
    filterKey: 'bdsp-62',
  },
  {
    id: 38,
    pokemon: null,
    location: 'Route 212',
    status: null,
    filterKey: 'bdsp-38',
  },
  {
    id: 64,
    pokemon: null,
    location: 'Pokémon Mansion',
    status: null,
    filterKey: 'bdsp-64',
  },
  {
    id: 65,
    pokemon: null,
    location: 'Trophy Garden',
    status: null,
    filterKey: 'bdsp-65',
  },
  {
    id: 39,
    pokemon: null,
    location: 'Route 210',
    status: null,
    filterKey: 'bdsp-39',
  },
  {
    id: 40,
    pokemon: null,
    location: 'Celestic Town',
    status: null,
    filterKey: 'bdsp-40',
  },
  {
    id: 41,
    pokemon: null,
    location: 'Fuego Ironworks',
    status: null,
    filterKey: 'bdsp-41',
  },
  {
    id: 42,
    pokemon: null,
    location: 'Route 219',
    status: null,
    filterKey: 'bdsp-42',
  },
  {
    id: 43,
    pokemon: null,
    location: 'Route 220',
    status: null,
    filterKey: 'bdsp-43',
  },
  {
    id: 44,
    pokemon: null,
    location: 'Route 221',
    status: null,
    filterKey: 'bdsp-44',
  },
  {
    id: 45,
    pokemon: null,
    location: 'Route 218',
    status: null,
    filterKey: 'bdsp-45',
  },
  {
    id: 46,
    pokemon: null,
    location: 'Canalave City',
    status: null,
    filterKey: 'bdsp-46',
  },
  {
    id: 47,
    pokemon: null,
    location: 'Iron Island',
    status: null,
    filterKey: 'bdsp-47',
  },
  {
    id: 48,
    pokemon: null,
    location: 'Lake Valor',
    status: null,
    filterKey: 'bdsp-48',
  },
  {
    id: 49,
    pokemon: null,
    location: 'Route 211',
    status: null,
    filterKey: 'bdsp-49',
  },
  {
    id: 50,
    pokemon: null,
    location: 'Route 216',
    status: null,
    filterKey: 'bdsp-50',
  },
  {
    id: 51,
    pokemon: null,
    location: 'Route 217',
    status: null,
    filterKey: 'bdsp-51',
  },
  {
    id: 52,
    pokemon: null,
    location: 'Acuity Lakefront',
    status: null,
    filterKey: 'bdsp-52',
  },
  {
    id: 53,
    pokemon: null,
    location: 'Lake Acuity',
    status: null,
    filterKey: 'bdsp-53',
  },
  {
    id: 54,
    pokemon: null,
    location: 'Snowpoint City',
    status: null,
    filterKey: 'bdsp-54',
  },
  {
    id: 56,
    pokemon: null,
    location: 'Sendoff Spring',
    status: null,
    filterKey: 'bdsp-56',
  },
  {
    id: 57,
    pokemon: null,
    location: 'Route 222',
    status: null,
    filterKey: 'bdsp-57',
  },
  {
    id: 58,
    pokemon: null,
    location: 'Sunyshore City',
    status: null,
    filterKey: 'bdsp-58',
  },
  {
    id: 59,
    pokemon: null,
    location: 'Route 223',
    status: null,
    filterKey: 'bdsp-59',
  },
  {
    id: 60,
    pokemon: null,
    location: 'Pokemon League',
    status: null,
    filterKey: 'bdsp-60',
  },
  {
    id: 61,
    pokemon: null,
    location: 'Victory Road',
    status: null,
    filterKey: 'bdsp-61',
  },
];

export default BD_SP;
