import { TEncounter } from 'constants/types';

const SINNOH: TEncounter[] = [
  {
    filter: ['Turtwig', 'Chimchar', 'Piplup'],
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    filter: ['Psyduck', 'Golduck', 'Goldeen', 'Seaking', 'Magikarp', 'Gyarados'],
    id: 1,
    pokemon: null,
    location: 'Twinleaf Town',
    status: null,
  },
  {
    filter: [
      'Nidoran♀',
      'Nidoran♂',
      'Growlithe',
      'Doduo',
      'Turtwig',
      'Chimchar',
      'Piplup',
      'Starly',
      'Bidoof',
      'Kricketot',
    ],
    id: 2,
    pokemon: null,
    location: 'Route 201',
    status: null,
  },
  {
    filter: [
      'Psyduck',
      'Golduck',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Gyarados',
      'Wobbuffet',
      'Surskit',
      'Lunatone',
      'Solrock',
      'Turtwig',
      'Chimchar',
      'Piplup',
      'Starly',
      'Staravia',
      'Bidoof',
      'Bibarel',
    ],
    id: 3,
    pokemon: null,
    location: 'Lake Verity',
    status: null,
  },
  {
    filter: ['Growlithe', 'Sentret', 'Zigzagoon', 'Starly', 'Bidoof', 'Kricketot', 'Shinx'],
    id: 5,
    pokemon: null,
    location: 'Route 202',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Psyduck',
      'Golduck',
      'Abra',
      'Cubone',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Gyarados',
      'Pineco',
      'Lotad',
      'Seedot',
      'Ralts',
      'Kirlia',
      'Starly',
      'Bidoof',
      'Kricketot',
      'Shinx',
    ],
    id: 7,
    pokemon: null,
    location: 'Route 203',
    status: null,
  },
  {
    filter: ['Zubat', 'Psyduck', 'Geodude'],
    id: 8,
    pokemon: null,
    location: 'Oreburgh Gate',
    status: null,
  },
  {
    filter: [
      'Abra',
      'Omanyte',
      'Kabuto',
      'Aerodactyl',
      'Lileep',
      'Anorith',
      'Cranidos',
      'Shieldon',
    ],
    id: 9,
    pokemon: null,
    location: 'Oreburgh City',
    status: null,
  },
  {
    filter: ['Zubat', 'Geodude', 'Onix'],
    id: 10,
    pokemon: null,
    location: 'Oreburgh Mine',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Weedle',
      'Zubat',
      'Psyduck',
      'Golduck',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Gyarados',
      'Pineco',
      'Wurmple',
      'Lotad',
      'Seedot',
      'Ralts',
      'Kirlia',
      'Starly',
      'Bidoof',
      'Kricketot',
      'Shinx',
      'Budew',
    ],
    id: 11,
    pokemon: null,
    location: 'Route 204',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Golbat',
      'Psyduck',
      'Golduck',
      'Geodude',
      'Magikarp',
      'Gyarados',
      'Barboach',
      'Whiscash',
    ],
    id: 12,
    pokemon: null,
    location: 'Ravaged Path',
    status: null,
  },
  {
    filter: ['Wurmple', 'Combee', 'Aipom', 'Burmy', 'Cherubi', 'Heracross', 'Munchlax'],
    id: 14,
    pokemon: null,
    location: 'Floaroma Meadow',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Tentacruel',
      'Shellder',
      'Magikarp',
      'Gyarados',
      'Mareep',
      'Elekid',
      'Wingull',
      'Pelipper',
      'Electrike',
      'Bidoof',
      'Shinx',
      'Pachirisu',
      'Buizel',
      'Shellos',
      'Gastrodon',
      'Finneon',
      'Lumineon',
    ],
    id: 15,
    pokemon: null,
    location: 'Valley Windworks',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Tentacruel',
      'Shellder',
      'Magikarp',
      'Gyarados',
      'Hoppip',
      'Elekid',
      'Wingull',
      'Pelipper',
      'Bidoof',
      'Pachirisu',
      'Buizel',
      'Shellos',
      'Gastrodon',
      'Finneon',
      'Lumineon',
    ],
    id: 16,
    pokemon: null,
    location: 'Route 205',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Weedle',
      'Kakuna',
      'Gastly',
      'Hoothoot',
      'Murkrow',
      'Misdreavus',
      'Pineco',
      'Wurmple',
      'Silcoon',
      'Beautifly',
      'Cascoon',
      'Dustox',
      'Seedot',
      'Slakoth',
      'Nincada',
      'Bidoof',
      'Kricketot',
      'Budew',
      'Buneary',
    ],
    id: 17,
    pokemon: null,
    location: 'Eterna Forest',
    status: null,
  },
  {
    filter: ['Psyduck', 'Golduck', 'Magikarp', 'Gyarados', 'Barboach', 'Whiscash'],
    id: 18,
    pokemon: null,
    location: 'Eterna City',
    status: null,
  },
  {
    filter: ['Gastly', 'Haunter', 'Gengar', 'Rotom'],
    id: 19,
    pokemon: null,
    location: 'Old Chateau',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Machop',
      'Geodude',
      'Ponyta',
      'Gligar',
      'Larvitar',
      'Nosepass',
      'Baltoy',
      'Kricketot',
      'Kricketune',
      'Stunky',
      'Bronzor',
    ],
    id: 20,
    pokemon: null,
    location: 'Route 206',
    status: null,
  },
  {
    filter: [
      'Sandshrew',
      'Zubat',
      'Machop',
      'Geodude',
      'Ponyta',
      'Gligar',
      'Larvitar',
      'Nosepass',
      'Baltoy',
      'Kricketot',
      'Kricketune',
      'Stunky',
      'Bronzor',
      'Gible',
    ],
    id: 21,
    pokemon: null,
    location: 'Wayward Cave',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Machop',
      'Geodude',
      'Ponyta',
      'Gligar',
      'Phanpy',
      'Stantler',
      'Larvitar',
      'Kricketot',
    ],
    id: 22,
    pokemon: null,
    location: 'Route 207',
    status: null,
  },
  {
    filter: [
      'Clefairy',
      'Zubat',
      'Machop',
      'Geodude',
      'Cleffa',
      'Nosepass',
      'Meditite',
      'Chingling',
      'Bronzor',
      'Golbat',
      'Magikarp',
      'Barboach',
      'Gyarados',
      'Whiscash',
      'Machoke',
      'Graveler',
      'Medicham',
      'Bronzong',
      'Lunatone',
      'Solrock',
      'Noctowl',
      'Absol',
      'Snover',
      'Abomasnow',
      'Dratini',
      'Dragonair',
      'Feebas',
    ],
    id: 23,
    pokemon: null,
    location: 'Mt. Coronet',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Psyduck',
      'Golduck',
      'Machop',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Gyarados',
      'Dunsparce',
      'Smeargle',
      'Tyrogue',
      'Ralts',
      'Meditite',
      'Roselia',
      'Zangoose',
      'Seviper',
      'Barboach',
      'Whiscash',
      'Bidoof',
      'Bibarel',
      'Budew',
    ],
    id: 24,
    pokemon: null,
    location: 'Route 208',
    status: null,
  },
  {
    filter: ['Eevee'],
    id: 26,
    pokemon: null,
    location: 'Hearthome City',
    status: null,
  },
  {
    filter: [
      'Vulpix',
      'Zubat',
      'Psyduck',
      'Golduck',
      'Gastly',
      'Chansey',
      'Goldeen',
      'Seaking',
      'Tauros',
      'Magikarp',
      'Gyarados',
      'Snubbull',
      'Miltank',
      'Ralts',
      'Kirlia',
      'Roselia',
      'Duskull',
      'Starly',
      'Staravia',
      'Bibarel',
      'Bonsly',
      'Mime Jr.',
    ],
    id: 27,
    pokemon: null,
    location: 'Route 209',
    status: null,
  },
  {
    filter: ['Unown'],
    id: 29,
    pokemon: null,
    location: 'Solaceon Ruins',
    status: null,
  },
  {
    filter: ['Zubat', 'Gastly', 'Murkrow', 'Misdreavus', 'Duskull', 'Golbat'],
    id: 30,
    pokemon: null,
    location: 'Lost Tower',
    status: null,
  },
  {
    filter: [
      'Abra',
      'Kadabra',
      'Geodude',
      'Ponyta',
      'Drowzee',
      'Lickitung',
      'Scyther',
      'Marill',
      'Gligar',
      'Houndoom',
      'Mightyena',
      'Staravia',
      'Kricketune',
    ],
    id: 31,
    pokemon: null,
    location: 'Route 215',
    status: null,
  },
  {
    filter: ['Porygon'],
    id: 32,
    pokemon: null,
    location: 'Veilstone City',
    status: null,
  },
  {
    filter: [
      'Vulpix',
      'Zubat',
      'Psyduck',
      'Golduck',
      'Geodude',
      'Graveler',
      'Ponyta',
      'Rhyhorn',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Gyarados',
      'Sudowoodo',
      'Girafarig',
      'Gligar',
      'Houndour',
      'Houndoom',
      'Poochyena',
      'Mightyena',
      'Spoink',
      'Kricketune',
      'Stunky',
    ],
    id: 33,
    pokemon: null,
    location: 'Route 214',
    status: null,
  },
  {
    filter: ['Geodude', 'Hippopotas'],
    id: 34,
    pokemon: null,
    location: 'Maniac Tunnel',
    status: null,
  },
  {
    filter: [
      'Nidorina',
      'Nidorino',
      'Geodude',
      'Graveler',
      'Girafarig',
      'Houndour',
      'Staravia',
      'Bibarel',
      'Kricketune',
    ],
    id: 35,
    pokemon: null,
    location: 'Valor Lakefront',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Tentacruel',
      'Magikarp',
      'Gyarados',
      'Remoraid',
      'Octillery',
      'Swellow',
      'Wingull',
      'Pelipper',
      'Sharpedo',
      'Absol',
      'Buizel',
      'Floatzel',
      'Shellos',
      'Gastrodon',
      'Chatot',
    ],
    id: 36,
    pokemon: null,
    location: 'Route 213',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Tentacruel',
      'Magikarp',
      'Gyarados',
      'Remoraid',
      'Octillery',
      'Wingull',
      'Pelipper',
      'Shellos',
      'Gastrodon',
    ],
    id: 37,
    pokemon: null,
    location: 'Pastoria City',
    status: null,
  },
  {
    filter: [
      'Psyduck',
      'Marill',
      'Wooper',
      'Quagsire',
      'Magikarp',
      'Gyarados',
      'Barboach',
      'Carvanha',
      'Whiscash',
      'Tangela',
      'Hoothoot',
      'Noctowl',
      'Yanma',
      'Azurill',
      'Tropius',
      'Starly',
      'Bidoof',
      'Bibarel',
      'Budew',
      'Arbok',
      'Roselia',
      'Skorupi',
      'Croagunk',
      'Carnivine',
    ],
    id: 62,
    pokemon: null,
    location: 'The Great Marsh',
    status: null,
  },
  {
    filter: [
      'Psyduck',
      'Golduck',
      'Goldeen',
      'Seaking',
      'Marill',
      'Smeargle',
      'Ralts',
      'Kirlia',
      'Budew',
      'Starly',
      'Staravia',
      'Ekans',
      'Tentacool',
      'Tentacruel',
      'Grimer',
      'Magikarp',
      'Gyarados',
      'Wooper',
      'Quagsire',
      'Remoraid',
      'Octillery',
      'Lotad',
      'Lombre',
      'Roselia',
      'Barboach',
      'Whiscash',
      'Bibarel',
      'Kricketune',
      'Buizel',
      'Shellos',
      'Gastrodon',
      'Croagunk',
    ],
    id: 38,
    pokemon: null,
    location: 'Route 212',
    status: null,
  },
  {
    filter: [
      'Geodude',
      'Ponyta',
      'Chansey',
      'Scyther',
      'Tauros',
      'Hoothoot',
      'Noctowl',
      'Pineco',
      'Miltank',
      'Seedot',
      'Nuzleaf',
      'Roselia',
      'Staravia',
      'Kricketune',
      'Bonsly',
      'Mime-jr',
    ],
    id: 39,
    pokemon: null,
    location: 'Route 210',
    status: null,
  },
  {
    filter: [
      'Psyduck',
      'Golduck',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Gyarados',
      'Barboach',
      'Whiscash',
      'Corphish',
      'Crawdaunt',
    ],
    id: 40,
    pokemon: null,
    location: 'Celestic Town',
    status: null,
  },
  {
    filter: [
      'Psyduck',
      'Golduck',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Gyarados',
      'Barboach',
      'Whiscash',
      'Corphish',
      'Crawdaunt',
    ],
    id: 41,
    pokemon: null,
    location: 'Fuego Ironworks',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Tentacruel',
      'Magikarp',
      'Gyarados',
      'Wingull',
      'Pelipper',
      'Clamperl',
      'Finneon',
      'Lumineon',
    ],
    id: 42,
    pokemon: null,
    location: 'Route 219',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Tentacruel',
      'Magikarp',
      'Gyarados',
      'Chinchou',
      'Lanturn',
      'Wingull',
      'Pelipper',
      'Finneon',
      'Lumineon',
    ],
    id: 43,
    pokemon: null,
    location: 'Route 220',
    status: null,
  },
  {
    filter: [
      'Nidorina',
      'Nidorino',
      'Tentacool',
      'Tentacruel',
      'Farfetchd',
      'Magikarp',
      'Gyarados',
      'Sudowoodo',
      'Girafarig',
      'Wingull',
      'Pelipper',
      'Roselia',
      'Clamperl',
      'Floatzel',
      'Shellos',
      'Gastrodon',
      'Stunky',
      'Skuntank',
      'Finneon',
      'Lumineon',
    ],
    id: 44,
    pokemon: null,
    location: 'Route 221',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Tentacruel',
      'Voltorb',
      'Mr. Mime',
      'Magikarp',
      'Gyarados',
      'Ditto',
      'Wingull',
      'Pelipper',
      'Floatzel',
      'Shellos',
      'Gastrodon',
      'Glameow',
      'Chatot',
      'Finneon',
      'Lumineon',
    ],
    id: 45,
    pokemon: null,
    location: 'Route 218',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Tentacruel',
      'Staryu',
      'Magikarp',
      'Gyarados',
      'Wingull',
      'Pelipper',
      'Shellos',
      'Gastrodon',
      'Finneon',
      'Lumineon',
    ],
    id: 46,
    pokemon: null,
    location: 'Canalave City',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Tentacruel',
      'Magikarp',
      'Gyarados',
      'Qwilfish',
      'Wingull',
      'Pelipper',
      'Finneon',
      'Lumineon',
      'Geodude',
      'Graveler',
      'Onix',
      'Sableye',
      'Mawile',
      'Steelix',
      'Riolu',
    ],
    id: 47,
    pokemon: null,
    location: 'Iron Island',
    status: null,
  },
  {
    filter: [
      'Psyduck',
      'Golduck',
      'Lickitung',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Gyarados',
      'Noctowl',
      'Wobbuffet',
      'Lunatone',
      'Solrock',
      'Staravia',
      'Bibarel',
      'Chingling',
    ],
    id: 48,
    pokemon: null,
    location: 'Lake Valor',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Machop',
      'Geodude',
      'Ponyta',
      'Hoothoot',
      'Teddiursa',
      'Tyrogue',
      'Meditite',
      'Bidoof',
      'Chingling',
      'Bronzor',
      'Machoke',
      'Graveler',
      'Noctowl',
      'Swablu',
    ],
    id: 49,
    pokemon: null,
    location: 'Route 211',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Machoke',
      'Graveler',
      'Noctowl',
      'Sneasel',
      'Ursaring',
      'Delibird',
      'Meditite',
      'Snorunt',
      'Snover',
    ],
    id: 50,
    pokemon: null,
    location: 'Route 216',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Machoke',
      'Noctowl',
      'Sneasel',
      'Ursaring',
      'Swinub',
      'Piloswine',
      'Delibird',
      'Meditite',
      'Medicham',
      'Snorunt',
      'Snover',
    ],
    id: 51,
    pokemon: null,
    location: 'Route 217',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Machoke',
      'Noctowl',
      'Sneasel',
      'Ursaring',
      'Swinub',
      'Piloswine',
      'Delibird',
      'Meditite',
      'Medicham',
      'Snorunt',
      'Snover',
    ],
    id: 52,
    pokemon: null,
    location: 'Acuity Lakefront',
    status: null,
  },
  {
    filter: [
      'Psyduck',
      'Golduck',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Gyarados',
      'Noctowl',
      'Wobbuffet',
      'Sneasel',
      'Teddiursa',
      'Ursaring',
      'Smoochum',
      'Lunatone',
      'Solrock',
      'Snorunt',
      'Bibarel',
      'Chingling',
      'Snover',
    ],
    id: 53,
    pokemon: null,
    location: 'Lake Acuity',
    status: null,
  },
  {
    filter: ['Haunter'],
    id: 54,
    pokemon: null,
    location: 'Snowpoint City',
    status: null,
  },
  {
    filter: ['Giratina'],
    id: 55,
    pokemon: null,
    location: 'Distortion World',
    status: null,
  },
  {
    filter: [
      'Psyduck',
      'Golduck',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Gyarados',
      'Noctowl',
      'Wobbuffet',
      'Sneasel',
      'Teddiursa',
      'Ursaring',
      'Smoochum',
      'Lunatone',
      'Solrock',
      'Snorunt',
      'Bibarel',
      'Chingling',
      'Snover',
    ],
    id: 56,
    pokemon: null,
    location: 'Sendoff Spring',
    status: null,
  },
  {
    filter: [
      'Golbat',
      'Golduck',
      'Graveler',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Gyarados',
      'Noctowl',
      'Lunatone',
      'Solrock',
      'Dusclops',
      'Chimecho',
      'Staravia',
      'Bibarel',
      'Chingling',
    ],
    id: 57,
    pokemon: null,
    location: 'Route 222',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Tentacruel',
      'Magnemite',
      'Magneton',
      'Mr. Mime',
      'Electabuzz',
      'Magikarp',
      'Gyarados',
      'Flaaffy',
      'Remoraid',
      'Octillery',
      'Wingull',
      'Pelipper',
      'Skitty',
      'Sharpedo',
      'Luxio',
      'Floatzel',
      'Gastrodon',
      'Glameow',
      'Purugly',
      'Chatot',
    ],
    id: 58,
    pokemon: null,
    location: 'Sunyshore City',
    status: null,
  },
  {
    filter: [
      'Tentacruel',
      'Magikarp',
      'Gyarados',
      'Remoraid',
      'Octillery',
      'Pelipper',
      'Wailmer',
      'Wailord',
      'Mantyke',
    ],
    id: 59,
    pokemon: null,
    location: 'Route 223',
    status: null,
  },
  {
    filter: [
      'Tentacruel',
      'Magikarp',
      'Gyarados',
      'Remoraid',
      'Octillery',
      'Wingull',
      'Pelipper',
      'Luvdisc',
    ],
    id: 60,
    pokemon: null,
    location: 'Pokemon League',
    status: null,
  },
  {
    filter: [
      'Golbat',
      'Machoke',
      'Graveler',
      'Onix',
      'Rhyhorn',
      'Rhydon',
      'Steelix',
      'Medicham',
      'Gabite',
      'Kadabra',
      'Magneton',
      'Azumarill',
      'Floatzel',
      'Magikarp',
      'Gyarados',
    ],
    id: 61,
    pokemon: null,
    location: 'Victory Road',
    status: null,
  },
];

export default SINNOH;
