import { TEncounter } from 'constants/types';

const SINNOH: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    id: 1,
    pokemon: null,
    location: 'Twinleaf Town',
    status: null,
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 201',
    status: null,
  },
  {
    id: 3,
    pokemon: null,
    location: 'Lake Verity',
    status: null,
  },
  {
    id: 4,
    pokemon: null,
    location: 'Sandgem Town',
    status: null,
  },
  {
    id: 5,
    pokemon: null,
    location: 'Route 202',
    status: null,
  },
  {
    id: 6,
    pokemon: null,
    location: 'Jubilife City',
    status: null,
  },
  {
    id: 7,
    pokemon: null,
    location: 'Route 203',
    status: null,
  },
  {
    id: 8,
    pokemon: null,
    location: 'Oreburgh Gate',
    status: null,
  },
  {
    id: 9,
    pokemon: null,
    location: 'Oreburgh City',
    status: null,
  },
  {
    id: 10,
    pokemon: null,
    location: 'Oreburgh Mine',
    status: null,
  },
  {
    id: 11,
    pokemon: null,
    location: 'Route 204',
    status: null,
  },
  {
    id: 12,
    pokemon: null,
    location: 'Ravaged Path',
    status: null,
  },
  {
    id: 13,
    pokemon: null,
    location: 'Floaroma Town',
    status: null,
  },
  {
    id: 14,
    pokemon: null,
    location: 'Floaroma Meadow',
    status: null,
  },
  {
    id: 15,
    pokemon: null,
    location: 'Valley Windworks',
    status: null,
  },
  {
    id: 16,
    pokemon: null,
    location: 'Route 205',
    status: null,
  },
  {
    id: 17,
    pokemon: null,
    location: 'Eterna Forest',
    status: null,
  },
  {
    id: 18,
    pokemon: null,
    location: 'Eterna City',
    status: null,
  },
  {
    id: 19,
    pokemon: null,
    location: 'Old Chateau',
    status: null,
  },
  {
    id: 20,
    pokemon: null,
    location: 'Route 206',
    status: null,
  },
  {
    id: 21,
    pokemon: null,
    location: 'Wayward Cave',
    status: null,
  },
  {
    id: 22,
    pokemon: null,
    location: 'Route 207',
    status: null,
  },
  {
    id: 23,
    pokemon: null,
    location: 'Mt. Coronet',
    status: null,
  },
  {
    id: 24,
    pokemon: null,
    location: 'Route 208',
    status: null,
  },
  {
    id: 26,
    pokemon: null,
    location: 'Hearthome City',
    status: null,
  },
  {
    id: 27,
    pokemon: null,
    location: 'Route 209',
    status: null,
  },
  {
    id: 28,
    pokemon: null,
    location: 'Solaceon Town',
    status: null,
  },
  {
    id: 29,
    pokemon: null,
    location: 'Solaceon Ruins',
    status: null,
  },
  {
    id: 30,
    pokemon: null,
    location: 'Lost Tower',
    status: null,
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 215',
    status: null,
  },
  {
    id: 32,
    pokemon: null,
    location: 'Veilstone City',
    status: null,
  },
  {
    id: 33,
    pokemon: null,
    location: 'Route 214',
    status: null,
  },
  {
    id: 34,
    pokemon: null,
    location: 'Maniac Tunnel',
    status: null,
  },
  {
    id: 35,
    pokemon: null,
    location: 'Valor Lakefront',
    status: null,
  },
  {
    id: 36,
    pokemon: null,
    location: 'Route 213',
    status: null,
  },
  {
    id: 37,
    pokemon: null,
    location: 'Pastoria City',
    status: null,
  },
  {
    id: 62,
    pokemon: null,
    location: 'The Great Marsh',
    status: null,
  },
  {
    id: 38,
    pokemon: null,
    location: 'Route 212',
    status: null,
  },
  {
    id: 39,
    pokemon: null,
    location: 'Route 210',
    status: null,
  },
  {
    id: 40,
    pokemon: null,
    location: 'Celestic Town',
    status: null,
  },
  {
    id: 41,
    pokemon: null,
    location: 'Fuego Ironworks',
    status: null,
  },
  {
    id: 42,
    pokemon: null,
    location: 'Route 219',
    status: null,
  },
  {
    id: 43,
    pokemon: null,
    location: 'Route 220',
    status: null,
  },
  {
    id: 44,
    pokemon: null,
    location: 'Route 221',
    status: null,
  },
  {
    id: 45,
    pokemon: null,
    location: 'Route 218',
    status: null,
  },
  {
    id: 46,
    pokemon: null,
    location: 'Canalave City',
    status: null,
  },
  {
    id: 47,
    pokemon: null,
    location: 'Iron Island',
    status: null,
  },
  {
    id: 48,
    pokemon: null,
    location: 'Lake Valor',
    status: null,
  },
  {
    id: 49,
    pokemon: null,
    location: 'Route 211',
    status: null,
  },
  {
    id: 50,
    pokemon: null,
    location: 'Route 216',
    status: null,
  },
  {
    id: 51,
    pokemon: null,
    location: 'Route 217',
    status: null,
  },
  {
    id: 52,
    pokemon: null,
    location: 'Acuity Lakefront',
    status: null,
  },
  {
    id: 53,
    pokemon: null,
    location: 'Lake Acuity',
    status: null,
  },
  {
    id: 54,
    pokemon: null,
    location: 'Snowpoint City',
    status: null,
  },
  {
    id: 55,
    pokemon: null,
    location: 'Distortion World',
    status: null,
  },
  {
    id: 56,
    pokemon: null,
    location: 'Sendoff Spring',
    status: null,
  },
  {
    id: 57,
    pokemon: null,
    location: 'Route 222',
    status: null,
  },
  {
    id: 58,
    pokemon: null,
    location: 'Sunyshore City',
    status: null,
  },
  {
    id: 59,
    pokemon: null,
    location: 'Route 223',
    status: null,
  },
  {
    id: 60,
    pokemon: null,
    location: 'Pokemon League',
    status: null,
  },
  {
    id: 61,
    pokemon: null,
    location: 'Victory Road',
    status: null,
  },
];

export default SINNOH;
