import { TEncounter } from 'constants/types';

const SINNOH: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
    filterKey: 'dpp-0',
  },
  {
    id: 1,
    pokemon: null,
    location: 'Twinleaf Town',
    status: null,
    filterKey: 'dpp-1',
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 201',
    status: null,
    filterKey: 'dpp-2',
  },
  {
    id: 3,
    pokemon: null,
    location: 'Lake Verity',
    status: null,
    filterKey: 'dpp-3',
  },
  {
    id: 5,
    pokemon: null,
    location: 'Route 202',
    status: null,
    filterKey: 'dpp-5',
  },
  {
    id: 7,
    pokemon: null,
    location: 'Route 203',
    status: null,
    filterKey: 'dpp-7',
  },
  {
    id: 8,
    pokemon: null,
    location: 'Oreburgh Gate',
    status: null,
    filterKey: 'dpp-8',
  },
  {
    id: 9,
    pokemon: null,
    location: 'Oreburgh City',
    status: null,
    filterKey: 'dpp-9',
  },
  {
    id: 10,
    pokemon: null,
    location: 'Oreburgh Mine',
    status: null,
    filterKey: 'dpp-10',
  },
  {
    id: 11,
    pokemon: null,
    location: 'Route 204',
    status: null,
    filterKey: 'dpp-11',
  },
  {
    id: 12,
    pokemon: null,
    location: 'Ravaged Path',
    status: null,
    filterKey: 'dpp-12',
  },
  {
    id: 14,
    pokemon: null,
    location: 'Floaroma Meadow',
    status: null,
    filterKey: 'dpp-14',
  },
  {
    id: 15,
    pokemon: null,
    location: 'Valley Windworks',
    status: null,
    filterKey: 'dpp-15',
  },
  {
    id: 16,
    pokemon: null,
    location: 'Route 205',
    status: null,
    filterKey: 'dpp-16',
  },
  {
    id: 17,
    pokemon: null,
    location: 'Eterna Forest',
    status: null,
    filterKey: 'dpp-17',
  },
  {
    id: 18,
    pokemon: null,
    location: 'Eterna City',
    status: null,
    filterKey: 'dpp-18',
  },
  {
    id: 19,
    pokemon: null,
    location: 'Old Chateau',
    status: null,
    filterKey: 'dpp-19',
  },
  {
    id: 20,
    pokemon: null,
    location: 'Route 206',
    status: null,
    filterKey: 'dpp-20',
  },
  {
    id: 21,
    pokemon: null,
    location: 'Wayward Cave',
    status: null,
    filterKey: 'dpp-21',
  },
  {
    id: 22,
    pokemon: null,
    location: 'Route 207',
    status: null,
    filterKey: 'dpp-22',
  },
  {
    id: 23,
    pokemon: null,
    location: 'Mt. Coronet',
    status: null,
    filterKey: 'dpp-23',
  },
  {
    id: 24,
    pokemon: null,
    location: 'Route 208',
    status: null,
    filterKey: 'dpp-24',
  },
  {
    id: 26,
    pokemon: null,
    location: 'Hearthome City',
    status: null,
    filterKey: 'dpp-26',
  },
  {
    id: 27,
    pokemon: null,
    location: 'Route 209',
    status: null,
    filterKey: 'dpp-27',
  },
  {
    id: 29,
    pokemon: null,
    location: 'Solaceon Ruins',
    status: null,
    filterKey: 'dpp-29',
  },
  {
    id: 30,
    pokemon: null,
    location: 'Lost Tower',
    status: null,
    filterKey: 'dpp-30',
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 215',
    status: null,
    filterKey: 'dpp-31',
  },
  {
    id: 32,
    pokemon: null,
    location: 'Veilstone City',
    status: null,
    filterKey: 'dpp-32',
  },
  {
    id: 33,
    pokemon: null,
    location: 'Route 214',
    status: null,
    filterKey: 'dpp-33',
  },
  {
    id: 34,
    pokemon: null,
    location: 'Maniac Tunnel',
    status: null,
    filterKey: 'dpp-34',
  },
  {
    id: 35,
    pokemon: null,
    location: 'Valor Lakefront',
    status: null,
    filterKey: 'dpp-35',
  },
  {
    id: 36,
    pokemon: null,
    location: 'Route 213',
    status: null,
    filterKey: 'dpp-36',
  },
  {
    id: 37,
    pokemon: null,
    location: 'Pastoria City',
    status: null,
    filterKey: 'dpp-37',
  },
  {
    id: 62,
    pokemon: null,
    location: 'The Great Marsh',
    status: null,
    filterKey: 'dpp-62',
  },
  {
    id: 38,
    pokemon: null,
    location: 'Route 212',
    status: null,
    filterKey: 'dpp-38',
  },
  {
    id: 39,
    pokemon: null,
    location: 'Route 210',
    status: null,
    filterKey: 'dpp-39',
  },
  {
    id: 40,
    pokemon: null,
    location: 'Celestic Town',
    status: null,
    filterKey: 'dpp-40',
  },
  {
    id: 41,
    pokemon: null,
    location: 'Fuego Ironworks',
    status: null,
    filterKey: 'dpp-41',
  },
  {
    id: 42,
    pokemon: null,
    location: 'Route 219',
    status: null,
    filterKey: 'dpp-42',
  },
  {
    id: 43,
    pokemon: null,
    location: 'Route 220',
    status: null,
    filterKey: 'dpp-43',
  },
  {
    id: 44,
    pokemon: null,
    location: 'Route 221',
    status: null,
    filterKey: 'dpp-44',
  },
  {
    id: 45,
    pokemon: null,
    location: 'Route 218',
    status: null,
    filterKey: 'dpp-45',
  },
  {
    id: 46,
    pokemon: null,
    location: 'Canalave City',
    status: null,
    filterKey: 'dpp-46',
  },
  {
    id: 47,
    pokemon: null,
    location: 'Iron Island',
    status: null,
    filterKey: 'dpp-47',
  },
  {
    id: 48,
    pokemon: null,
    location: 'Lake Valor',
    status: null,
    filterKey: 'dpp-48',
  },
  {
    id: 49,
    pokemon: null,
    location: 'Route 211',
    status: null,
    filterKey: 'dpp-49',
  },
  {
    id: 50,
    pokemon: null,
    location: 'Route 216',
    status: null,
    filterKey: 'dpp-50',
  },
  {
    id: 51,
    pokemon: null,
    location: 'Route 217',
    status: null,
    filterKey: 'dpp-51',
  },
  {
    id: 52,
    pokemon: null,
    location: 'Acuity Lakefront',
    status: null,
    filterKey: 'dpp-52',
  },
  {
    id: 53,
    pokemon: null,
    location: 'Lake Acuity',
    status: null,
    filterKey: 'dpp-53',
  },
  {
    id: 54,
    pokemon: null,
    location: 'Snowpoint City',
    status: null,
    filterKey: 'dpp-54',
  },
  {
    id: 55,
    pokemon: null,
    location: 'Distortion World',
    status: null,
    filterKey: 'dpp-55',
  },
  {
    id: 56,
    pokemon: null,
    location: 'Sendoff Spring',
    status: null,
    filterKey: 'dpp-56',
  },
  {
    id: 57,
    pokemon: null,
    location: 'Route 222',
    status: null,
    filterKey: 'dpp-57',
  },
  {
    id: 58,
    pokemon: null,
    location: 'Sunyshore City',
    status: null,
    filterKey: 'dpp-58',
  },
  {
    id: 59,
    pokemon: null,
    location: 'Route 223',
    status: null,
    filterKey: 'dpp-59',
  },
  {
    id: 60,
    pokemon: null,
    location: 'Pokemon League',
    status: null,
    filterKey: 'dpp-60',
  },
  {
    id: 61,
    pokemon: null,
    location: 'Victory Road',
    status: null,
    filterKey: 'dpp-61',
  },
];

export default SINNOH;
