import type { TEncounter } from 'constants/types';

const FR_LG: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
    filterKey: 'frlg-0',
  },
  {
    id: 1,
    pokemon: null,
    location: 'Pallet Town',
    status: null,
    filterKey: 'frlg-1',
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 1',
    status: null,
    filterKey: 'frlg-2',
  },
  {
    id: 3,
    pokemon: null,
    location: 'Viridian City',
    status: null,
    filterKey: 'frlg-3',
  },
  {
    id: 4,
    pokemon: null,
    location: 'Route 22',
    status: null,
    filterKey: 'frlg-4',
  },
  {
    id: 5,
    pokemon: null,
    location: 'Route 2',
    status: null,
    filterKey: 'frlg-5',
  },
  {
    id: 6,
    pokemon: null,
    location: 'Viridian Forest',
    status: null,
    filterKey: 'frlg-6',
  },
  {
    id: 8,
    pokemon: null,
    location: 'Route 3',
    status: null,
    filterKey: 'frlg-8',
  },
  {
    id: 9,
    pokemon: null,
    location: 'Route 4',
    status: null,
    filterKey: 'frlg-9',
  },
  {
    id: 10,
    pokemon: null,
    location: 'Mt. Moon',
    status: null,
    filterKey: 'frlg-10',
  },
  {
    id: 11,
    pokemon: null,
    location: 'Cerulean City',
    status: null,
    filterKey: 'frlg-11',
  },
  {
    id: 12,
    pokemon: null,
    location: 'Route 24',
    status: null,
    filterKey: 'frlg-12',
  },
  {
    id: 13,
    pokemon: null,
    location: 'Route 25',
    status: null,
    filterKey: 'frlg-13',
  },
  {
    id: 14,
    pokemon: null,
    location: 'Route 5',
    status: null,
    filterKey: 'frlg-14',
  },
  {
    id: 15,
    pokemon: null,
    location: 'Route 6',
    status: null,
    filterKey: 'frlg-15',
  },
  {
    id: 16,
    pokemon: null,
    location: 'Vermillion City',
    status: null,
    filterKey: 'frlg-16',
  },
  {
    id: 17,
    pokemon: null,
    location: 'S.S. Anne',
    status: null,
    filterKey: 'frlg-17',
  },
  {
    id: 18,
    pokemon: null,
    location: 'Route 11',
    status: null,
    filterKey: 'frlg-18',
  },
  {
    id: 19,
    pokemon: null,
    location: "Diglett's Cave",
    status: null,
    filterKey: 'frlg-19',
  },
  {
    id: 20,
    pokemon: null,
    location: 'Route 9',
    status: null,
    filterKey: 'frlg-20',
  },
  {
    id: 21,
    pokemon: null,
    location: 'Route 10',
    status: null,
    filterKey: 'frlg-21',
  },
  {
    id: 22,
    pokemon: null,
    location: 'Rock Tunnel',
    status: null,
    filterKey: 'frlg-22',
  },
  {
    id: 24,
    pokemon: null,
    location: 'Pokemon Tower',
    status: null,
    filterKey: 'frlg-24',
  },
  {
    id: 25,
    pokemon: null,
    location: 'Route 12',
    status: null,
    filterKey: 'frlg-25',
  },
  {
    id: 26,
    pokemon: null,
    location: 'Route 8',
    status: null,
    filterKey: 'frlg-26',
  },
  {
    id: 27,
    pokemon: null,
    location: 'Route 7',
    status: null,
    filterKey: 'frlg-27',
  },
  {
    id: 28,
    pokemon: null,
    location: 'Celadon City',
    status: null,
    filterKey: 'frlg-28',
  },
  {
    id: 29,
    pokemon: null,
    location: 'Saffron City',
    status: null,
    filterKey: 'frlg-29',
  },
  {
    id: 30,
    pokemon: null,
    location: 'Rocket Hideout',
    status: null,
    filterKey: 'frlg-30',
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 16',
    status: null,
    filterKey: 'frlg-31',
  },
  {
    id: 32,
    pokemon: null,
    location: 'Route 17',
    status: null,
    filterKey: 'frlg-32',
  },
  {
    id: 33,
    pokemon: null,
    location: 'Route 18',
    status: null,
    filterKey: 'frlg-33',
  },
  {
    id: 34,
    pokemon: null,
    location: 'Fuschia City',
    status: null,
    filterKey: 'frlg-34',
  },
  {
    id: 35,
    pokemon: null,
    location: 'Safari Zone',
    status: null,
    filterKey: 'frlg-35',
  },
  {
    id: 36,
    pokemon: null,
    location: 'Route 15',
    status: null,
    filterKey: 'frlg-36',
  },
  {
    id: 37,
    pokemon: null,
    location: 'Route 14',
    status: null,
    filterKey: 'frlg-37',
  },
  {
    id: 38,
    pokemon: null,
    location: 'Route 13',
    status: null,
    filterKey: 'frlg-38',
  },
  {
    id: 39,
    pokemon: null,
    location: 'Power Plant',
    status: null,
    filterKey: 'frlg-39',
  },
  {
    id: 40,
    pokemon: null,
    location: 'Route 19',
    status: null,
    filterKey: 'frlg-40',
  },
  {
    id: 41,
    pokemon: null,
    location: 'Route 20',
    status: null,
    filterKey: 'frlg-41',
  },
  {
    id: 42,
    pokemon: null,
    location: 'Seafoam Islands',
    status: null,
    filterKey: 'frlg-42',
  },
  {
    id: 43,
    pokemon: null,
    location: 'Cinnabar Island',
    status: null,
    filterKey: 'frlg-43',
  },
  {
    id: 44,
    pokemon: null,
    location: 'Pokemon Mansion',
    status: null,
    filterKey: 'frlg-44',
  },
  {
    id: 45,
    pokemon: null,
    location: 'Route 21',
    status: null,
    filterKey: 'frlg-45',
  },
  {
    id: 46,
    pokemon: null,
    location: 'One Island',
    status: null,
    filterKey: 'frlg-46',
  },
  {
    id: 47,
    pokemon: null,
    location: 'Treasure Beach',
    status: null,
    filterKey: 'frlg-47',
  },
  {
    id: 48,
    pokemon: null,
    location: 'Kindle Road',
    status: null,
    filterKey: 'frlg-48',
  },
  {
    id: 49,
    pokemon: null,
    location: 'Mt. Ember',
    status: null,
    filterKey: 'frlg-49',
  },
  {
    id: 50,
    pokemon: null,
    location: 'Cape Brink',
    status: null,
    filterKey: 'frlg-50',
  },
  {
    id: 51,
    pokemon: null,
    location: 'Three Isle Port',
    status: null,
    filterKey: 'frlg-51',
  },
  {
    id: 53,
    pokemon: null,
    location: 'Bond Bridge',
    status: null,
    filterKey: 'frlg-53',
  },
  {
    id: 54,
    pokemon: null,
    location: 'Berry Forest',
    status: null,
    filterKey: 'frlg-54',
  },
  {
    id: 55,
    pokemon: null,
    location: 'Route 23',
    status: null,
    filterKey: 'frlg-55',
  },
  {
    id: 56,
    pokemon: null,
    location: 'Victory Road',
    status: null,
    filterKey: 'frlg-56',
  },
  {
    id: 57,
    pokemon: null,
    location: 'Four Island',
    status: null,
    filterKey: 'frlg-57',
  },
  {
    id: 58,
    pokemon: null,
    location: 'Icefall Cave',
    status: null,
    filterKey: 'frlg-58',
  },
  {
    id: 59,
    pokemon: null,
    location: 'Five Isle Meadow',
    status: null,
    filterKey: 'frlg-59',
  },
  {
    id: 60,
    pokemon: null,
    location: 'Memorial Pillar',
    status: null,
    filterKey: 'frlg-60',
  },
  {
    id: 61,
    pokemon: null,
    location: 'Water Labyrinth',
    status: null,
    filterKey: 'frlg-61',
  },
  {
    id: 62,
    pokemon: null,
    location: 'Resort Gorgeous',
    status: null,
    filterKey: 'frlg-62',
  },
  {
    id: 63,
    pokemon: null,
    location: 'Lost Cave',
    status: null,
    filterKey: 'frlg-63',
  },
  {
    id: 64,
    pokemon: null,
    location: 'Water Path',
    status: null,
    filterKey: 'frlg-64',
  },
  {
    id: 65,
    pokemon: null,
    location: 'Green Path',
    status: null,
    filterKey: 'frlg-65',
  },
  {
    id: 66,
    pokemon: null,
    location: 'Pattern Bush',
    status: null,
    filterKey: 'frlg-66',
  },
  {
    id: 67,
    pokemon: null,
    location: 'Outcast Island',
    status: null,
    filterKey: 'frlg-67',
  },
  {
    id: 68,
    pokemon: null,
    location: 'Altering Cave',
    status: null,
    filterKey: 'frlg-68',
  },
  {
    id: 69,
    pokemon: null,
    location: 'Ruin Valley',
    status: null,
    filterKey: 'frlg-69',
  },
  {
    id: 70,
    pokemon: null,
    location: 'Trainer Tower',
    status: null,
    filterKey: 'frlg-70',
  },
  {
    id: 71,
    pokemon: null,
    location: 'Canyon Entrance',
    status: null,
    filterKey: 'frlg-71',
  },
  {
    id: 72,
    pokemon: null,
    location: 'Sevault Canyon',
    status: null,
    filterKey: 'frlg-72',
  },
  {
    id: 73,
    pokemon: null,
    location: 'Tanoby Ruins',
    status: null,
    filterKey: 'frlg-73',
  },
  {
    id: 74,
    pokemon: null,
    location: 'Cerulean Cave',
    status: null,
    filterKey: 'frlg-74',
  },
];

export default FR_LG;
