import { TEncounter } from 'constants/types';

const FR_LG: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    id: 1,
    pokemon: null,
    location: 'Pallet Town',
    status: null,
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 1',
    status: null,
  },
  {
    id: 3,
    pokemon: null,
    location: 'Viridian City',
    status: null,
  },
  {
    id: 4,
    pokemon: null,
    location: 'Route 22',
    status: null,
  },
  {
    id: 5,
    pokemon: null,
    location: 'Route 2',
    status: null,
  },
  {
    id: 6,
    pokemon: null,
    location: 'Viridian Forest',
    status: null,
  },
  {
    id: 7,
    pokemon: null,
    location: 'Pewter City',
    status: null,
  },
  {
    id: 8,
    pokemon: null,
    location: 'Route 3',
    status: null,
  },
  {
    id: 9,
    pokemon: null,
    location: 'Route 4',
    status: null,
  },
  {
    id: 10,
    pokemon: null,
    location: 'Mt. Moon',
    status: null,
  },
  {
    id: 11,
    pokemon: null,
    location: 'Cerulean City',
    status: null,
  },
  {
    id: 12,
    pokemon: null,
    location: 'Route 24',
    status: null,
  },
  {
    id: 13,
    pokemon: null,
    location: 'Route 25',
    status: null,
  },
  {
    id: 14,
    pokemon: null,
    location: 'Route 5',
    status: null,
  },
  {
    id: 15,
    pokemon: null,
    location: 'Route 6',
    status: null,
  },
  {
    id: 16,
    pokemon: null,
    location: 'Vermillion City',
    status: null,
  },
  {
    id: 17,
    pokemon: null,
    location: 'S.S. Anne',
    status: null,
  },
  {
    id: 18,
    pokemon: null,
    location: 'Route 11',
    status: null,
  },
  {
    id: 19,
    pokemon: null,
    location: "Diglett's Cave",
    status: null,
  },
  {
    id: 20,
    pokemon: null,
    location: 'Route 9',
    status: null,
  },
  {
    id: 21,
    pokemon: null,
    location: 'Route 10',
    status: null,
  },
  {
    id: 22,
    pokemon: null,
    location: 'Rock Tunnel',
    status: null,
  },
  {
    id: 23,
    pokemon: null,
    location: 'Lavendar Town',
    status: null,
  },
  {
    id: 24,
    pokemon: null,
    location: 'Pokemon Tower',
    status: null,
  },
  {
    id: 25,
    pokemon: null,
    location: 'Route 12',
    status: null,
  },
  {
    id: 26,
    pokemon: null,
    location: 'Route 8',
    status: null,
  },
  {
    id: 27,
    pokemon: null,
    location: 'Route 7',
    status: null,
  },
  {
    id: 28,
    pokemon: null,
    location: 'Celadon City',
    status: null,
  },
  {
    id: 29,
    pokemon: null,
    location: 'Saffron City',
    status: null,
  },
  {
    id: 30,
    pokemon: null,
    location: 'Rocket Hideout',
    status: null,
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 16',
    status: null,
  },
  {
    id: 32,
    pokemon: null,
    location: 'Route 17',
    status: null,
  },
  {
    id: 33,
    pokemon: null,
    location: 'Route 18',
    status: null,
  },
  {
    id: 34,
    pokemon: null,
    location: 'Fuschia City',
    status: null,
  },
  {
    id: 35,
    pokemon: null,
    location: 'Safari Zone',
    status: null,
  },
  {
    id: 36,
    pokemon: null,
    location: 'Route 15',
    status: null,
  },
  {
    id: 37,
    pokemon: null,
    location: 'Route 14',
    status: null,
  },
  {
    id: 38,
    pokemon: null,
    location: 'Route 13',
    status: null,
  },
  {
    id: 39,
    pokemon: null,
    location: 'Power Plant',
    status: null,
  },
  {
    id: 40,
    pokemon: null,
    location: 'Route 19',
    status: null,
  },
  {
    id: 41,
    pokemon: null,
    location: 'Route 20',
    status: null,
  },
  {
    id: 42,
    pokemon: null,
    location: 'Seafoam Islands',
    status: null,
  },
  {
    id: 43,
    pokemon: null,
    location: 'Cinnabar Island',
    status: null,
  },
  {
    id: 44,
    pokemon: null,
    location: 'Pokemon Mansion',
    status: null,
  },
  {
    id: 45,
    pokemon: null,
    location: 'Route 21',
    status: null,
  },
  {
    id: 46,
    pokemon: null,
    location: 'One Island',
    status: null,
  },
  {
    id: 47,
    pokemon: null,
    location: 'Treasure Beach',
    status: null,
  },
  {
    id: 48,
    pokemon: null,
    location: 'Kindle Road',
    status: null,
  },
  {
    id: 49,
    pokemon: null,
    location: 'Mt. Ember',
    status: null,
  },
  {
    id: 50,
    pokemon: null,
    location: 'Cape Brink',
    status: null,
  },
  {
    id: 51,
    pokemon: null,
    location: 'Three Isle Port',
    status: null,
  },
  {
    id: 53,
    pokemon: null,
    location: 'Bond Bridge',
    status: null,
  },
  {
    id: 54,
    pokemon: null,
    location: 'Berry Forest',
    status: null,
  },
  {
    id: 55,
    pokemon: null,
    location: 'Route 23',
    status: null,
  },
  {
    id: 56,
    pokemon: null,
    location: 'Victory Road',
    status: null,
  },
  {
    id: 57,
    pokemon: null,
    location: 'Four Island',
    status: null,
  },
  {
    id: 58,
    pokemon: null,
    location: 'Icefall Cave',
    status: null,
  },
  {
    id: 59,
    pokemon: null,
    location: 'Five Island',
    status: null,
  },
  {
    id: 60,
    pokemon: null,
    location: 'Five Isle Meadow',
    status: null,
  },
  {
    id: 61,
    pokemon: null,
    location: 'Memorial Pillar ',
    status: null,
  },
  {
    id: 62,
    pokemon: null,
    location: 'Water Labyrinth',
    status: null,
  },
  {
    id: 63,
    pokemon: null,
    location: 'Resort Gorgeous',
    status: null,
  },
  {
    id: 64,
    pokemon: null,
    location: 'Lost Cave',
    status: null,
  },
  {
    id: 65,
    pokemon: null,
    location: 'Water Path',
    status: null,
  },
  {
    id: 66,
    pokemon: null,
    location: 'Green Path',
    status: null,
  },
  {
    id: 67,
    pokemon: null,
    location: 'Pattern Bush',
    status: null,
  },
  {
    id: 68,
    pokemon: null,
    location: 'Outcast Island',
    status: null,
  },
  {
    id: 69,
    pokemon: null,
    location: 'Altering Cave',
    status: null,
  },
  {
    id: 70,
    pokemon: null,
    location: 'Ruin Valley',
    status: null,
  },
  {
    id: 71,
    pokemon: null,
    location: 'Trainer Tower',
    status: null,
  },
  {
    id: 72,
    pokemon: null,
    location: 'Canyon Entrance',
    status: null,
  },
  {
    id: 73,
    pokemon: null,
    location: 'Seavault Canyon',
    status: null,
  },
  {
    id: 74,
    pokemon: null,
    location: 'Tanoby Ruins',
    status: null,
  },
  {
    id: 75,
    pokemon: null,
    location: 'Cerulean Cave',
    status: null,
  },
];

export default FR_LG;
