import { TEncounter } from 'constants/types';

const G_S_C: TEncounter[] = [
  {
    filter: ['Cyndaquil', 'Chikorita', 'Totodile'],
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Tentacruel',
      'Shellder',
      'Magikarp',
      'Chikorita',
      'Cyndaquil',
      'Totodile',
      'Chinchou',
      'Lanturn',
    ],
    id: 1,
    pokemon: null,
    location: 'New Bark Town',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Rattata',
      'Spearow',
      'Exeggcute',
      'Sentret',
      'Hoothoot',
      'Ledyba',
      'Spinarak',
      'Hoppip',
      'Aipom',
      'Pineco',
      'Heracross',
      'Plusle',
      'Minun',
      'Shinx',
    ],
    id: 2,
    pokemon: null,
    location: 'Route 29',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Krabby', 'Kingler', 'Staryu', 'Magikarp', 'Corsola'],
    id: 3,
    pokemon: null,
    location: 'Cherrygrove City',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Weedle',
      'Kakuna',
      'Pidgey',
      'Rattata',
      'Spearow',
      'Zubat',
      'Poliwag',
      'Poliwhirl',
      'Exeggcute',
      'Magikarp',
      'Hoothoot',
      'Ledyba',
      'Spinarak',
      'Hoppip',
      'Aipom',
      'Pineco',
      'Heracross',
      'Linoone',
      'Whismur',
      'Bidoof',
      'Buizel',
    ],
    id: 4,
    pokemon: null,
    location: 'Route 30',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Weedle',
      'Kakuna',
      'Pidgey',
      'Rattata',
      'Spearow',
      'Zubat',
      'Poliwag',
      'Poliwhirl',
      'Bellsprout',
      'Gastly',
      'Exeggcute',
      'Magikarp',
      'Hoothoot',
      'Ledyba',
      'Spinarak',
      'Hoppip',
      'Aipom',
      'Pineco',
      'Heracross',
      'Linoone',
      'Whismur',
      'Bidoof',
      'Buizel',
    ],
    id: 5,
    pokemon: null,
    location: 'Route 31',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Geodude',
      'Krabby',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Dunsparce',
      'Shuckle',
      'Teddiursa',
      'Makuhita',
      'Absol',
      'Chingling',
      'Bronzor',
      'Graveler',
      'Wobbuffet',
    ],
    id: 6,
    pokemon: null,
    location: 'Dark Cave',
    status: null,
  },
  {
    filter: ['Poliwag', 'Poliwhirl', 'Magikarp', 'Togepi', 'Whiscash'],
    id: 7,
    pokemon: null,
    location: 'Violet City',
    status: null,
  },
  {
    filter: ['Rattata', 'Gastly', 'Zigzagoon', 'Meditite', 'Spinda', 'Chatot'],
    id: 8,
    pokemon: null,
    location: 'Sprout Tower',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Rattata',
      'Spearow',
      'Ekans',
      'Zubat',
      'Bellsprout',
      'Tentacool',
      'Tentacruel',
      'Gastly',
      'Exeggcute',
      'Magikarp',
      'Hoothoot',
      'Mareep',
      'Hoppip',
      'Aipom',
      'Wooper',
      'Quagsire',
      'Pineco',
      'Qwilfish',
      'Heracross',
      'Linoone',
      'Whismur',
      'Bidoof',
      'Buizel',
    ],
    id: 9,
    pokemon: null,
    location: 'Route 32',
    status: null,
  },
  {
    filter: [
      'Poliwag',
      'Geodude',
      'Magikarp',
      'Natu',
      'Wooper',
      'Quagsire',
      'Smeargle',
      'Linoone',
      'Whismur',
      'Bidoof',
      'Buizel, Unown',
    ],
    id: 10,
    pokemon: null,
    location: 'Ruins of Alph',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Sandshrew',
      'Zubat',
      'Geodude',
      'Onix',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Wooper',
      'Quagsire',
      'Makuhita',
      'Absol',
      'Chingling',
      'Bronzor',
    ],
    id: 11,
    pokemon: null,
    location: 'Union Cave',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Spearow',
      'Ekans',
      'Zubat',
      'Geodude',
      'Hoppip',
      'Aipom',
      'Heracross',
      'Plusle',
      'Minun',
      'Shinx',
    ],
    id: 12,
    pokemon: null,
    location: 'Route 33',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Spearow',
      'Ekans',
      'Exeggcute',
      'Aipom',
      'Pineco',
      'Heracross',
    ],
    id: 13,
    pokemon: null,
    location: 'Azalea Town',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Golbat',
      'Slowpoke',
      'Slowbro',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Makuhita',
      'Absol',
      'Chingling',
      'Bronzor',
    ],
    id: 14,
    pokemon: null,
    location: 'Slowpoke Well',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgey',
      'Zubat',
      'Oddish',
      'Paras',
      'Venonat',
      'Psyduck',
      'Golduck',
      'Poliwag',
      'Exeggcute',
      'Magikarp',
      'Hoothoot',
      'Noctowl',
      'Pineco',
      'Numel',
      'Spoink',
      'Budew',
      'Carnivine',
    ],
    id: 15,
    pokemon: null,
    location: 'Ilex Forest',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgey',
      'Rattata',
      'Jigglypuff',
      'Abra',
      'Tentacool',
      'Tentacruel',
      'Drowzee',
      'Krabby',
      'Kingler',
      'Exeggcute',
      'Staryu',
      'Magikarp',
      'Ditto',
      'Hoothoot',
      'Ledyba',
      'Spinarak',
      'Pichu',
      'Cleffa',
      'Igglybuff',
      'Pineco',
      'Snubbull',
      'Corsola',
      'Tyrogue',
      'Smoochum',
      'Elekid',
      'Magby',
      'Linoone',
      'Ralts',
      'Whismur',
      'Bidoof',
      'Buizel',
    ],
    id: 16,
    pokemon: null,
    location: 'Route 34',
    status: null,
  },
  {
    id: 17,
    pokemon: null,
    location: 'Goldenrod City',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgey',
      'Nidoran-f',
      'Nidoran-m',
      'Jigglypuff',
      'Meowth',
      'Psyduck',
      'Golduck',
      'Growlithe',
      'Poliwag',
      'Abra',
      'Drowzee',
      'Exeggcute',
      'Magikarp',
      'Ditto',
      'Hoothoot',
      'Ledyba',
      'Spinarak',
      'Yanma',
      'Pineco',
      'Snubbull',
      'Linoone',
      'Whismur',
      'Bidoof',
      'Buizel',
    ],
    id: 18,
    pokemon: null,
    location: 'Route 35',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Weedle',
      'Kakuna',
      'Pidgey',
      'Nidoran-f',
      'Nidoran-m',
      'Venonat',
      'Psyduck',
      'Hoothoot',
      'Ledyba',
      'Spinarak',
      'Sunkern',
      'Plusle',
      'Minun',
      'Shinx',
    ],
    id: 19,
    pokemon: null,
    location: 'National Park',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgey',
      'Nidoran-f',
      'Nidoran-m',
      'Vulpix',
      'Growlithe',
      'Bellsprout',
      'Gastly',
      'Exeggcute',
      'Hoothoot',
      'Ledyba',
      'Spinarak',
      'Sudowoodo',
      'Pineco',
      'Stantler',
      'Plusle',
      'Minun',
      'Shinx',
    ],
    id: 20,
    pokemon: null,
    location: 'Route 36',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgey',
      'Pidgeotto',
      'Vulpix',
      'Growlithe',
      'Exeggcute',
      'Hoothoot',
      'Noctowl',
      'Ledyba',
      'Spinarak',
      'Ariados',
      'Pineco',
      'Stantler',
      'Plusle',
      'Minun',
      'Shinx',
    ],
    id: 21,
    pokemon: null,
    location: 'Route 37',
    status: null,
  },
  {
    filter: ['Poliwag', 'Poliwhirl', 'Magikarp'],
    id: 22,
    pokemon: null,
    location: 'Ecruteak City',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Zubat',
      'Koffing',
      'Weezing',
      'Magmar',
      'Zigzagoon',
      'Meditite',
      'Spinda',
      'Chatot',
    ],
    id: 23,
    pokemon: null,
    location: 'Burned Tower',
    status: null,
  },
  {
    id: 24,
    pokemon: null,
    location: 'Tin Tower',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgeotto',
      'Rattata',
      'Raticate',
      'Meowth',
      'Magnemite',
      'Farfetchd',
      'Exeggcute',
      'Tauros',
      'Hoothoot',
      'Noctowl',
      'Ledyba',
      'Spinarak',
      'Pineco',
      'Snubbull',
      'Miltank',
      'Plusle',
      'Minun',
      'Shinx',
    ],
    id: 25,
    pokemon: null,
    location: 'Route 38',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgeotto',
      'Rattata',
      'Raticate',
      'Meowth',
      'Magnemite',
      'Farfetchd',
      'Exeggcute',
      'Tauros',
      'Hoothoot',
      'Noctowl',
      'Ledyba',
      'Spinarak',
      'Pineco',
      'Miltank',
      'Plusle',
      'Minun',
      'Shinx',
    ],
    id: 26,
    pokemon: null,
    location: 'Route 39',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Krabby', 'Kingler', 'Staryu', 'Magikarp', 'Corsola'],
    id: 27,
    pokemon: null,
    location: 'Olivine City',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Krabby', 'Kingler', 'Staryu', 'Magikarp', 'Corsola'],
    id: 28,
    pokemon: null,
    location: 'Route 40',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Shellder', 'Magikarp', 'Chinchou', 'Lanturn', 'Mantine'],
    id: 29,
    pokemon: null,
    location: 'Route 41',
    status: null,
  },
  {
    filter: ['Zubat', 'Golbat', 'Seel', 'Krabby', 'Makuhita', 'Absol', 'Chingling', 'Bronzor'],
    id: 30,
    pokemon: null,
    location: 'Whirl Islands',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Tentacruel',
      'Krabby',
      'Kingler',
      'Staryu',
      'Magikarp',
      'Shuckle',
      'Corsola',
    ],
    id: 31,
    pokemon: null,
    location: 'Cianwood City',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Spearow',
      'Fearow',
      'Ekans',
      'Arbok',
      'Zubat',
      'Golbat',
      'Mankey',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Mareep',
      'Flaaffy',
      'Marill',
      'Aipom',
      'Heracross',
      'Linoone',
      'Whismur',
      'Bidoof',
      'Buizel',
    ],
    id: 32,
    pokemon: null,
    location: 'Route 42',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Zubat',
      'Golbat',
      'Machop',
      'Geodude',
      'Marill',
      'Makuhita',
      'Absol',
      'Chingling',
      'Bronzor',
    ],
    id: 33,
    pokemon: null,
    location: 'Mt. Mortar',
    status: null,
  },
  {
    id: 34,
    pokemon: null,
    location: 'Mahogany Town',
    status: null,
  },
  {
    id: 35,
    pokemon: null,
    location: 'Rocket Hideout',
    status: null,
  },
  {
    filter: [
      'Pidgeotto',
      'Raticate',
      'Spearow',
      'Venonat',
      'Venomoth',
      'Poliwag',
      'Farfetchd',
      'Exeggcute',
      'Magikarp',
      'Sentret',
      'Furret',
      'Hoothoot',
      'Noctowl',
      'Mareep',
      'Flaaffy',
      'Aipom',
      'Girafarig',
      'Pineco',
      'Heracross',
      'Linoone',
      'Whismur',
      'Bidoof',
      'Buizel',
    ],
    id: 36,
    pokemon: null,
    location: 'Route 43',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Venonat',
      'Exeggcute',
      'Magikarp',
      'Gyarados',
      'Hoothoot',
      'Pineco',
    ],
    id: 37,
    pokemon: null,
    location: 'Lake of Rage',
    status: null,
  },
  {
    filter: [
      'Spearow',
      'Poliwag',
      'Poliwhirl',
      'Bellsprout',
      'Weepinbell',
      'Lickitung',
      'Tangela',
      'Magikarp',
      'Aipom',
      'Heracross',
      'Remoraid',
      'Linoone',
      'Whismur',
      'Bidoof',
      'Buizel',
    ],
    id: 38,
    pokemon: null,
    location: 'Route 44',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Golbat',
      'Jynx',
      'Sneasel',
      'Swinub',
      'Delibird',
      'Makuhita',
      'Absol',
      'Chingling',
      'Bronzor',
    ],
    id: 39,
    pokemon: null,
    location: 'Ice Path',
    status: null,
  },
  {
    filter: ['Poliwag', 'Magikarp'],
    id: 40,
    pokemon: null,
    location: 'Blackthorn City',
    status: null,
  },
  {
    filter: ['Magikarp', 'Dratini', 'Dragonair'],
    id: 41,
    pokemon: null,
    location: "Dragon's Den",
    status: null,
  },
  {
    filter: [
      'Spearow',
      'Poliwag',
      'Geodude',
      'Graveler',
      'Magikarp',
      'Dratini',
      'Dragonair',
      'Aipom',
      'Gligar',
      'Heracross',
      'Teddiursa',
      'Skarmory',
      'Phanpy',
      'Donphan',
      'Linoone',
      'Whismur',
      'Swablu',
      'Bidoof',
      'Buizel',
    ],
    id: 42,
    pokemon: null,
    location: 'Route 45',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Raticate',
      'Ekans',
      'Arbok',
      'Sandslash',
      'Tentacool',
      'Tentacruel',
      'Ponyta',
      'Doduo',
      'Dodrio',
      'Shellder',
      'Exeggcute',
      'Magikarp',
      'Hoothoot',
      'Noctowl',
      'Chinchou',
      'Lanturn',
      'Quagsire',
      'Pineco',
      'Linoone',
      'Whismur',
      'Luvdisc',
      'Bidoof',
      'Buizel',
    ],
    id: 43,
    pokemon: null,
    location: 'Route 27',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Zubat',
      'Golbat',
      'Slowpoke',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Makuhita',
      'Absol',
      'Chingling',
      'Bronzor',
    ],
    id: 44,
    pokemon: null,
    location: 'Tohjo Falls',
    status: null,
  },
  {
    filter: [
      'Sandslash',
      'Golbat',
      'Graveler',
      'Onix',
      'Rhyhorn',
      'Rhydon',
      'Ursaring',
      'Donphan',
      'Makuhita',
      'Absol',
      'Chingling',
      'Bronzor',
    ],
    id: 45,
    pokemon: null,
    location: 'Victory Road',
    status: null,
  },
  {
    id: 46,
    pokemon: null,
    location: 'Indigo Plateau',
    status: null,
  },
  {
    filter: [
      'Diglett',
      'Tentacool',
      'Tentacruel',
      'Shellder',
      'Magikarp',
      'Snorlax',
      'Chinchou',
      'Lanturn',
      'Shuckle',
      'Wingull',
    ],
    id: 47,
    pokemon: null,
    location: 'Vermillion City',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Rattata',
      'Raticate',
      'Jigglypuff',
      'Oddish',
      'Meowth',
      'Psyduck',
      'Golduck',
      'Poliwag',
      'Abra',
      'Bellsprout',
      'Magnemite',
      'Drowzee',
      'Magikarp',
      'Snubbull',
      'Granbull',
      'Linoone',
      'Whismur',
      'Bidoof',
      'Buizel',
    ],
    id: 48,
    pokemon: null,
    location: 'Route 6',
    status: null,
  },
  {
    filter: ['Treecko', 'Torchic', 'Mudkip'],
    id: 49,
    pokemon: null,
    location: 'Saffron City',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Pidgeotto',
      'Jigglypuff',
      'Oddish',
      'Gloom',
      'Meowth',
      'Abra',
      'Bellsprout',
      'Hoothoot',
      'Noctowl',
      'Snubbull',
      'Plusle',
      'Minun',
      'Shinx',
    ],
    id: 50,
    pokemon: null,
    location: 'Route 5',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Spearow',
      'Vulpix',
      'Jigglypuff',
      'Meowth',
      'Persian',
      'Growlithe',
      'Abra',
      'Murkrow',
      'Snubbull',
      'Houndour',
      'Plusle',
      'Minun',
      'Shinx',
    ],
    id: 51,
    pokemon: null,
    location: 'Route 7',
    status: null,
  },
  {
    filter: [
      'Pidgeotto',
      'Rattata',
      'Vulpix',
      'Jigglypuff',
      'Meowth',
      'Growlithe',
      'Abra',
      'Kadabra',
      'Haunter',
      'Noctowl',
      'Snubbull',
      'Plusle',
      'Minun',
      'Shinx',
    ],
    id: 52,
    pokemon: null,
    location: 'Route 8',
    status: null,
  },
  {
    filter: [
      'Raticate',
      'Spearow',
      'Fearow',
      'Zubat',
      'Venonat',
      'Venomoth',
      'Voltorb',
      'Marowak',
      'Goldeen',
      'Seaking',
      'Electabuzz',
      'Magikarp',
      'Zapdos',
      'Quagsire',
      'Linoone',
      'Whismur',
      'Bidoof',
      'Buizel',
    ],
    id: 53,
    pokemon: null,
    location: 'Route 10',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Machop',
      'Machoke',
      'Geodude',
      'Haunter',
      'Cubone',
      'Marowak',
      'Makuhita',
      'Absol',
      'Chingling',
      'Bronzor',
    ],
    id: 54,
    pokemon: null,
    location: 'Rock Tunnel',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Spearow',
      'Fearow',
      'Zubat',
      'Venonat',
      'Venomoth',
      'Mankey',
      'Primeape',
      'Marowak',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Linoone',
      'Whismur',
      'Sableye',
      'Mawile',
      'Bidoof',
      'Buizel',
    ],
    id: 55,
    pokemon: null,
    location: 'Route 9',
    status: null,
  },
  {
    filter: ['Goldeen', 'Seaking', 'Magikarp'],
    id: 56,
    pokemon: null,
    location: 'Cerulean City',
    status: null,
  },
  {
    filter: ['Goldeen', 'Seaking', 'Magikarp'],
    id: 57,
    pokemon: null,
    location: 'Route 24',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Weedle',
      'Kakuna',
      'Pidgey',
      'Pidgeotto',
      'Oddish',
      'Venonat',
      'Psyduck',
      'Poliwag',
      'Abra',
      'Bellsprout',
      'Krabby',
      'Kingler',
      'Goldeen',
      'Magikarp',
    ],
    id: 58,
    pokemon: null,
    location: 'Route 25',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Spearow',
      'Ekans',
      'Arbok',
      'Clefairy',
      'Jigglypuff',
      'Zubat',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Linoone',
      'Whismur',
      'Bidoof',
      'Buizel',
    ],
    id: 59,
    pokemon: null,
    location: 'Route 4',
    status: null,
  },
  {
    filter: ['Fearow', 'Grimer', 'Muk', 'Murkrow', 'Slugma', 'Plusle', 'Minun', 'Shinx'],
    id: 60,
    pokemon: null,
    location: 'Route 16',
    status: null,
  },
  {
    filter: ['Fearow', 'Grimer', 'Muk', 'Slugma', 'Plusle', 'Minun', 'Shinx'],
    id: 61,
    pokemon: null,
    location: 'Route 17',
    status: null,
  },
  {
    filter: ['Fearow', 'Grimer', 'Muk', 'Murkrow', 'Slugma', 'Plusle', 'Minun', 'Shinx'],
    id: 62,
    pokemon: null,
    location: 'Route 18',
    status: null,
  },
  {
    filter: ['Magikarp', 'Gyarados', 'Hoothoot', 'Spinark', 'Ledyba', 'Wurmple', 'Tangela'],
    id: 63,
    pokemon: null,
    location: 'Fuschia City',
    status: null,
  },
  {
    filter: [
      'Pidgeotto',
      'Nidorina',
      'Nidorino',
      'Venonat',
      'Venomoth',
      'Chansey',
      'Noctowl',
      'Hoppip',
      'Quagsire',
      'Plusle',
      'Minun',
      'Shinx',
    ],
    id: 64,
    pokemon: null,
    location: 'Route 15',
    status: null,
  },
  {
    filter: [
      'Pidgeotto',
      'Nidorina',
      'Nidorino',
      'Venonat',
      'Venomoth',
      'Chansey',
      'Noctowl',
      'Hoppip',
      'Skiploom',
      'Quagsire',
      'Plusle',
      'Minun',
      'Shinx',
    ],
    id: 65,
    pokemon: null,
    location: 'Route 14',
    status: null,
  },
  {
    filter: [
      'Pidgeotto',
      'Nidorina',
      'Nidorino',
      'Venonat',
      'Venomoth',
      'Tentacool',
      'Tentacruel',
      'Chansey',
      'Magikarp',
      'Noctowl',
      'Hoppip',
      'Quagsire',
      'Qwilfish',
      'Linoone',
      'Whismur',
      'Bidoof',
      'Buizel',
    ],
    id: 66,
    pokemon: null,
    location: 'Route 13',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Magikarp', 'Snorlax', 'Quagsire', 'Qwilfish', 'Relicanth'],
    id: 67,
    pokemon: null,
    location: 'Route 12',
    status: null,
  },
  {
    filter: [
      'Pidgeotto',
      'Rattata',
      'Raticate',
      'Meowth',
      'Magnemite',
      'Drowzee',
      'Hypno',
      'Snorlax',
      'Noctowl',
      'Hoppip',
      'Plusle',
      'Minun',
      'Shinx',
    ],
    id: 68,
    pokemon: null,
    location: 'Route 11',
    status: null,
  },
  {
    filter: ['Diglett', 'Dugtrio', 'Makuhita', 'Absol', 'Chingling', 'Bronzor'],
    id: 69,
    pokemon: null,
    location: "Diglett's Cave",
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgey',
      'Pidgeotto',
      'Pikachu',
      'Hoothoot',
      'Noctowl',
      'Ledyba',
      'Ledian',
      'Spinarak',
      'Ariados',
      'Plusle',
      'Minun',
      'Shinx',
    ],
    id: 70,
    pokemon: null,
    location: 'Route 2',
    status: null,
  },
  {
    filter: ['Rapidash', 'Xatu', 'Hoothoot', 'Pineco', 'Wurmple', 'Starly', 'Latias', 'Latios'],
    id: 71,
    pokemon: null,
    location: 'Pewter City',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Spearow',
      'Ekans',
      'Arbok',
      'Clefairy',
      'Jigglypuff',
      'Zubat',
      'Plusle',
      'Minun',
      'Gulpin',
      'Baltoy',
      'Shinx',
    ],
    id: 73,
    pokemon: null,
    location: 'Route 3',
    status: null,
  },
  {
    filter: [
      'Sandshrew',
      'Sandslash',
      'Clefairy',
      'Zubat',
      'Paras',
      'Geodude',
      'Makuhita',
      'Absol',
      'Chingling',
      'Bronzor',
      'Poliwag',
      'Magikarp',
    ],
    id: 74,
    pokemon: null,
    location: 'Mt. Moon',
    status: null,
  },
  {
    filter: ['Poliwag', 'Poliwhirl', 'Magikarp'],
    id: 75,
    pokemon: null,
    location: 'Viridian City',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Rattata',
      'Raticate',
      'Sentret',
      'Furret',
      'Hoothoot',
      'Poochyena',
      'Plusle',
      'Minun',
      'Shinx',
    ],
    id: 76,
    pokemon: null,
    location: 'Route 1',
    status: null,
  },
  {
    filter: [
      'Bulbasaur',
      'Charmander',
      'Squirtle',
      'Tentacool',
      'Tentacruel',
      'Shellder',
      'Magikarp',
      'Chinchou',
      'Lanturn',
    ],
    id: 77,
    pokemon: null,
    location: 'Pallet Town',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Tentacool',
      'Tentacruel',
      'Shellder',
      'Tangela',
      'Mr-mime',
      'Magikarp',
      'Chinchou',
      'Lanturn',
      'Linoone',
      'Whismur',
      'Bidoof',
      'Buizel',
    ],
    id: 78,
    pokemon: null,
    location: 'Route 21',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Shellder', 'Magikarp', 'Chinchou', 'Lanturn'],
    id: 79,
    pokemon: null,
    location: 'Cinnabar Island',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Shellder', 'Magikarp', 'Chinchou', 'Lanturn'],
    id: 80,
    pokemon: null,
    location: 'Route 20',
    status: null,
  },
  {
    id: 81,
    pokemon: null,
    location: 'Route 19',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Spearow',
      'Fearow',
      'Poliwag',
      'Poliwhirl',
      'Ponyta',
      'Doduo',
      'Magikarp',
      'Linoone',
      'Whismur',
      'Bidoof',
      'Buizel',
    ],
    id: 82,
    pokemon: null,
    location: 'Route 22',
    status: null,
  },
  {
    filter: [
      'Arbok',
      'Golbat',
      'Poliwag',
      'Poliwhirl',
      'Ponyta',
      'Rapidash',
      'Doduo',
      'Dodrio',
      'Tangela',
      'Magikarp',
      'Sneasel',
      'Ursaring',
      'Donphan',
      'Linoone',
      'Whismur',
      'Bidoof',
      'Buizel',
    ],
    id: 83,
    pokemon: null,
    location: 'Route 28',
    status: null,
  },
  {
    filter: [
      'Golbat',
      'Parasect',
      'Golduck',
      'Machoke',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Quagsire',
      'Misdreavus',
      'Steelix',
      'Ursaring',
      'Donphan',
      'Larvitar',
      'Makuhita',
      'Absol',
      'Chingling',
      'Bronzor',
    ],
    id: 84,
    pokemon: null,
    location: 'Mt. Silver',
    status: null,
  },
];

export default G_S_C;
