import { TEncounter } from 'constants/types';

const G_S_C: TEncounter[] = [
  {
    filter: ['Cyndaquil', 'Chikorita', 'Totodile'],
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Tentacruel',
      'Shellder',
      'Magikarp',
      'Chikorita',
      'Cyndaquil',
      'Totodile',
      'Chinchou',
      'Lanturn',
    ],
    id: 1,
    pokemon: null,
    location: 'New Bark Town',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Rattata',
      'Spearow',
      'Exeggcute',
      'Sentret',
      'Hoothoot',
      'Ledyba',
      'Spinarak',
      'Hoppip',
      'Aipom',
      'Pineco',
      'Heracross',
    ],
    id: 2,
    pokemon: null,
    location: 'Route 29',
    status: null,
  },
  {
    filter: ['Rattata', 'Spearow', 'Geodude', 'Jigglypuff', 'Phanpy'],
    id: 3,
    pokemon: null,
    location: 'Route 46',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Krabby', 'Kingler', 'Staryu', 'Magikarp', 'Corsola'],
    id: 4,
    pokemon: null,
    location: 'Cherrygrove City',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Weedle',
      'Kakuna',
      'Pidgey',
      'Rattata',
      'Spearow',
      'Zubat',
      'Poliwag',
      'Poliwhirl',
      'Exeggcute',
      'Magikarp',
      'Hoothoot',
      'Ledyba',
      'Spinarak',
      'Hoppip',
      'Aipom',
      'Pineco',
      'Heracross',
    ],
    id: 5,
    pokemon: null,
    location: 'Route 30',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Weedle',
      'Kakuna',
      'Pidgey',
      'Rattata',
      'Spearow',
      'Zubat',
      'Poliwag',
      'Poliwhirl',
      'Bellsprout',
      'Gastly',
      'Exeggcute',
      'Magikarp',
      'Hoothoot',
      'Ledyba',
      'Spinarak',
      'Hoppip',
      'Aipom',
      'Pineco',
      'Heracross',
    ],
    id: 6,
    pokemon: null,
    location: 'Route 31',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Golbat',
      'Graveler',
      'Geodude',
      'Krabby',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Dunsparce',
      'Shuckle',
      'Wobbuffet',
      'Teddiursa',
      'Ursaring',
    ],
    id: 7,
    pokemon: null,
    location: 'Dark Cave',
    status: null,
  },
  {
    filter: ['Poliwag', 'Poliwhirl', 'Magikarp', 'Togepi'],
    id: 8,
    pokemon: null,
    location: 'Violet City',
    status: null,
  },
  {
    filter: ['Rattata', 'Gastly'],
    id: 9,
    pokemon: null,
    location: 'Sprout Tower',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Rattata',
      'Spearow',
      'Ekans',
      'Zubat',
      'Bellsprout',
      'Tentacool',
      'Tentacruel',
      'Gastly',
      'Exeggcute',
      'Magikarp',
      'Hoothoot',
      'Mareep',
      'Hoppip',
      'Aipom',
      'Wooper',
      'Quagsire',
      'Pineco',
      'Qwilfish',
      'Heracross',
    ],
    id: 10,
    pokemon: null,
    location: 'Route 32',
    status: null,
  },
  {
    filter: ['Poliwag', 'Magikarp', 'Natu', 'Wooper', 'Quagsire', 'Smeargle', 'Unown'],
    id: 11,
    pokemon: null,
    location: 'Ruins of Alph',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Sandshrew',
      'Zubat',
      'Geodude',
      'Onix',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Wooper',
      'Quagsire',
    ],
    id: 12,
    pokemon: null,
    location: 'Union Cave',
    status: null,
  },
  {
    filter: ['Rattata', 'Spearow', 'Ekans', 'Zubat', 'Geodude', 'Hoppip', 'Aipom', 'Heracross'],
    id: 13,
    pokemon: null,
    location: 'Route 33',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Spearow',
      'Ekans',
      'Exeggcute',
      'Aipom',
      'Pineco',
      'Heracross',
    ],
    id: 14,
    pokemon: null,
    location: 'Azalea Town',
    status: null,
  },
  {
    filter: ['Zubat', 'Golbat', 'Slowpoke', 'Slowbro', 'Goldeen', 'Seaking', 'Magikarp'],
    id: 15,
    pokemon: null,
    location: 'Slowpoke Well',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgey',
      'Zubat',
      'Oddish',
      'Paras',
      'Venonat',
      'Psyduck',
      'Golduck',
      'Poliwag',
      'Exeggcute',
      'Magikarp',
      'Hoothoot',
      'Noctowl',
      'Pineco',
    ],
    id: 16,
    pokemon: null,
    location: 'Ilex Forest',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgey',
      'Rattata',
      'Jigglypuff',
      'Abra',
      'Tentacool',
      'Tentacruel',
      'Drowzee',
      'Krabby',
      'Kingler',
      'Exeggcute',
      'Staryu',
      'Magikarp',
      'Ditto',
      'Hoothoot',
      'Ledyba',
      'Spinarak',
      'Pichu',
      'Cleffa',
      'Igglybuff',
      'Pineco',
      'Snubbull',
      'Corsola',
      'Tyrogue',
      'Smoochum',
      'Elekid',
      'Magby',
    ],
    id: 17,
    pokemon: null,
    location: 'Route 34',
    status: null,
  },
  {
    filter: ['Eevee'],
    id: 18,
    pokemon: null,
    location: 'Goldenrod City',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgey',
      'Nidoran♀',
      'Nidoran♂',
      'Jigglypuff',
      'Meowth',
      'Psyduck',
      'Golduck',
      'Growlithe',
      'Poliwag',
      'Abra',
      'Drowzee',
      'Exeggcute',
      'Magikarp',
      'Ditto',
      'Hoothoot',
      'Ledyba',
      'Spinarak',
      'Yanma',
      'Pineco',
      'Snubbull',
    ],
    id: 19,
    pokemon: null,
    location: 'Route 35',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Weedle',
      'Kakuna',
      'Pidgey',
      'Nidoran♀',
      'Nidoran♂',
      'Venonat',
      'Psyduck',
      'Hoothoot',
      'Ledyba',
      'Spinarak',
      'Sunkern',
    ],
    id: 20,
    pokemon: null,
    location: 'National Park',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgey',
      'Nidoran♀',
      'Nidoran♂',
      'Vulpix',
      'Growlithe',
      'Bellsprout',
      'Gastly',
      'Exeggcute',
      'Hoothoot',
      'Ledyba',
      'Spinarak',
      'Sudowoodo',
      'Pineco',
      'Stantler',
    ],
    id: 21,
    pokemon: null,
    location: 'Route 36',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgey',
      'Pidgeotto',
      'Vulpix',
      'Growlithe',
      'Exeggcute',
      'Hoothoot',
      'Noctowl',
      'Ledyba',
      'Spinarak',
      'Ariados',
      'Pineco',
      'Stantler',
    ],
    id: 22,
    pokemon: null,
    location: 'Route 37',
    status: null,
  },
  {
    filter: ['Poliwag', 'Poliwhirl', 'Magikarp'],
    id: 23,
    pokemon: null,
    location: 'Ecruteak City',
    status: null,
  },
  {
    filter: ['Rattata', 'Raticate', 'Zubat', 'Koffing', 'Weezing', 'Magmar'],
    id: 24,
    pokemon: null,
    location: 'Burned Tower',
    status: null,
  },
  {
    filter: ['Ho-oh', 'Rattata', 'Gastly', 'Suicune'],
    id: 25,
    pokemon: null,
    location: 'Tin Tower',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgeotto',
      'Rattata',
      'Raticate',
      'Meowth',
      'Magnemite',
      'Farfetchd',
      'Exeggcute',
      'Tauros',
      'Hoothoot',
      'Noctowl',
      'Ledyba',
      'Spinarak',
      'Pineco',
      'Snubbull',
      'Miltank',
    ],
    id: 26,
    pokemon: null,
    location: 'Route 38',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgeotto',
      'Rattata',
      'Raticate',
      'Meowth',
      'Magnemite',
      'Farfetchd',
      'Exeggcute',
      'Tauros',
      'Hoothoot',
      'Noctowl',
      'Ledyba',
      'Spinarak',
      'Pineco',
      'Miltank',
    ],
    id: 27,
    pokemon: null,
    location: 'Route 39',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Krabby', 'Kingler', 'Staryu', 'Magikarp', 'Corsola'],
    id: 28,
    pokemon: null,
    location: 'Olivine City',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Tentacruel',
      'Krabby',
      'Kingler',
      'Staryu',
      'Magikarp',
      'Shuckle',
      'Corsola',
    ],
    id: 29,
    pokemon: null,
    location: 'Route 40',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Shellder', 'Magikarp', 'Chinchou', 'Lanturn', 'Mantine'],
    id: 30,
    pokemon: null,
    location: 'Route 41',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Golbat',
      'Tentacool',
      'Tentacruel',
      'Seel',
      'Krabby',
      'Kingler',
      'Horsea',
      'Seadra',
      'Magikarp',
      'Lugia',
    ],
    id: 31,
    pokemon: null,
    location: 'Whirl Islands',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Tentacruel',
      'Krabby',
      'Kingler',
      'Staryu',
      'Magikarp',
      'Shuckle',
      'Corsola',
    ],
    id: 32,
    pokemon: null,
    location: 'Cianwood City',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Spearow',
      'Fearow',
      'Ekans',
      'Arbok',
      'Zubat',
      'Golbat',
      'Mankey',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Mareep',
      'Flaaffy',
      'Marill',
      'Aipom',
      'Heracross',
    ],
    id: 33,
    pokemon: null,
    location: 'Route 42',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Zubat',
      'Golbat',
      'Machop',
      'Geodude',
      'Graveler',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Marill',
      'Tyrogue',
    ],
    id: 34,
    pokemon: null,
    location: 'Mt. Mortar',
    status: null,
  },
  {
    filter: ['Geodude', 'Voltorb', 'Electrode', 'Koffing'],
    id: 35,
    pokemon: null,
    location: 'Rocket HQ',
    status: null,
  },
  {
    filter: [
      'Pidgeotto',
      'Raticate',
      'Spearow',
      'Venonat',
      'Venomoth',
      'Poliwag',
      'Farfetchd',
      'Exeggcute',
      'Magikarp',
      'Sentret',
      'Furret',
      'Hoothoot',
      'Noctowl',
      'Mareep',
      'Flaaffy',
      'Aipom',
      'Girafarig',
      'Pineco',
      'Heracross',
    ],
    id: 36,
    pokemon: null,
    location: 'Route 43',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Venonat',
      'Exeggcute',
      'Magikarp',
      'Gyarados',
      'Hoothoot',
      'Pineco',
    ],
    id: 37,
    pokemon: null,
    location: 'Lake of Rage',
    status: null,
  },
  {
    filter: [
      'Spearow',
      'Poliwag',
      'Poliwhirl',
      'Bellsprout',
      'Weepinbell',
      'Lickitung',
      'Tangela',
      'Magikarp',
      'Aipom',
      'Heracross',
      'Remoraid',
    ],
    id: 38,
    pokemon: null,
    location: 'Route 44',
    status: null,
  },
  {
    filter: ['Zubat', 'Golbat', 'Jynx', 'Sneasel', 'Swinub', 'Delibird'],

    id: 39,
    pokemon: null,
    location: 'Ice Path',
    status: null,
  },
  {
    filter: ['Poliwag', 'Magikarp'],
    id: 40,
    pokemon: null,
    location: 'Blackthorn City',
    status: null,
  },
  {
    filter: ['Magikarp', 'Dratini', 'Dragonair'],
    id: 41,
    pokemon: null,
    location: "Dragon's Den",
    status: null,
  },
  {
    filter: [
      'Spearow',
      'Geodude',
      'Graveler',
      'Magikarp',
      'Dratini',
      'Dragonair',
      'Aipom',
      'Gligar',
      'Heracross',
      'Teddiursa',
      'Skarmory',
      'Phanpy',
      'Donphan',
    ],
    id: 42,
    pokemon: null,
    location: 'Route 45',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Raticate',
      'Ekans',
      'Arbok',
      'Sandslash',
      'Tentacool',
      'Tentacruel',
      'Ponyta',
      'Doduo',
      'Dodrio',
      'Shellder',
      'Exeggcute',
      'Magikarp',
      'Hoothoot',
      'Noctowl',
      'Chinchou',
      'Lanturn',
      'Quagsire',
      'Pineco',
    ],
    id: 43,
    pokemon: null,
    location: 'Route 27',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Zubat',
      'Golbat',
      'Slowpoke',
      'Goldeen',
      'Seaking',
      'Magikarp',
    ],
    id: 44,
    pokemon: null,
    location: 'Tohjo Falls',
    status: null,
  },
  {
    filter: ['Sandslash', 'Golbat', 'Graveler', 'Onix', 'Rhyhorn', 'Rhydon', 'Ursaring', 'Donphan'],
    id: 45,
    pokemon: null,
    location: 'Victory Road',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Shellder', 'Magikarp', 'Snorlax', 'Chinchou', 'Lanturn'],
    id: 47,
    pokemon: null,
    location: 'Vermilion City',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Rattata',
      'Raticate',
      'Jigglypuff',
      'Oddish',
      'Meowth',
      'Psyduck',
      'Golduck',
      'Poliwag',
      'Abra',
      'Bellsprout',
      'Magnemite',
      'Drowzee',
      'Magikarp',
      'Snubbull',
      'Granbull',
    ],
    id: 48,
    pokemon: null,
    location: 'Route 6',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Pidgeotto',
      'Jigglypuff',
      'Oddish',
      'Gloom',
      'Meowth',
      'Abra',
      'Bellsprout',
      'Hoothoot',
      'Noctowl',
      'Snubbull',
    ],
    id: 50,
    pokemon: null,
    location: 'Route 5',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Spearow',
      'Vulpix',
      'Jigglypuff',
      'Meowth',
      'Persian',
      'Growlithe',
      'Abra',
      'Murkrow',
      'Snubbull',
      'Houndour',
    ],
    id: 51,
    pokemon: null,
    location: 'Route 7',
    status: null,
  },
  {
    filter: [
      'Pidgeotto',
      'Rattata',
      'Vulpix',
      'Jigglypuff',
      'Meowth',
      'Growlithe',
      'Abra',
      'Kadabra',
      'Haunter',
      'Noctowl',
      'Snubbull',
    ],
    id: 52,
    pokemon: null,
    location: 'Route 8',
    status: null,
  },
  {
    filter: [
      'Raticate',
      'Spearow',
      'Fearow',
      'Zubat',
      'Venonat',
      'Venomoth',
      'Voltorb',
      'Marowak',
      'Goldeen',
      'Seaking',
      'Electabuzz',
      'Magikarp',
      'Quagsire',
    ],
    id: 53,
    pokemon: null,
    location: 'Route 10',
    status: null,
  },
  {
    filter: ['Zubat', 'Machop', 'Machoke', 'Geodude', 'Haunter', 'Cubone', 'Marowak'],
    id: 54,
    pokemon: null,
    location: 'Rock Tunnel',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Spearow',
      'Fearow',
      'Zubat',
      'Venonat',
      'Venomoth',
      'Mankey',
      'Primeape',
      'Marowak',
      'Goldeen',
      'Seaking',
      'Magikarp',
    ],
    id: 55,
    pokemon: null,
    location: 'Route 9',
    status: null,
  },
  {
    filter: ['Goldeen', 'Seaking', 'Magikarp'],
    id: 56,
    pokemon: null,
    location: 'Cerulean City',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Oddish',
      'Gloom',
      'Venonat',
      'Venomoth',
      'Abra',
      'Bellsprout',
      'Weepinbell',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Sunkern',
    ],
    id: 57,
    pokemon: null,
    location: 'Route 24',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Pidgey',
      'Pidgeotto',
      'Oddish',
      'Venonat',
      'Venomoth',
      'Abra',
      'Bellsprout',
      'Weepinbell',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Hoothoot',
      'Noctowl',
    ],
    id: 58,
    pokemon: null,
    location: 'Route 25',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Pidgey',
      'Pidgeotto',
      'Oddish',
      'Venonat',
      'Venomoth',
      'Abra',
      'Bellsprout',
      'Weepinbell',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Hoothoot',
      'Noctowl',
    ],
    id: 59,
    pokemon: null,
    location: 'Route 4',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Pidgey',
      'Pidgeotto',
      'Oddish',
      'Venonat',
      'Venomoth',
      'Abra',
      'Bellsprout',
      'Weepinbell',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Hoothoot',
      'Noctowl',
    ],
    id: 60,
    pokemon: null,
    location: 'Route 16',
    status: null,
  },
  {
    filter: ['Fearow', 'Grimer', 'Muk', 'Slugma'],
    id: 61,
    pokemon: null,
    location: 'Route 17',
    status: null,
  },
  {
    filter: ['Fearow', 'Grimer', 'Muk', 'Slugma'],
    id: 62,
    pokemon: null,
    location: 'Route 18',
    status: null,
  },
  {
    filter: ['Magikarp', 'Gyarados', 'Hoothoot', 'Spinark', 'Ledyba', 'Wurmple', 'Tangela'],
    id: 63,
    pokemon: null,
    location: 'Fuschia City',
    status: null,
  },
  {
    filter: [
      'Pidgeotto',
      'Nidorina',
      'Nidorino',
      'Venonat',
      'Venomoth',
      'Chansey',
      'Noctowl',
      'Hoppip',
      'Quagsire',
    ],
    id: 64,
    pokemon: null,
    location: 'Route 15',
    status: null,
  },
  {
    filter: [
      'Pidgeotto',
      'Nidorina',
      'Nidorino',
      'Venonat',
      'Venomoth',
      'Chansey',
      'Noctowl',
      'Hoppip',
      'Skiploom',
      'Quagsire',
    ],
    id: 65,
    pokemon: null,
    location: 'Route 14',
    status: null,
  },
  {
    filter: [
      'Pidgeotto',
      'Nidorina',
      'Nidorino',
      'Venonat',
      'Venomoth',
      'Tentacool',
      'Tentacruel',
      'Chansey',
      'Magikarp',
      'Noctowl',
      'Hoppip',
      'Quagsire',
      'Qwilfish',
    ],
    id: 66,
    pokemon: null,
    location: 'Route 13',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Magikarp', 'Quagsire', 'Qwilfish'],
    id: 67,
    pokemon: null,
    location: 'Route 12',
    status: null,
  },
  {
    filter: [
      'Pidgeotto',
      'Rattata',
      'Raticate',
      'Meowth',
      'Magnemite',
      'Drowzee',
      'Hypno',
      'Noctowl',
      'Hoppip',
    ],
    id: 68,
    pokemon: null,
    location: 'Route 11',
    status: null,
  },
  {
    filter: ['Diglett', 'Dugtrio'],
    id: 69,
    pokemon: null,
    location: "Diglett's Cave",
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Weedle',
      'Kakuna',
      'Beedrill',
      'Pidgey',
      'Pidgeotto',
      'Pikachu',
      'Hoothoot',
      'Noctowl',
      'Ledyba',
      'Ledian',
      'Spinarak',
      'Ariados',
    ],
    id: 70,
    pokemon: null,
    location: 'Route 2',
    status: null,
  },
  {
    filter: ['Rapidash', 'Xatu'],
    id: 71,
    pokemon: null,
    location: 'Pewter City',
    status: null,
  },
  {
    filter: ['Rattata', 'Raticate', 'Spearow', 'Ekans', 'Arbok', 'Clefairy', 'Jigglypuff', 'Zubat'],
    id: 73,
    pokemon: null,
    location: 'Route 3',
    status: null,
  },
  {
    filter: [
      'Sandshrew',
      'Sandslash',
      'Clefairy',
      'Zubat',
      'Paras',
      'Geodude',
      'Poliwag',
      'Magikarp',
    ],
    id: 74,
    pokemon: null,
    location: 'Mt. Moon',
    status: null,
  },
  {
    filter: ['Poliwag', 'Poliwhirl', 'Magikarp'],
    id: 75,
    pokemon: null,
    location: 'Viridian City',
    status: null,
  },
  {
    filter: ['Pidgey', 'Rattata', 'Raticate', 'Sentret', 'Furret', 'Hoothoot'],
    id: 76,
    pokemon: null,
    location: 'Route 1',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Shellder', 'Magikarp', 'Chinchou', 'Lanturn'],
    id: 77,
    pokemon: null,
    location: 'Pallet Town',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Tentacool',
      'Tentacruel',
      'Shellder',
      'Tangela',
      'Mr. Mime',
      'Magikarp',
      'Chinchou',
      'Lanturn',
    ],
    id: 78,
    pokemon: null,
    location: 'Route 21',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Shellder', 'Magikarp', 'Chinchou', 'Lanturn'],
    id: 79,
    pokemon: null,
    location: 'Cinnabar Island',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Shellder', 'Magikarp', 'Chinchou', 'Lanturn'],
    id: 80,
    pokemon: null,
    location: 'Route 20',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Krabby', 'Kingler', 'Staryu', 'Magikarp', 'Corsola'],
    id: 81,
    pokemon: null,
    location: 'Route 19',
    status: null,
  },
  {
    filter: ['Rattata', 'Spearow', 'Fearow', 'Poliwag', 'Poliwhirl', 'Ponyta', 'Doduo', 'Magikarp'],
    id: 82,
    pokemon: null,
    location: 'Route 22',
    status: null,
  },
  {
    filter: [
      'Arbok',
      'Golbat',
      'Poliwag',
      'Poliwhirl',
      'Ponyta',
      'Rapidash',
      'Doduo',
      'Dodrio',
      'Tangela',
      'Magikarp',
      'Sneasel',
      'Ursaring',
      'Donphan',
    ],
    id: 83,
    pokemon: null,
    location: 'Route 28',
    status: null,
  },
  {
    filter: [
      'Arbok',
      'Poliwhirl',
      'Doduo',
      'Dodrio',
      'Golbat',
      'Rapidash',
      'Parasect',
      'Sneasel',
      'Tangela',
      'Magmar',
      'Golduck',
      'Machoke',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Quagsire',
      'Misdreavus',
      'Steelix',
      'Ursaring',
      'Donphan',
      'Larvitar',
      'Pupitar',
    ],
    id: 84,
    pokemon: null,
    location: 'Mt. Silver',
    status: null,
  },
];

export default G_S_C;
