import type { TEncounter } from 'constants/types';

const G_S_C: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
    filterKey: 'gsc-0',
  },
  {
    id: 1,
    pokemon: null,
    location: 'New Bark Town',
    status: null,
    filterKey: 'gsc-1',
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 29',
    status: null,
    filterKey: 'gsc-2',
  },
  {
    id: 3,
    pokemon: null,
    location: 'Route 46',
    status: null,
    filterKey: 'gsc-3',
  },
  {
    id: 4,
    pokemon: null,
    location: 'Cherrygrove City',
    status: null,
    filterKey: 'gsc-4',
  },
  {
    id: 5,
    pokemon: null,
    location: 'Route 30',
    status: null,
    filterKey: 'gsc-5',
  },
  {
    id: 6,
    pokemon: null,
    location: 'Route 31',
    status: null,
    filterKey: 'gsc-6',
  },
  {
    id: 7,
    pokemon: null,
    location: 'Dark Cave',
    status: null,
    filterKey: 'gsc-7',
  },
  {
    id: 8,
    pokemon: null,
    location: 'Violet City',
    status: null,
    filterKey: 'gsc-8',
  },
  {
    id: 9,
    pokemon: null,
    location: 'Sprout Tower',
    status: null,
    filterKey: 'gsc-9',
  },
  {
    id: 10,
    pokemon: null,
    location: 'Route 32',
    status: null,
    filterKey: 'gsc-10',
  },
  {
    id: 11,
    pokemon: null,
    location: 'Ruins of Alph',
    status: null,
    filterKey: 'gsc-11',
  },
  {
    id: 12,
    pokemon: null,
    location: 'Union Cave',
    status: null,
    filterKey: 'gsc-12',
  },
  {
    id: 13,
    pokemon: null,
    location: 'Route 33',
    status: null,
    filterKey: 'gsc-13',
  },
  {
    id: 14,
    pokemon: null,
    location: 'Azalea Town',
    status: null,
    filterKey: 'gsc-14',
  },
  {
    id: 15,
    pokemon: null,
    location: 'Slowpoke Well',
    status: null,
    filterKey: 'gsc-15',
  },
  {
    id: 16,
    pokemon: null,
    location: 'Ilex Forest',
    status: null,
    filterKey: 'gsc-16',
  },
  {
    id: 17,
    pokemon: null,
    location: 'Route 34',
    status: null,
    filterKey: 'gsc-17',
  },
  {
    id: 18,
    pokemon: null,
    location: 'Goldenrod City',
    status: null,
    filterKey: 'gsc-18',
  },
  {
    id: 19,
    pokemon: null,
    location: 'Route 35',
    status: null,
    filterKey: 'gsc-19',
  },
  {
    id: 20,
    pokemon: null,
    location: 'National Park',
    status: null,
    filterKey: 'gsc-20',
  },
  {
    id: 21,
    pokemon: null,
    location: 'Route 36',
    status: null,
    filterKey: 'gsc-21',
  },
  {
    id: 22,
    pokemon: null,
    location: 'Route 37',
    status: null,
    filterKey: 'gsc-22',
  },
  {
    id: 23,
    pokemon: null,
    location: 'Ecruteak City',
    status: null,
    filterKey: 'gsc-23',
  },
  {
    id: 24,
    pokemon: null,
    location: 'Burned Tower',
    status: null,
    filterKey: 'gsc-24',
  },
  {
    id: 25,
    pokemon: null,
    location: 'Tin Tower',
    status: null,
    filterKey: 'gsc-25',
  },
  {
    id: 26,
    pokemon: null,
    location: 'Route 38',
    status: null,
    filterKey: 'gsc-26',
  },
  {
    id: 27,
    pokemon: null,
    location: 'Route 39',
    status: null,
    filterKey: 'gsc-27',
  },
  {
    id: 28,
    pokemon: null,
    location: 'Olivine City',
    status: null,
    filterKey: 'gsc-28',
  },
  {
    id: 29,
    pokemon: null,
    location: 'Route 40',
    status: null,
    filterKey: 'gsc-29',
  },
  {
    id: 30,
    pokemon: null,
    location: 'Route 41',
    status: null,
    filterKey: 'gsc-30',
  },
  {
    id: 31,
    pokemon: null,
    location: 'Whirl Islands',
    status: null,
    filterKey: 'gsc-31',
  },
  {
    id: 32,
    pokemon: null,
    location: 'Cianwood City',
    status: null,
    filterKey: 'gsc-32',
  },
  {
    id: 33,
    pokemon: null,
    location: 'Route 42',
    status: null,
    filterKey: 'gsc-33',
  },
  {
    id: 34,
    pokemon: null,
    location: 'Mt. Mortar',
    status: null,
    filterKey: 'gsc-34',
  },
  {
    id: 35,
    pokemon: null,
    location: 'Rocket HQ',
    status: null,
    filterKey: 'gsc-35',
  },
  {
    id: 36,
    pokemon: null,
    location: 'Route 43',
    status: null,
    filterKey: 'gsc-36',
  },
  {
    id: 37,
    pokemon: null,
    location: 'Lake of Rage',
    status: null,
    filterKey: 'gsc-37',
  },
  {
    id: 38,
    pokemon: null,
    location: 'Route 44',
    status: null,
    filterKey: 'gsc-38',
  },
  {
    id: 39,
    pokemon: null,
    location: 'Ice Path',
    status: null,
    filterKey: 'gsc-39',
  },
  {
    id: 40,
    pokemon: null,
    location: 'Blackthorn City',
    status: null,
    filterKey: 'gsc-40',
  },
  {
    id: 41,
    pokemon: null,
    location: "Dragon's Den",
    status: null,
    filterKey: 'gsc-41',
  },
  {
    id: 42,
    pokemon: null,
    location: 'Route 45',
    status: null,
    filterKey: 'gsc-42',
  },
  {
    id: 43,
    pokemon: null,
    location: 'Route 27',
    status: null,
    filterKey: 'gsc-43',
  },
  {
    id: 44,
    pokemon: null,
    location: 'Tohjo Falls',
    status: null,
    filterKey: 'gsc-44',
  },
  {
    id: 45,
    pokemon: null,
    location: 'Victory Road',
    status: null,
    filterKey: 'gsc-45',
  },
  {
    id: 47,
    pokemon: null,
    location: 'Vermilion City',
    status: null,
    filterKey: 'gsc-47',
  },
  {
    id: 48,
    pokemon: null,
    location: 'Route 6',
    status: null,
    filterKey: 'gsc-48',
  },
  {
    id: 50,
    pokemon: null,
    location: 'Route 5',
    status: null,
    filterKey: 'gsc-50',
  },
  {
    id: 51,
    pokemon: null,
    location: 'Route 7',
    status: null,
    filterKey: 'gsc-51',
  },
  {
    id: 52,
    pokemon: null,
    location: 'Route 8',
    status: null,
    filterKey: 'gsc-52',
  },
  {
    id: 53,
    pokemon: null,
    location: 'Route 10',
    status: null,
    filterKey: 'gsc-53',
  },
  {
    id: 54,
    pokemon: null,
    location: 'Rock Tunnel',
    status: null,
    filterKey: 'gsc-54',
  },
  {
    id: 55,
    pokemon: null,
    location: 'Route 9',
    status: null,
    filterKey: 'gsc-55',
  },
  {
    id: 56,
    pokemon: null,
    location: 'Cerulean City',
    status: null,
    filterKey: 'gsc-56',
  },
  {
    id: 57,
    pokemon: null,
    location: 'Route 24',
    status: null,
    filterKey: 'gsc-57',
  },
  {
    id: 58,
    pokemon: null,
    location: 'Route 25',
    status: null,
    filterKey: 'gsc-58',
  },
  {
    id: 59,
    pokemon: null,
    location: 'Route 4',
    status: null,
    filterKey: 'gsc-59',
  },
  {
    id: 60,
    pokemon: null,
    location: 'Route 16',
    status: null,
    filterKey: 'gsc-60',
  },
  {
    id: 61,
    pokemon: null,
    location: 'Route 17',
    status: null,
    filterKey: 'gsc-61',
  },
  {
    id: 62,
    pokemon: null,
    location: 'Route 18',
    status: null,
    filterKey: 'gsc-62',
  },
  {
    id: 63,
    pokemon: null,
    location: 'Fuschia City',
    status: null,
    filterKey: 'gsc-63',
  },
  {
    id: 64,
    pokemon: null,
    location: 'Route 15',
    status: null,
    filterKey: 'gsc-64',
  },
  {
    id: 65,
    pokemon: null,
    location: 'Route 14',
    status: null,
    filterKey: 'gsc-65',
  },
  {
    id: 66,
    pokemon: null,
    location: 'Route 13',
    status: null,
    filterKey: 'gsc-66',
  },
  {
    id: 67,
    pokemon: null,
    location: 'Route 12',
    status: null,
    filterKey: 'gsc-67',
  },
  {
    id: 68,
    pokemon: null,
    location: 'Route 11',
    status: null,
    filterKey: 'gsc-68',
  },
  {
    id: 69,
    pokemon: null,
    location: "Diglett's Cave",
    status: null,
    filterKey: 'gsc-69',
  },
  {
    id: 70,
    pokemon: null,
    location: 'Route 2',
    status: null,
    filterKey: 'gsc-70',
  },
  {
    id: 71,
    pokemon: null,
    location: 'Pewter City',
    status: null,
    filterKey: 'gsc-71',
  },
  {
    id: 73,
    pokemon: null,
    location: 'Route 3',
    status: null,
    filterKey: 'gsc-73',
  },
  {
    id: 74,
    pokemon: null,
    location: 'Mt. Moon',
    status: null,
    filterKey: 'gsc-74',
  },
  {
    id: 75,
    pokemon: null,
    location: 'Viridian City',
    status: null,
    filterKey: 'gsc-75',
  },
  {
    id: 76,
    pokemon: null,
    location: 'Route 1',
    status: null,
    filterKey: 'gsc-76',
  },
  {
    id: 77,
    pokemon: null,
    location: 'Pallet Town',
    status: null,
    filterKey: 'gsc-77',
  },
  {
    id: 78,
    pokemon: null,
    location: 'Route 21',
    status: null,
    filterKey: 'gsc-78',
  },
  {
    id: 79,
    pokemon: null,
    location: 'Cinnabar Island',
    status: null,
    filterKey: 'gsc-79',
  },
  {
    id: 80,
    pokemon: null,
    location: 'Route 20',
    status: null,
    filterKey: 'gsc-80',
  },
  {
    id: 81,
    pokemon: null,
    location: 'Route 19',
    status: null,
    filterKey: 'gsc-81',
  },
  {
    id: 82,
    pokemon: null,
    location: 'Route 22',
    status: null,
    filterKey: 'gsc-82',
  },
  {
    id: 83,
    pokemon: null,
    location: 'Route 28',
    status: null,
    filterKey: 'gsc-83',
  },
  {
    id: 84,
    pokemon: null,
    location: 'Mt. Silver',
    status: null,
    filterKey: 'gsc-84',
  },
];

export default G_S_C;
