import { TEncounter } from 'constants/types';

const OR_AS: TEncounter[] = [
  {
    filter: ['Treecko', 'Mudkip', 'Torchic'],
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    filter: ['Treecko', 'Mudkip', 'Torchic'],
    id: 1,
    pokemon: null,
    location: 'Littleroot Town',
    status: null,
  },
  {
    filter: [
      'Chikorita',
      'Cyndaquil',
      'Totodile',
      'Treecko',
      'Torchic',
      'Mudkip',
      'Turtwig',
      'Chimchar',
      'Piplup',
      'Snivy',
      'Tepig',
      'Oshawott',
    ],
    id: 2,
    pokemon: null,
    location: 'Route 101',
    status: null,
  },
  {
    filter: ['Poochyena', 'Zigzagoon', 'Wurmple', 'Lotad', 'Seedot', 'Ralts', 'Surskit'],
    id: 3,
    pokemon: null,
    location: 'Route 102',
    status: null,
  },
  {
    filter: ['Poochyena', 'Zigzagoon', 'Wingull'],
    id: 4,
    pokemon: null,
    location: 'Route 103',
    status: null,
  },
  {
    filter: ['Goldeen', 'Magikarp', 'Marill', 'Corphish', 'Surskit', 'Masquerain', 'Azumarill'],
    id: 5,
    pokemon: null,
    location: 'Petalburg City',
    status: null,
  },
  {
    filter: [
      'Magikarp',
      'Marill',
      'Poochyena',
      'Zigzagoon',
      'Wurmple',
      'Taillow',
      'Wingull',
      'Pelipper',
    ],
    id: 6,
    pokemon: null,
    location: 'Route 104',
    status: null,
  },
  {
    filter: [
      'Poochyena',
      'Zigzagoon',
      'Wurmple',
      'Silcoon',
      'Cascoon',
      'Taillow',
      'Shroomish',
      'Slakoth',
    ],
    id: 7,
    pokemon: null,
    location: 'Petalburg Woods',
    status: null,
  },
  {
    filter: ['Makuhita', 'Ralts'],
    id: 8,
    pokemon: null,
    location: 'Rustboro City',
    status: null,
  },
  {
    filter: [
      'Jigglypuff',
      'Tentacool',
      'Magikarp',
      'Taillow',
      'Swellow',
      'Wingull',
      'Pelipper',
      'Wailmer',
      'Swablu',
    ],
    id: 9,
    pokemon: null,
    location: 'Route 115',
    status: null,
  },
  {
    filter: ['Abra', 'Poochyena', 'Zigzagoon', 'Taillow', 'Nincada', 'Whismur', 'Skitty'],
    id: 10,
    pokemon: null,
    location: 'Route 116',
    status: null,
  },
  {
    filter: ['Whismur'],
    id: 11,
    pokemon: null,
    location: 'Rusturf Tunnel',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Wailmer'],
    id: 12,
    pokemon: null,
    location: 'Dewford Town',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Wailmer'],
    id: 13,
    pokemon: null,
    location: 'Route 106',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Abra',
      'Geodude',
      'Makuhita',
      'Aron',
      'Onix',
      'Mawile',
      'Sabeleye',
      'Nosepass',
    ],
    id: 14,
    pokemon: null,
    location: 'Granite Cave',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Wailmer'],
    id: 15,
    pokemon: null,
    location: 'Route 107',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Wailmer'],
    id: 16,
    pokemon: null,
    location: 'Slateport City',
    status: null,
  },
  {
    filter: [
      'Oddish',
      'Tentacool',
      'Magikarp',
      'Poochyena',
      'Zigzagoon',
      'Wingull',
      'Pelipper',
      'Electrike',
      'Plusle',
      'Minun',
      'Gulpin',
      'Wailmer',
      'Magnemite',
    ],
    id: 17,
    pokemon: null,
    location: 'Route 110',
    status: null,
  },
  {
    filter: ['Magnemite', 'Magneton', 'Voltorb', 'Electrode'],
    id: 19,
    pokemon: null,
    location: 'New Mauville',
    status: null,
  },
  {
    filter: [
      'Oddish',
      'Goldeen',
      'Magikarp',
      'Marill',
      'Poochyena',
      'Zigzagoon',
      'Seedot',
      'Surskit',
      'Volbeat',
      'Illumise',
      'Roselia',
      'Corphish',
    ],
    id: 20,
    pokemon: null,
    location: 'Route 117',
    status: null,
  },
  {
    filter: [
      'Sandshrew',
      'Geodude',
      'Goldeen',
      'Magikarp',
      'Marill',
      'Surskit',
      'Trapinch',
      'Cacnea',
      'Barboach',
      'Baltoy',
    ],
    id: 21,
    pokemon: null,
    location: 'Route 111',
    status: null,
  },
  {
    filter: ['Machop', 'Marill', 'Numel'],
    id: 23,
    pokemon: null,
    location: 'Route 112',
    status: null,
  },
  {
    filter: ['Machop', 'Grimer', 'Koffing', 'Slugma', 'Numel', 'Torkoal'],
    id: 24,
    pokemon: null,
    location: 'Fiery Path',
    status: null,
  },
  {
    filter: ['Sandshrew', 'Slugma', 'Skarmory', 'Spinda'],
    id: 25,
    pokemon: null,
    location: 'Route 113',
    status: null,
  },
  {
    filter: [
      'Lombre',
      'Nuzleaf',
      'Surskit',
      'Swablu',
      'Zangoose',
      'Seviper',
      'Lotad',
      'Seedot',
      'Marill',
      'Azumarill',
      'Masquerain',
      'Goldeen',
      'Magikarp',
      'Barboach',
      'Geodude',
    ],
    id: 26,
    pokemon: null,
    location: 'Route 114',
    status: null,
  },
  {
    filter: [
      'Golbat',
      'Goldeen',
      'Magikarp',
      'Lunatone',
      'Solrock',
      'Barboach',
      'Whiscash',
      'Bagon',
    ],
    id: 28,
    pokemon: null,
    location: 'Meteor Falls',
    status: null,
  },
  {
    filter: ['Machop', 'Numel', 'Spoink'],
    id: 29,
    pokemon: null,
    location: 'Jagged Pass',
    status: null,
  },
  {
    filter: ['Togepi', 'Wynaut'],
    id: 30,
    pokemon: null,
    location: 'Lavaridge Town',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Magikarp',
      'Zigzagoon',
      'Linoone',
      'Wingull',
      'Pelipper',
      'Electrike',
      'Manectric',
      'Carvanha',
      'Sharpedo',
      'Kecleon',
    ],
    id: 31,
    pokemon: null,
    location: 'Route 118',
    status: null,
  },
  {
    filter: [
      'Oddish',
      'Tentacool',
      'Magikarp',
      'Zigzagoon',
      'Linoone',
      'Wingull',
      'Pelipper',
      'Carvanha',
      'Kecleon',
      'Tropius',
    ],
    id: 32,
    pokemon: null,
    location: 'Route 119',
    status: null,
  },
  {
    filter: ['Skitty'],
    id: 33,
    pokemon: null,
    location: 'Fortree City',
    status: null,
  },
  {
    filter: [
      'Oddish',
      'Goldeen',
      'Magikarp',
      'Marill',
      'Poochyena',
      'Mightyena',
      'Zigzagoon',
      'Linoone',
      'Seedot',
      'Surskit',
      'Barboach',
      'Kecleon',
      'Absol',
    ],
    id: 34,
    pokemon: null,
    location: 'Route 120',
    status: null,
  },
  {
    filter: [
      'Oddish',
      'Gloom',
      'Tentacool',
      'Magikarp',
      'Poochyena',
      'Mightyena',
      'Zigzagoon',
      'Linoone',
      'Wingull',
      'Pelipper',
      'Wailmer',
      'Kecleon',
      'Shuppet',
      'Duskull',
    ],
    id: 35,
    pokemon: null,
    location: 'Route 121',
    status: null,
  },
  {
    filter: [
      'Pikachu',
      'Gloom',
      'Psyduck',
      'Dodouo',
      'Girafarig',
      'Oddish',
      'Kakuna',
      'Pidgeotto',
      'Buneary',
      'Goldeen',
      'Magikarp',
      'Seaking',
      'Xatu',
      'Wobbuffet',
      'Rhyhorn',
      'Donphan',
      'Pinsir',
    ],
    id: 36,
    pokemon: null,
    location: 'Safari Zone',
    status: null,
  },
  {
    filter: ['Tentacool', 'Staryu', 'Magikarp', 'Wingull', 'Pelipper', 'Wailmer'],
    id: 37,
    pokemon: null,
    location: 'Lilycove City',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Sharpedo', 'Wailmer'],
    id: 38,
    pokemon: null,
    location: 'Route 122',
    status: null,
  },
  {
    filter: ['Shuppet', 'Duskull', 'Vulpix', 'Wingull', 'Meditite', 'Chimecho'],
    id: 39,
    pokemon: null,
    location: 'Mt. Pyre',
    status: null,
  },
  {
    filter: [
      'Oddish',
      'Gloom',
      'Tentacool',
      'Magikarp',
      'Poochyena',
      'Mightyena',
      'Zigzagoon',
      'Linoone',
      'Wingull',
      'Pelipper',
      'Wailmer',
      'Kecleon',
      'Shuppet',
      'Duskull',
    ],
    id: 40,
    pokemon: null,
    location: 'Route 123',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wailmer', 'Staryu', 'Electrode'],
    id: 41,
    pokemon: null,
    location: 'Team Magma/Aqua Hideout',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Sharpedo', 'Wailmer'],
    id: 42,
    pokemon: null,
    location: 'Route 124',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Sharpedo', 'Wailmer'],
    id: 44,
    pokemon: null,
    location: 'Mossdeep City',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Sharpedo', 'Wailmer'],
    id: 45,
    pokemon: null,
    location: 'Route 125',
    status: null,
  },
  {
    filter: ['Zubat', 'Golbat', 'Tentacool', 'Magikarp', 'Wailmer', 'Spheal'],
    id: 46,
    pokemon: null,
    location: 'Shoal Cave',
    status: null,
  },
  {
    filter: ['Zubat', 'Golbat', 'Tentacool', 'Magikarp', 'Wailmer', 'Spheal'],
    id: 47,
    pokemon: null,
    location: 'Route 127',
    status: null,
  },
  {
    filter: ['Zubat', 'Golbat', 'Tentacool', 'Magikarp', 'Wailmer', 'Spheal'],
    id: 48,
    pokemon: null,
    location: 'Route 128',
    status: null,
  },
  {
    filter: ['Zubat', 'Golbat', 'Tentacool', 'Magikarp', 'Wailmer'],
    id: 49,
    pokemon: null,
    location: 'Seafloor Cavern',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Sharpedo', 'Wailmer'],
    id: 50,
    pokemon: null,
    location: 'Route 126',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Gyarados'],
    id: 51,
    pokemon: null,
    location: 'Sootopolis City',
    status: null,
  },
  {
    filter: ['Zubat', 'Golbat', 'Sableye', 'Mawile', 'Kyogre', 'Groudon'],
    id: 52,
    pokemon: null,
    location: 'Cave of Origin',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Sharpedo', 'Wailmer', 'Wailord'],
    id: 53,
    pokemon: null,
    location: 'Route 129',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Sharpedo', 'Wailmer', 'Wynaut'],
    id: 54,
    pokemon: null,
    location: 'Route 130',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Sharpedo', 'Wailmer'],
    id: 56,
    pokemon: null,
    location: 'Route 131',
    status: null,
  },
  {
    filter: ['Golbat', 'Ariados', 'Mawile', 'Claydol', 'Sableye', 'Swablu', 'Deoxys', 'Rayquaza'],
    id: 57,
    pokemon: null,
    location: 'Sky Pillar',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Sharpedo', 'Wailmer'],
    id: 58,
    pokemon: null,
    location: 'Pacifidlog Town',
    status: null,
  },
  {
    filter: [
      'Venomoth',
      'Xatu',
      'Zebstrika',
      'Darmanitan',
      'Tangela',
      'Larvesta',
      'Persian',
      'Porygon',
      'Purugly',
      'Pelipper',
      'Absol',
      'Audino',
      'Graveler',
      'Binacle',
      'Ditto',
      'Munna',
      'Maractus',
    ],
    id: 59,
    pokemon: null,
    location: 'Mirage Island',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Wailmer'],
    id: 60,
    pokemon: null,
    location: 'Route 105',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Wailmer'],
    id: 61,
    pokemon: null,
    location: 'Route 108',
    status: null,
  },
  {
    filter: ['Tentacool', 'Tentacruel', 'Magikarp'],
    id: 62,
    pokemon: null,
    location: 'Abandoned Ship',
    status: null,
  },
  {
    filter: ['Tentacool', 'Magikarp', 'Wingull', 'Pelipper', 'Wailmer'],
    id: 63,
    pokemon: null,
    location: 'Route 109',
    status: null,
  },
  {
    filter: ['Tentacool', 'Horsea', 'Magikarp', 'Wingull', 'Pelipper', 'Sharpedo', 'Wailmer'],
    id: 64,
    pokemon: null,
    location: 'Route 132',
    status: null,
  },
  {
    filter: ['Tentacool', 'Horsea', 'Magikarp', 'Wingull', 'Pelipper', 'Sharpedo', 'Wailmer'],
    id: 65,
    pokemon: null,
    location: 'Route 133',
    status: null,
  },
  {
    filter: ['Tentacool', 'Horsea', 'Magikarp', 'Wingull', 'Pelipper', 'Sharpedo', 'Wailmer'],
    id: 66,
    pokemon: null,
    location: 'Route 134',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Golbat',
      'Loudred',
      'Makuhita',
      'Hariyama',
      'Aron',
      'Lairon',
      'Medicham',
      'Geodude',
      'Graveler',
      'Sableye',
      'Mawile',
      'Tentacool',
      'Wailmer',
      'Luvdisc',
      'Magikarp',
      'Barboach',
      'Whiscash',
    ],
    id: 68,
    pokemon: null,
    location: 'Victory Road',
    status: null,
  },
];

export default OR_AS;
