import type { TEncounter } from 'constants/types';

const OR_AS: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
    filterKey: 'oras-0',
  },
  {
    id: 1,
    pokemon: null,
    location: 'Littleroot Town',
    status: null,
    filterKey: 'oras-1',
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 101',
    status: null,
    filterKey: 'oras-2',
  },
  {
    id: 3,
    pokemon: null,
    location: 'Route 102',
    status: null,
    filterKey: 'oras-3',
  },
  {
    id: 4,
    pokemon: null,
    location: 'Route 103',
    status: null,
    filterKey: 'oras-4',
  },
  {
    id: 5,
    pokemon: null,
    location: 'Petalburg City',
    status: null,
    filterKey: 'oras-5',
  },
  {
    id: 6,
    pokemon: null,
    location: 'Route 104',
    status: null,
    filterKey: 'oras-6',
  },
  {
    id: 7,
    pokemon: null,
    location: 'Petalburg Woods',
    status: null,
    filterKey: 'oras-7',
  },
  {
    id: 8,
    pokemon: null,
    location: 'Rustboro City',
    status: null,
    filterKey: 'oras-8',
  },
  {
    id: 9,
    pokemon: null,
    location: 'Route 115',
    status: null,
    filterKey: 'oras-9',
  },
  {
    id: 10,
    pokemon: null,
    location: 'Route 116',
    status: null,
    filterKey: 'oras-10',
  },
  {
    id: 11,
    pokemon: null,
    location: 'Rusturf Tunnel',
    status: null,
    filterKey: 'oras-11',
  },
  {
    id: 12,
    pokemon: null,
    location: 'Dewford Town',
    status: null,
    filterKey: 'oras-12',
  },
  {
    id: 13,
    pokemon: null,
    location: 'Route 106',
    status: null,
    filterKey: 'oras-13',
  },
  {
    id: 14,
    pokemon: null,
    location: 'Granite Cave',
    status: null,
    filterKey: 'oras-14',
  },
  {
    id: 15,
    pokemon: null,
    location: 'Route 107',
    status: null,
    filterKey: 'oras-15',
  },
  {
    id: 16,
    pokemon: null,
    location: 'Slateport City',
    status: null,
    filterKey: 'oras-16',
  },
  {
    id: 17,
    pokemon: null,
    location: 'Route 110',
    status: null,
    filterKey: 'oras-17',
  },
  {
    id: 19,
    pokemon: null,
    location: 'New Mauville',
    status: null,
    filterKey: 'oras-19',
  },
  {
    id: 20,
    pokemon: null,
    location: 'Route 117',
    status: null,
    filterKey: 'oras-20',
  },
  {
    id: 21,
    pokemon: null,
    location: 'Route 111',
    status: null,
    filterKey: 'oras-21',
  },
  {
    id: 23,
    pokemon: null,
    location: 'Route 112',
    status: null,
    filterKey: 'oras-23',
  },
  {
    id: 24,
    pokemon: null,
    location: 'Fiery Path',
    status: null,
    filterKey: 'oras-24',
  },
  {
    id: 25,
    pokemon: null,
    location: 'Route 113',
    status: null,
    filterKey: 'oras-25',
  },
  {
    id: 26,
    pokemon: null,
    location: 'Route 114',
    status: null,
    filterKey: 'oras-26',
  },
  {
    id: 28,
    pokemon: null,
    location: 'Meteor Falls',
    status: null,
    filterKey: 'oras-28',
  },
  {
    id: 29,
    pokemon: null,
    location: 'Jagged Pass',
    status: null,
    filterKey: 'oras-29',
  },
  {
    id: 30,
    pokemon: null,
    location: 'Lavaridge Town',
    status: null,
    filterKey: 'oras-30',
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 118',
    status: null,
    filterKey: 'oras-31',
  },
  {
    id: 32,
    pokemon: null,
    location: 'Route 119',
    status: null,
    filterKey: 'oras-32',
  },
  {
    id: 33,
    pokemon: null,
    location: 'Fortree City',
    status: null,
    filterKey: 'oras-33',
  },
  {
    id: 34,
    pokemon: null,
    location: 'Route 120',
    status: null,
    filterKey: 'oras-34',
  },
  {
    id: 35,
    pokemon: null,
    location: 'Route 121',
    status: null,
    filterKey: 'oras-35',
  },
  {
    id: 36,
    pokemon: null,
    location: 'Safari Zone',
    status: null,
    filterKey: 'oras-36',
  },
  {
    id: 37,
    pokemon: null,
    location: 'Lilycove City',
    status: null,
    filterKey: 'oras-37',
  },
  {
    id: 38,
    pokemon: null,
    location: 'Route 122',
    status: null,
    filterKey: 'oras-38',
  },
  {
    id: 39,
    pokemon: null,
    location: 'Mt. Pyre',
    status: null,
    filterKey: 'oras-39',
  },
  {
    id: 40,
    pokemon: null,
    location: 'Route 123',
    status: null,
    filterKey: 'oras-40',
  },
  {
    id: 41,
    pokemon: null,
    location: 'Team Magma/Aqua Hideout',
    status: null,
    filterKey: 'oras-41',
  },
  {
    id: 42,
    pokemon: null,
    location: 'Route 124',
    status: null,
    filterKey: 'oras-42',
  },
  {
    id: 44,
    pokemon: null,
    location: 'Mossdeep City',
    status: null,
    filterKey: 'oras-44',
  },
  {
    id: 45,
    pokemon: null,
    location: 'Route 125',
    status: null,
    filterKey: 'oras-45',
  },
  {
    id: 46,
    pokemon: null,
    location: 'Shoal Cave',
    status: null,
    filterKey: 'oras-46',
  },
  {
    id: 47,
    pokemon: null,
    location: 'Route 127',
    status: null,
    filterKey: 'oras-47',
  },
  {
    id: 48,
    pokemon: null,
    location: 'Route 128',
    status: null,
    filterKey: 'oras-48',
  },
  {
    id: 49,
    pokemon: null,
    location: 'Seafloor Cavern',
    status: null,
    filterKey: 'oras-49',
  },
  {
    id: 50,
    pokemon: null,
    location: 'Route 126',
    status: null,
    filterKey: 'oras-50',
  },
  {
    id: 51,
    pokemon: null,
    location: 'Sootopolis City',
    status: null,
    filterKey: 'oras-51',
  },
  {
    id: 52,
    pokemon: null,
    location: 'Cave of Origin',
    status: null,
    filterKey: 'oras-52',
  },
  {
    id: 53,
    pokemon: null,
    location: 'Route 129',
    status: null,
    filterKey: 'oras-53',
  },
  {
    id: 54,
    pokemon: null,
    location: 'Route 130',
    status: null,
    filterKey: 'oras-54',
  },
  {
    id: 56,
    pokemon: null,
    location: 'Route 131',
    status: null,
    filterKey: 'oras-56',
  },
  {
    id: 57,
    pokemon: null,
    location: 'Sky Pillar',
    status: null,
    filterKey: 'oras-57',
  },
  {
    id: 58,
    pokemon: null,
    location: 'Pacifidlog Town',
    status: null,
    filterKey: 'oras-58',
  },
  {
    id: 59,
    pokemon: null,
    location: 'Mirage Island',
    status: null,
    filterKey: 'oras-59',
  },
  {
    id: 60,
    pokemon: null,
    location: 'Route 105',
    status: null,
    filterKey: 'oras-60',
  },
  {
    id: 61,
    pokemon: null,
    location: 'Route 108',
    status: null,
    filterKey: 'oras-61',
  },
  {
    id: 62,
    pokemon: null,
    location: 'Abandoned Ship',
    status: null,
    filterKey: 'oras-62',
  },
  {
    id: 63,
    pokemon: null,
    location: 'Route 109',
    status: null,
    filterKey: 'oras-63',
  },
  {
    id: 64,
    pokemon: null,
    location: 'Route 132',
    status: null,
    filterKey: 'oras-64',
  },
  {
    id: 65,
    pokemon: null,
    location: 'Route 133',
    status: null,
    filterKey: 'oras-65',
  },
  {
    id: 66,
    pokemon: null,
    location: 'Route 134',
    status: null,
    filterKey: 'oras-66',
  },
  {
    id: 68,
    pokemon: null,
    location: 'Victory Road',
    status: null,
    filterKey: 'oras-68',
  },
];

export default OR_AS;
