import { TEncounter } from 'constants/types';

const R_B_Y: TEncounter[] = [
  {
    filter: ['Bulbasaur', 'Charmander', 'Squirtle'],
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    filter: [
      'Bulbasaur',
      'Charmander',
      'Squirtle',
      'Pikachu',
      'Poliwag',
      'Tentacool',
      'Goldeen',
      'Staryu',
      'Magikarp',
    ],
    id: 1,
    pokemon: null,
    location: 'Pallet Town',
    status: null,
  },
  {
    filter: ['Pidgey', 'Rattata'],
    id: 2,
    pokemon: null,
    location: 'Route 1',
    status: null,
  },
  {
    filter: ['Poliwag', 'Tentacool', 'Goldeen', 'Magikarp'],
    id: 3,
    pokemon: null,
    location: 'Viridian City',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Spearow',
      'Nidoran-f',
      'Nidoran-m',
      'Mankey',
      'Poliwag',
      'Poliwhirl',
      'Goldeen',
      'Magikarp',
    ],
    id: 4,
    pokemon: null,
    location: 'Route 22',
    status: null,
  },
  {
    filter: ['Caterpie', 'Weedle', 'Pidgey', 'Rattata', 'Nidoran-f', 'Nidoran-m'],
    id: 5,
    pokemon: null,
    location: 'Route 2',
    status: null,
  },
  {
    filter: ['Caterpie', 'Metapod', 'Weedle', 'Kakuna', 'Pidgey', 'Pidgeotto', 'Pikachu'],
    id: 6,
    pokemon: null,
    location: 'Viridian Forest',
    status: null,
  },
  {
    id: 7,
    pokemon: null,
    location: 'Pewter City',
    status: null,
  },
  {
    filter: ['Pidgey', 'Rattata', 'Spearow', 'Sandshrew', 'Jigglypuff', 'Mankey'],
    id: 8,
    pokemon: null,
    location: 'Route 3',
    status: null,
  },
  {
    filter: ['Rattata', 'Spearow', 'Ekans', 'Sandshrew', 'Mankey'],
    id: 9,
    pokemon: null,
    location: 'Route 4',
    status: null,
  },
  {
    filter: ['Sandshrew', 'Clefairy', 'Zubat', 'Paras', 'Geodude'],
    id: 10,
    pokemon: null,
    location: 'Mt. Moon',
    status: null,
  },
  {
    filter: ['Bulbasaur', 'Psyduck', 'Poliwag', 'Krabby', 'Goldeen', 'Seaking', 'Magikarp'],
    id: 11,
    pokemon: null,
    location: 'Cerulean City',
    status: null,
  },
  {
    filter: [
      'Charmander',
      'Caterpie',
      'Metapod',
      'Weedle',
      'Kakuna',
      'Pidgey',
      'Pidgeotto',
      'Oddish',
      'Venonat',
      'Psyduck',
      'Poliwag',
      'Abra',
      'Bellsprout',
      'Krabby',
      'Goldeen',
      'Seaking',
      'Magikarp',
    ],
    id: 12,
    pokemon: null,
    location: 'Route 24',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Weedle',
      'Kakuna',
      'Pidgey',
      'Pidgeotto',
      'Oddish',
      'Venonat',
      'Psyduck',
      'Poliwag',
      'Abra',
      'Bellsprout',
      'Krabby',
      'Kingler',
      'Goldeen',
      'Magikarp',
    ],
    id: 13,
    pokemon: null,
    location: 'Route 25',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Pidgeotto',
      'Rattata',
      'Jigglypuff',
      'Oddish',
      'Meowth',
      'Mankey',
      'Abra',
      'Bellsprout',
    ],
    id: 14,
    pokemon: null,
    location: 'Route 5',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Pidgeotto',
      'Rattata',
      'Jigglypuff',
      'Oddish',
      'Meowth',
      'Psyduck',
      'Golduck',
      'Mankey',
      'Poliwag',
      'Abra',
      'Bellsprout',
      'Shellder',
      'Krabby',
      'Goldeen',
      'Magikarp',
    ],
    id: 15,
    pokemon: null,
    location: 'Route 6',
    status: null,
  },
  {
    filter: [
      'Squirtle',
      'Poliwag',
      'Tentacool',
      'Shellder',
      'Krabby',
      'Horsea',
      'Goldeen',
      'Magikarp',
    ],
    id: 16,
    pokemon: null,
    location: 'Vermillion City',
    status: null,
  },
  {
    filter: ['Poliwag', 'Tentacool', 'Shellder', 'Krabby', 'Goldeen', 'Staryu', 'Magikarp'],
    id: 17,
    pokemon: null,
    location: 'S.S. Anne',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Pidgeotto',
      'Rattata',
      'Raticate',
      'Spearow',
      'Ekans',
      'Sandshrew',
      'Poliwag',
      'Tentacool',
      'Shellder',
      'Drowzee',
      'Krabby',
      'Horsea',
      'Goldeen',
      'Magikarp',
    ],
    id: 18,
    pokemon: null,
    location: 'Route 11',
    status: null,
  },
  {
    filter: ['Diglett', 'Dugtrio'],
    id: 19,
    pokemon: null,
    location: "Diglett's Cave",
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Spearow',
      'Fearow',
      'Ekans',
      'Sandshrew',
      'Nidoran-f',
      'Nidorina',
      'Nidoran-m',
      'Nidorino',
    ],
    id: 20,
    pokemon: null,
    location: 'Route 9',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Spearow',
      'Ekans',
      'Sandshrew',
      'Nidoran-f',
      'Nidoran-m',
      'Poliwag',
      'Poliwhirl',
      'Machop',
      'Slowpoke',
      'Magnemite',
      'Krabby',
      'Kingler',
      'Voltorb',
      'Horsea',
      'Goldeen',
      'Magikarp',
    ],
    id: 21,
    pokemon: null,
    location: 'Route 10',
    status: null,
  },
  {
    filter: ['Zubat', 'Machop', 'Geodude', 'Onix'],
    id: 22,
    pokemon: null,
    location: 'Rock Tunnel',
    status: null,
  },
  {
    id: 23,
    pokemon: null,
    location: 'Lavendar Town',
    status: null,
  },
  {
    filter: ['Gastly', 'Haunter', 'Cubone'],
    id: 24,
    pokemon: null,
    location: 'Pokemon Tower',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Pidgeotto',
      'Oddish',
      'Gloom',
      'Venonat',
      'Poliwag',
      'Bellsprout',
      'Weepinbell',
      'Tentacool',
      'Slowpoke',
      'Slowbro',
      'Farfetchd',
      'Krabby',
      'Horsea',
      'Seadra',
      'Goldeen',
      'Magikarp',
      'Snorlax',
    ],
    id: 25,
    pokemon: null,
    location: 'Route 12',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Pidgeotto',
      'Rattata',
      'Ekans',
      'Sandshrew',
      'Vulpix',
      'Jigglypuff',
      'Meowth',
      'Mankey',
      'Growlithe',
      'Abra',
      'Kadabra',
    ],
    id: 26,
    pokemon: null,
    location: 'Route 8',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Pidgeotto',
      'Rattata',
      'Vulpix',
      'Jigglypuff',
      'Oddish',
      'Meowth',
      'Mankey',
      'Growlithe',
      'Abra',
      'Bellsprout',
    ],
    id: 27,
    pokemon: null,
    location: 'Route 7',
    status: null,
  },
  {
    filter: ['Poliwag', 'Poliwhirl', 'Slowpoke', 'Goldeen', 'Magikarp'],
    id: 28,
    pokemon: null,
    location: 'Celadon City',
    status: null,
  },
  {
    filter: ['Hitmonlee', 'Hitmonchan', 'Lapras'],
    id: 29,
    pokemon: null,
    location: 'Saffron City',
    status: null,
  },
  {
    id: 30,
    pokemon: null,
    location: 'Rocket Hideout',
    status: null,
  },
  {
    filter: ['Rattata', 'Raticate', 'Spearow', 'Fearow', 'Doduo', 'Snorlax'],
    id: 31,
    pokemon: null,
    location: 'Route 16',
    status: null,
  },
  {
    filter: [
      'Raticate',
      'Spearow',
      'Fearow',
      'Poliwag',
      'Tentacool',
      'Ponyta',
      'Doduo',
      'Dodrio',
      'Shellder',
      'Krabby',
      'Goldeen',
      'Magikarp',
    ],
    id: 32,
    pokemon: null,
    location: 'Route 17',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Spearow',
      'Fearow',
      'Poliwag',
      'Tentacool',
      'Doduo',
      'Shellder',
      'Krabby',
      'Goldeen',
      'Magikarp',
    ],
    id: 33,
    pokemon: null,
    location: 'Route 18',
    status: null,
  },
  {
    filter: ['Magikarp', 'Poliwag', 'Goldeen', 'Krabby', 'Seaking', 'Gyarados'],
    id: 34,
    pokemon: null,
    location: 'Fuschia City',
    status: null,
  },
  {
    filter: [
      'Nidoran-f',
      'Nidorina',
      'Nidoran-m',
      'Nidorino',
      'Paras',
      'Parasect',
      'Venonat',
      'Psyduck',
      'Poliwag',
      'Slowpoke',
      'Krabby',
      'Exeggcute',
      'Rhyhorn',
      'Chansey',
      'Tangela',
      'Goldeen',
      'Scyther',
      'Pinsir',
      'Magikarp',
      'Dratini',
      'Dragonair',
    ],
    id: 35,
    pokemon: null,
    location: 'Safari Zone',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Pidgeotto',
      'Oddish',
      'Gloom',
      'Venonat',
      'Venomoth',
      'Bellsprout',
      'Weepinbell',
      'Ditto',
    ],
    id: 36,
    pokemon: null,
    location: 'Route 15',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Pidgeotto',
      'Oddish',
      'Gloom',
      'Venonat',
      'Venomoth',
      'Bellsprout',
      'Weepinbell',
      'Ditto',
    ],
    id: 37,
    pokemon: null,
    location: 'Route 14',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Pidgeotto',
      'Oddish',
      'Gloom',
      'Venonat',
      'Poliwag',
      'Bellsprout',
      'Weepinbell',
      'Tentacool',
      'Slowpoke',
      'Slowbro',
      'Farfetchd',
      'Krabby',
      'Horsea',
      'Seadra',
      'Goldeen',
      'Magikarp',
      'Ditto',
    ],
    id: 38,
    pokemon: null,
    location: 'Route 13',
    status: null,
  },
  {
    filter: [
      'Pikachu',
      'Raichu',
      'Magnemite',
      'Magneton',
      'Grimer',
      'Muk',
      'Voltorb',
      'Electrode',
      'Electabuzz',
      'Zapdos',
    ],
    id: 39,
    pokemon: null,
    location: 'Power Plant',
    status: null,
  },
  {
    filter: [
      'Pikachu',
      'Raichu',
      'Magnemite',
      'Magneton',
      'Grimer',
      'Muk',
      'Voltorb',
      'Electrode',
      'Electabuzz',
      'Zapdos',
    ],
    id: 40,
    pokemon: null,
    location: 'Route 19',
    status: null,
  },
  {
    filter: [
      'Poliwag',
      'Tentacool',
      'Tentacruel',
      'Shellder',
      'Horsea',
      'Goldeen',
      'Staryu',
      'Magikarp',
    ],
    id: 41,
    pokemon: null,
    location: 'Route 20',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Golbat',
      'Psyduck',
      'Golduck',
      'Poliwag',
      'Tentacool',
      'Slowpoke',
      'Slowbro',
      'Seel',
      'Dewgong',
      'Shellder',
      'Krabby',
      'Kingler',
      'Horsea',
      'Seadra',
      'Goldeen',
      'Staryu',
      'Magikarp',
      'Articuno',
    ],
    id: 42,
    pokemon: null,
    location: 'Seafoam Islands',
    status: null,
  },
  {
    filter: ['Poliwag', 'Tentacool', 'Shellder', 'Horsea', 'Goldeen', 'Staryu', 'Magikarp'],
    id: 43,
    pokemon: null,
    location: 'Cinnabar Island',
    status: null,
  },
  {
    filter: [
      'Rattata',
      'Raticate',
      'Vulpix',
      'Growlithe',
      'Ponyta',
      'Grimer',
      'Muk',
      'Koffing',
      'Weezing',
    ],
    id: 44,
    pokemon: null,
    location: 'Pokemon Mansion',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Pidgeotto',
      'Rattata',
      'Raticate',
      'Poliwag',
      'Tentacool',
      'Tentacruel',
      'Shellder',
      'Tangela',
      'Horsea',
      'Goldeen',
      'Staryu',
      'Magikarp',
    ],
    id: 45,
    pokemon: null,
    location: 'Route 21',
    status: null,
  },
  {
    filter: [
      'Spearow',
      'Fearow',
      'Ekans',
      'Arbok',
      'Sandshrew',
      'Sandslash',
      'Nidorina',
      'Nidorino',
      'Mankey',
      'Primeape',
      'Poliwag',
      'Poliwhirl',
      'Slowbro',
      'Kingler',
      'Seadra',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Ditto',
    ],
    id: 46,
    pokemon: null,
    location: 'Route 23',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Golbat',
      'Machop',
      'Machoke',
      'Geodude',
      'Graveler',
      'Onix',
      'Marowak',
      'Moltres',
    ],
    id: 47,
    pokemon: null,
    location: 'Victory Road',
    status: null,
  },
  {
    filter: [
      'Arbok',
      'Raichu',
      'Sandslash',
      'Golbat',
      'Gloom',
      'Parasect',
      'Venomoth',
      'Poliwag',
      'Kadabra',
      'Weepinbell',
      'Graveler',
      'Slowbro',
      'Magneton',
      'Dodrio',
      'Hypno',
      'Kingler',
      'Seadra',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Ditto',
      'Mewtwo',
    ],
    id: 48,
    pokemon: null,
    location: 'Cerulean Cave',
    status: null,
  },
];

export default R_B_Y;
