import type { TEncounter } from 'constants/types';

const R_B_Y: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
    filterKey: 'rby-0',
  },
  {
    id: 1,
    pokemon: null,
    location: 'Pallet Town',
    status: null,
    filterKey: 'rby-1',
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 1',
    status: null,
    filterKey: 'rby-2',
  },
  {
    id: 3,
    pokemon: null,
    location: 'Viridian City',
    status: null,
    filterKey: 'rby-3',
  },
  {
    id: 4,
    pokemon: null,
    location: 'Route 22',
    status: null,
    filterKey: 'rby-4',
  },
  {
    id: 5,
    pokemon: null,
    location: 'Route 2',
    status: null,
    filterKey: 'rby-5',
  },
  {
    id: 6,
    pokemon: null,
    location: 'Viridian Forest',
    status: null,
    filterKey: 'rby-6',
  },
  {
    id: 7,
    pokemon: null,
    location: 'Pewter City',
    status: null,
    filterKey: 'rby-49',
  },
  {
    id: 8,
    pokemon: null,
    location: 'Route 3',
    status: null,
    filterKey: 'rby-8',
  },
  {
    id: 9,
    pokemon: null,
    location: 'Route 4',
    status: null,
    filterKey: 'rby-9',
  },
  {
    id: 10,
    pokemon: null,
    location: 'Mt. Moon',
    status: null,
    filterKey: 'rby-10',
  },
  {
    id: 11,
    pokemon: null,
    location: 'Cerulean City',
    status: null,
    filterKey: 'rby-11',
  },
  {
    id: 12,
    pokemon: null,
    location: 'Route 24',
    status: null,
    filterKey: 'rby-12',
  },
  {
    id: 13,
    pokemon: null,
    location: 'Route 25',
    status: null,
    filterKey: 'rby-13',
  },
  {
    id: 14,
    pokemon: null,
    location: 'Route 5',
    status: null,
    filterKey: 'rby-14',
  },
  {
    id: 15,
    pokemon: null,
    location: 'Route 6',
    status: null,
    filterKey: 'rby-15',
  },
  {
    id: 16,
    pokemon: null,
    location: 'Vermillion City',
    status: null,
    filterKey: 'rby-16',
  },
  {
    id: 17,
    pokemon: null,
    location: 'S.S. Anne',
    status: null,
    filterKey: 'rby-17',
  },
  {
    id: 18,
    pokemon: null,
    location: 'Route 11',
    status: null,
    filterKey: 'rby-18',
  },
  {
    id: 19,
    pokemon: null,
    location: "Diglett's Cave",
    status: null,
    filterKey: 'rby-19',
  },
  {
    id: 20,
    pokemon: null,
    location: 'Route 9',
    status: null,
    filterKey: 'rby-20',
  },
  {
    id: 21,
    pokemon: null,
    location: 'Route 10',
    status: null,
    filterKey: 'rby-21',
  },
  {
    id: 22,
    pokemon: null,
    location: 'Rock Tunnel',
    status: null,
    filterKey: 'rby-22',
  },
  {
    id: 24,
    pokemon: null,
    location: 'Pokemon Tower',
    status: null,
    filterKey: 'rby-24',
  },
  {
    id: 25,
    pokemon: null,
    location: 'Route 12',
    status: null,
    filterKey: 'rby-25',
  },
  {
    id: 26,
    pokemon: null,
    location: 'Route 8',
    status: null,
    filterKey: 'rby-26',
  },
  {
    id: 27,
    pokemon: null,
    location: 'Route 7',
    status: null,
    filterKey: 'rby-27',
  },
  {
    id: 28,
    pokemon: null,
    location: 'Celadon City',
    status: null,
    filterKey: 'rby-28',
  },
  {
    id: 29,
    pokemon: null,
    location: 'Saffron City',
    status: null,
    filterKey: 'rby-29',
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 16',
    status: null,
    filterKey: 'rby-31',
  },
  {
    id: 32,
    pokemon: null,
    location: 'Route 17',
    status: null,
    filterKey: 'rby-32',
  },
  {
    id: 33,
    pokemon: null,
    location: 'Route 18',
    status: null,
    filterKey: 'rby-33',
  },
  {
    id: 34,
    pokemon: null,
    location: 'Fuschia City',
    status: null,
    filterKey: 'rby-34',
  },
  {
    id: 35,
    pokemon: null,
    location: 'Safari Zone',
    status: null,
    filterKey: 'rby-35',
  },
  {
    id: 36,
    pokemon: null,
    location: 'Route 15',
    status: null,
    filterKey: 'rby-36',
  },
  {
    id: 37,
    pokemon: null,
    location: 'Route 14',
    status: null,
    filterKey: 'rby-37',
  },
  {
    id: 38,
    pokemon: null,
    location: 'Route 13',
    status: null,
    filterKey: 'rby-38',
  },
  {
    id: 39,
    pokemon: null,
    location: 'Power Plant',
    status: null,
    filterKey: 'rby-39',
  },
  {
    id: 40,
    pokemon: null,
    location: 'Route 19',
    status: null,
    filterKey: 'rby-40',
  },
  {
    id: 41,
    pokemon: null,
    location: 'Route 20',
    status: null,
    filterKey: 'rby-41',
  },
  {
    id: 42,
    pokemon: null,
    location: 'Seafoam Islands',
    status: null,
    filterKey: 'rby-42',
  },
  {
    id: 43,
    pokemon: null,
    location: 'Cinnabar Island',
    status: null,
    filterKey: 'rby-43',
  },
  {
    id: 44,
    pokemon: null,
    location: 'Pokemon Mansion',
    status: null,
    filterKey: 'rby-44',
  },
  {
    id: 45,
    pokemon: null,
    location: 'Route 21',
    status: null,
    filterKey: 'rby-45',
  },
  {
    id: 46,
    pokemon: null,
    location: 'Route 23',
    status: null,
    filterKey: 'rby-46',
  },
  {
    id: 47,
    pokemon: null,
    location: 'Victory Road',
    status: null,
    filterKey: 'rby-47',
  },
  {
    id: 48,
    pokemon: null,
    location: 'Cerulean Cave',
    status: null,
    filterKey: 'rby-48',
  },
];

export default R_B_Y;
