import type { TEncounter } from 'constants/types';

const R_S_E: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
    filterKey: 'rse-0',
  },
  {
    id: 1,
    pokemon: null,
    location: 'Littleroot Town',
    status: null,
    filterKey: 'rse-1',
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 101',
    status: null,
    filterKey: 'rse-2',
  },
  {
    id: 3,
    pokemon: null,
    location: 'Route 102',
    status: null,
    filterKey: 'rse-3',
  },
  {
    id: 4,
    pokemon: null,
    location: 'Route 103',
    status: null,
    filterKey: 'rse-4',
  },
  {
    id: 5,
    pokemon: null,
    location: 'Petalburg City',
    status: null,
    filterKey: 'rse-5',
  },
  {
    id: 6,
    pokemon: null,
    location: 'Route 104',
    status: null,
    filterKey: 'rse-6',
  },
  {
    id: 7,
    pokemon: null,
    location: 'Petalburg Woods',
    status: null,
    filterKey: 'rse-7',
  },
  {
    id: 8,
    pokemon: null,
    location: 'Rustboro City',
    status: null,
    filterKey: 'rse-8',
  },
  {
    id: 9,
    pokemon: null,
    location: 'Route 115',
    status: null,
    filterKey: 'rse-9',
  },
  {
    id: 10,
    pokemon: null,
    location: 'Route 116',
    status: null,
    filterKey: 'rse-10',
  },
  {
    id: 11,
    pokemon: null,
    location: 'Rusturf Tunnel',
    status: null,
    filterKey: 'rse-11',
  },
  {
    id: 12,
    pokemon: null,
    location: 'Dewford Town',
    status: null,
    filterKey: 'rse-12',
  },
  {
    id: 13,
    pokemon: null,
    location: 'Route 106',
    status: null,
    filterKey: 'rse-13',
  },
  {
    id: 14,
    pokemon: null,
    location: 'Granite Cave',
    status: null,
    filterKey: 'rse-14',
  },
  {
    id: 15,
    pokemon: null,
    location: 'Route 107',
    status: null,
    filterKey: 'rse-15',
  },
  {
    id: 16,
    pokemon: null,
    location: 'Slateport City',
    status: null,
    filterKey: 'rse-16',
  },
  {
    id: 17,
    pokemon: null,
    location: 'Route 110',
    status: null,
    filterKey: 'rse-17',
  },
  {
    id: 18,
    pokemon: null,
    location: 'Altering Cave',
    status: null,
    filterKey: 'rse-18',
  },
  {
    id: 19,
    pokemon: null,
    location: 'New Mauville',
    status: null,
    filterKey: 'rse-19',
  },
  {
    id: 20,
    pokemon: null,
    location: 'Route 117',
    status: null,
    filterKey: 'rse-20',
  },
  {
    id: 21,
    pokemon: null,
    location: 'Route 111',
    status: null,
    filterKey: 'rse-21',
  },
  {
    id: 22,
    pokemon: null,
    location: 'Mirage Tower',
    status: null,
    filterKey: 'rse-22',
  },
  {
    id: 23,
    pokemon: null,
    location: 'Route 112',
    status: null,
    filterKey: 'rse-23',
  },
  {
    id: 24,
    pokemon: null,
    location: 'Fiery Path',
    status: null,
    filterKey: 'rse-24',
  },
  {
    id: 25,
    pokemon: null,
    location: 'Route 113',
    status: null,
    filterKey: 'rse-25',
  },
  {
    id: 26,
    pokemon: null,
    location: 'Route 114',
    status: null,
    filterKey: 'rse-26',
  },
  {
    id: 27,
    pokemon: null,
    location: 'Desert Underpass',
    status: null,
    filterKey: 'rse-27',
  },
  {
    id: 28,
    pokemon: null,
    location: 'Meteor Falls',
    status: null,
    filterKey: 'rse-28',
  },
  {
    id: 29,
    pokemon: null,
    location: 'Jagged Pass',
    status: null,
    filterKey: 'rse-29',
  },
  {
    id: 30,
    pokemon: null,
    location: 'Lavaridge Town',
    status: null,
    filterKey: 'rse-30',
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 118',
    status: null,
    filterKey: 'rse-31',
  },
  {
    id: 32,
    pokemon: null,
    location: 'Route 119',
    status: null,
    filterKey: 'rse-32',
  },
  {
    id: 33,
    pokemon: null,
    location: 'Fortree City',
    status: null,
    filterKey: 'rse-33',
  },
  {
    id: 34,
    pokemon: null,
    location: 'Route 120',
    status: null,
    filterKey: 'rse-34',
  },
  {
    id: 35,
    pokemon: null,
    location: 'Route 121',
    status: null,
    filterKey: 'rse-35',
  },
  {
    id: 36,
    pokemon: null,
    location: 'Safari Zone',
    status: null,
    filterKey: 'rse-36',
  },
  {
    id: 37,
    pokemon: null,
    location: 'Lilycove City',
    status: null,
    filterKey: 'rse-37',
  },
  {
    id: 38,
    pokemon: null,
    location: 'Route 122',
    status: null,
    filterKey: 'rse-38',
  },
  {
    id: 39,
    pokemon: null,
    location: 'Mt. Pyre',
    status: null,
    filterKey: 'rse-39',
  },
  {
    id: 40,
    pokemon: null,
    location: 'Route 123',
    status: null,
    filterKey: 'rse-40',
  },
  {
    id: 41,
    pokemon: null,
    location: 'Team Magma Hideout',
    status: null,
    filterKey: 'rse-41',
  },
  {
    id: 69,
    pokemon: null,
    location: 'Team Aqua Hideout',
    status: null,
    filterKey: 'rse-69',
  },
  {
    id: 42,
    pokemon: null,
    location: 'Route 124',
    status: null,
    filterKey: 'rse-42',
  },
  {
    id: 44,
    pokemon: null,
    location: 'Mossdeep City',
    status: null,
    filterKey: 'rse-44',
  },
  {
    id: 45,
    pokemon: null,
    location: 'Route 125',
    status: null,
    filterKey: 'rse-45',
  },
  {
    id: 46,
    pokemon: null,
    location: 'Shoal Cave',
    status: null,
    filterKey: 'rse-46',
  },
  {
    id: 47,
    pokemon: null,
    location: 'Route 127',
    status: null,
    filterKey: 'rse-47',
  },
  {
    id: 48,
    pokemon: null,
    location: 'Route 128',
    status: null,
    filterKey: 'rse-48',
  },
  {
    id: 49,
    pokemon: null,
    location: 'Seafloor Cavern',
    status: null,
    filterKey: 'rse-49',
  },
  {
    id: 50,
    pokemon: null,
    location: 'Route 126',
    status: null,
    filterKey: 'rse-50',
  },
  {
    id: 51,
    pokemon: null,
    location: 'Sootopolis City',
    status: null,
    filterKey: 'rse-51',
  },
  {
    id: 52,
    pokemon: null,
    location: 'Cave of Origin',
    status: null,
    filterKey: 'rse-52',
  },
  {
    id: 53,
    pokemon: null,
    location: 'Route 129',
    status: null,
    filterKey: 'rse-53',
  },
  {
    id: 54,
    pokemon: null,
    location: 'Route 130',
    status: null,
    filterKey: 'rse-54',
  },
  {
    id: 56,
    pokemon: null,
    location: 'Route 131',
    status: null,
    filterKey: 'rse-56',
  },
  {
    id: 57,
    pokemon: null,
    location: 'Sky Pillar',
    status: null,
    filterKey: 'rse-57',
  },
  {
    id: 58,
    pokemon: null,
    location: 'Pacifidlog Town',
    status: null,
    filterKey: 'rse-58',
  },
  {
    id: 59,
    pokemon: null,
    location: 'Mirage Island',
    status: null,
    filterKey: 'rse-59',
  },
  {
    id: 60,
    pokemon: null,
    location: 'Route 105',
    status: null,
    filterKey: 'rse-60',
  },
  {
    id: 61,
    pokemon: null,
    location: 'Route 108',
    status: null,
    filterKey: 'rse-61',
  },
  {
    id: 62,
    pokemon: null,
    location: 'Abandoned Ship',
    status: null,
    filterKey: 'rse-62',
  },
  {
    id: 63,
    pokemon: null,
    location: 'Route 109',
    status: null,
    filterKey: 'rse-63',
  },
  {
    id: 64,
    pokemon: null,
    location: 'Route 132',
    status: null,
    filterKey: 'rse-64',
  },
  {
    id: 65,
    pokemon: null,
    location: 'Route 133',
    status: null,
    filterKey: 'rse-65',
  },
  {
    id: 66,
    pokemon: null,
    location: 'Route 134',
    status: null,
    filterKey: 'rse-66',
  },
  {
    id: 68,
    pokemon: null,
    location: 'Victory Road',
    status: null,
    filterKey: 'rse-68',
  },
];

export default R_S_E;
