import { TEncounter } from 'constants/types';

const R_S_E: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    id: 1,
    pokemon: null,
    location: 'Littleroot Town',
    status: null,
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 101',
    status: null,
  },
  {
    id: 3,
    pokemon: null,
    location: 'Route 102',
    status: null,
  },
  {
    id: 4,
    pokemon: null,
    location: 'Route 103',
    status: null,
  },
  {
    id: 5,
    pokemon: null,
    location: 'Petalburg City',
    status: null,
  },
  {
    id: 6,
    pokemon: null,
    location: 'Route 104',
    status: null,
  },
  {
    id: 7,
    pokemon: null,
    location: 'Petalburg Woods',
    status: null,
  },
  {
    id: 8,
    pokemon: null,
    location: 'Rustboro City',
    status: null,
  },
  {
    id: 9,
    pokemon: null,
    location: 'Route 115',
    status: null,
  },
  {
    id: 10,
    pokemon: null,
    location: 'Route 116',
    status: null,
  },
  {
    id: 11,
    pokemon: null,
    location: 'Rusturf Tunnel',
    status: null,
  },
  {
    id: 12,
    pokemon: null,
    location: 'Dewford Town',
    status: null,
  },
  {
    id: 13,
    pokemon: null,
    location: 'Route 106',
    status: null,
  },
  {
    id: 14,
    pokemon: null,
    location: 'Granite Cave',
    status: null,
  },
  {
    id: 15,
    pokemon: null,
    location: 'Route 107',
    status: null,
  },
  {
    id: 16,
    pokemon: null,
    location: 'Slateport City',
    status: null,
  },
  {
    id: 17,
    pokemon: null,
    location: 'Route 110',
    status: null,
  },
  {
    id: 18,
    pokemon: null,
    location: 'Altering Cave',
    status: null,
  },
  {
    id: 19,
    pokemon: null,
    location: 'New Mauville',
    status: null,
  },
  {
    id: 20,
    pokemon: null,
    location: 'Route 117',
    status: null,
  },
  {
    id: 21,
    pokemon: null,
    location: 'Route 111',
    status: null,
  },
  {
    id: 22,
    pokemon: null,
    location: 'Mirage Tower',
    status: null,
  },
  {
    id: 23,
    pokemon: null,
    location: 'Route 112',
    status: null,
  },
  {
    id: 24,
    pokemon: null,
    location: 'Fiery Path',
    status: null,
  },
  {
    id: 25,
    pokemon: null,
    location: 'Route 113',
    status: null,
  },
  {
    id: 26,
    pokemon: null,
    location: 'Route 114',
    status: null,
  },
  {
    id: 27,
    pokemon: null,
    location: 'Desert Underpass',
    status: null,
  },
  {
    id: 28,
    pokemon: null,
    location: 'Meteor Falls',
    status: null,
  },
  {
    id: 29,
    pokemon: null,
    location: 'Jagged Pass',
    status: null,
  },
  {
    id: 30,
    pokemon: null,
    location: 'Lavaridge Town',
    status: null,
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 118',
    status: null,
  },
  {
    id: 32,
    pokemon: null,
    location: 'Route 119',
    status: null,
  },
  {
    id: 33,
    pokemon: null,
    location: 'Fortree City',
    status: null,
  },
  {
    id: 34,
    pokemon: null,
    location: 'Route 120',
    status: null,
  },
  {
    id: 35,
    pokemon: null,
    location: 'Route 121',
    status: null,
  },
  {
    id: 36,
    pokemon: null,
    location: 'Safari Zone',
    status: null,
  },
  {
    id: 37,
    pokemon: null,
    location: 'Lilycove City',
    status: null,
  },
  {
    id: 38,
    pokemon: null,
    location: 'Route 122',
    status: null,
  },
  {
    id: 39,
    pokemon: null,
    location: 'Mt. Pyre',
    status: null,
  },
  {
    id: 40,
    pokemon: null,
    location: 'Route 123',
    status: null,
  },
  {
    id: 41,
    pokemon: null,
    location: 'Team Magma Hideout',
    status: null,
  },
  {
    id: 42,
    pokemon: null,
    location: 'Route 124',
    status: null,
  },
  {
    id: 44,
    pokemon: null,
    location: 'Mossdeep City',
    status: null,
  },
  {
    id: 45,
    pokemon: null,
    location: 'Route 125',
    status: null,
  },
  {
    id: 46,
    pokemon: null,
    location: 'Shoal Cave',
    status: null,
  },
  {
    id: 47,
    pokemon: null,
    location: 'Route 127',
    status: null,
  },
  {
    id: 48,
    pokemon: null,
    location: 'Route 128',
    status: null,
  },
  {
    id: 49,
    pokemon: null,
    location: 'Seafloor Cavern',
    status: null,
  },
  {
    id: 50,
    pokemon: null,
    location: 'Route 126',
    status: null,
  },
  {
    id: 51,
    pokemon: null,
    location: 'Sootopolis City',
    status: null,
  },
  {
    id: 52,
    pokemon: null,
    location: 'Cave of Origin',
    status: null,
  },
  {
    id: 53,
    pokemon: null,
    location: 'Route 129',
    status: null,
  },
  {
    id: 54,
    pokemon: null,
    location: 'Route 130',
    status: null,
  },
  {
    id: 55,
    pokemon: null,
    location: 'Route 130',
    status: null,
  },
  {
    id: 56,
    pokemon: null,
    location: 'Route 131',
    status: null,
  },
  {
    id: 57,
    pokemon: null,
    location: 'Sky Pillar',
    status: null,
  },
  {
    id: 58,
    pokemon: null,
    location: 'Pacifidlog Town',
    status: null,
  },
  {
    id: 59,
    pokemon: null,
    location: 'Mirage Island',
    status: null,
  },
  {
    id: 60,
    pokemon: null,
    location: 'Route 105',
    status: null,
  },
  {
    id: 61,
    pokemon: null,
    location: 'Mirage 108',
    status: null,
  },
  {
    id: 62,
    pokemon: null,
    location: 'Abandoned Ship',
    status: null,
  },
  {
    id: 63,
    pokemon: null,
    location: 'Route 109',
    status: null,
  },
  {
    id: 64,
    pokemon: null,
    location: 'Route 132',
    status: null,
  },
  {
    id: 65,
    pokemon: null,
    location: 'Route 133',
    status: null,
  },
  {
    id: 66,
    pokemon: null,
    location: 'Route 134',
    status: null,
  },
  {
    id: 67,
    pokemon: null,
    location: 'Evergrande City',
    status: null,
  },
  {
    id: 68,
    pokemon: null,
    location: 'Victory Road',
    status: null,
  },
];

export default R_S_E;
