import { TEncounter } from 'constants/types';

const S_M: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    id: 1,
    pokemon: null,
    location: "Hau'oli Outskirts",
    status: null,
  },
  {
    id: 2,
    pokemon: null,
    location: 'Iki Town',
    status: null,
  },
  {
    id: 3,
    pokemon: null,
    location: 'Route 1',
    status: null,
  },
  {
    id: 4,
    pokemon: null,
    location: "Route 1 (Trainer's School)",
    status: null,
  },
  {
    id: 5,
    pokemon: null,
    location: "Hau'oli City",
    status: null,
  },
  {
    id: 6,
    pokemon: null,
    location: 'Route 2',
    status: null,
  },
  {
    id: 7,
    pokemon: null,
    location: 'Berry Fields',
    status: null,
  },
  {
    id: 8,
    pokemon: null,
    location: 'Verdant Cavern',
    status: null,
  },
  {
    id: 9,
    pokemon: null,
    location: "Hau'oli Cemetery",
    status: null,
  },
  {
    id: 10,
    pokemon: null,
    location: 'Route 3',
    status: null,
  },
  {
    id: 11,
    pokemon: null,
    location: 'Melemele Meadow',
    status: null,
  },
  {
    id: 12,
    pokemon: null,
    location: 'Seaward Cave',
    status: null,
  },
  {
    id: 13,
    pokemon: null,
    location: "Kala'e Bay",
    status: null,
  },
  {
    id: 14,
    pokemon: null,
    location: 'Ten Carat Hill',
    status: null,
  },
  {
    id: 15,
    pokemon: null,
    location: 'Route 4',
    status: null,
  },
  {
    id: 16,
    pokemon: null,
    location: 'Paniola Town',
    status: null,
  },
  {
    id: 17,
    pokemon: null,
    location: 'Paniola Ranch',
    status: null,
  },
  {
    id: 18,
    pokemon: null,
    location: 'Route 5',
    status: null,
  },
  {
    id: 19,
    pokemon: null,
    location: 'Route 10',
    status: null,
  },
  {
    id: 21,
    pokemon: null,
    location: 'Brooklet Hill',
    status: null,
  },
  {
    id: 32,
    pokemon: null,
    location: 'Melemele Sea',
    status: null,
  },
  {
    id: 22,
    pokemon: null,
    location: 'Route 6',
    status: null,
  },
  {
    id: 23,
    pokemon: null,
    location: 'Route 7',
    status: null,
  },
  {
    id: 24,
    pokemon: null,
    location: 'Wela Volcano Park',
    status: null,
  },
  {
    id: 25,
    pokemon: null,
    location: 'Route 8',
    status: null,
  },
  {
    id: 26,
    pokemon: null,
    location: 'Lush Jungle',
    status: null,
  },
  {
    id: 27,
    pokemon: null,
    location: 'Digletts Tunnel',
    status: null,
  },
  {
    id: 28,
    pokemon: null,
    location: 'Route 9',
    status: null,
  },
  {
    id: 29,
    pokemon: null,
    location: 'Konikoni City',
    status: null,
  },
  {
    id: 30,
    pokemon: null,
    location: 'Memorial Hill',
    status: null,
  },
  {
    id: 31,
    pokemon: null,
    location: 'Akala Outskirts',
    status: null,
  },
  {
    id: 33,
    pokemon: null,
    location: 'Hano Beach',
    status: null,
  },
  {
    id: 34,
    pokemon: null,
    location: 'Malie City',
    status: null,
  },
  {
    id: 35,
    pokemon: null,
    location: 'Malie Garden',
    status: null,
  },
  {
    id: 36,
    pokemon: null,
    location: 'Mt. Hokulani',
    status: null,
  },
  {
    id: 37,
    pokemon: null,
    location: 'Route 11',
    status: null,
  },
  {
    id: 38,
    pokemon: null,
    location: 'Route 12',
    status: null,
  },
  {
    id: 39,
    pokemon: null,
    location: 'Secluded Shore',
    status: null,
  },
  {
    id: 40,
    pokemon: null,
    location: 'Blush Mountain',
    status: null,
  },
  {
    id: 41,
    pokemon: null,
    location: 'Route 13',
    status: null,
  },
  {
    id: 42,
    pokemon: null,
    location: 'Tapu Village',
    status: null,
  },
  {
    id: 43,
    pokemon: null,
    location: 'Route 14',
    status: null,
  },
  {
    id: 44,
    pokemon: null,
    location: 'Route 15',
    status: null,
  },
  {
    id: 45,
    pokemon: null,
    location: 'Thrify Megamart',
    status: null,
  },
  {
    id: 46,
    pokemon: null,
    location: 'Route 16',
    status: null,
  },
  {
    id: 47,
    pokemon: null,
    location: "Ula'ula Meadow",
    status: null,
  },
  {
    id: 48,
    pokemon: null,
    location: 'Route 17',
    status: null,
  },
  {
    id: 49,
    pokemon: null,
    location: 'Seafolk Village',
    status: null,
  },
  {
    id: 50,
    pokemon: null,
    location: 'Poni Wilds',
    status: null,
  },
  {
    id: 51,
    pokemon: null,
    location: 'Ancient Poni Path',
    status: null,
  },
  {
    id: 52,
    pokemon: null,
    location: 'Poni Breaker Coast',
    status: null,
  },
  {
    id: 53,
    pokemon: null,
    location: 'Exeggutor Island',
    status: null,
  },
  {
    id: 54,
    pokemon: null,
    location: 'Vast Poni Canyon',
    status: null,
  },
  {
    id: 55,
    pokemon: null,
    location: 'Altar of the Sunne/Moone',
    status: null,
  },
  {
    id: 56,
    pokemon: null,
    location: 'Mount Lanakila',
    status: null,
  },
];

export default S_M;
