import { TEncounter } from 'constants/types';

const S_M: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
    filterKey: 'sm-0',
  },
  {
    id: 1,
    pokemon: null,
    location: "Hau'oli Outskirts",
    status: null,
    filterKey: 'sm-1',
  },
  {
    id: 2,
    pokemon: null,
    location: 'Iki Town',
    status: null,
    filterKey: 'sm-2',
  },
  {
    id: 3,
    pokemon: null,
    location: 'Route 1',
    status: null,
    filterKey: 'sm-3',
  },
  {
    id: 4,
    pokemon: null,
    location: "Route 1 (Trainer's School)",
    status: null,
    filterKey: 'sm-4',
  },
  {
    id: 5,
    pokemon: null,
    location: "Hau'oli City",
    status: null,
    filterKey: 'sm-5',
  },
  {
    id: 6,
    pokemon: null,
    location: 'Route 2',
    status: null,
    filterKey: 'sm-6',
  },
  {
    id: 8,
    pokemon: null,
    location: 'Verdant Cavern',
    status: null,
    filterKey: 'sm-8',
  },
  {
    id: 9,
    pokemon: null,
    location: "Hau'oli Cemetery",
    status: null,
    filterKey: 'sm-9',
  },
  {
    id: 10,
    pokemon: null,
    location: 'Route 3',
    status: null,
    filterKey: 'sm-10',
  },
  {
    id: 11,
    pokemon: null,
    location: 'Melemele Meadow',
    status: null,
    filterKey: 'sm-11',
  },
  {
    id: 12,
    pokemon: null,
    location: 'Seaward Cave',
    status: null,
    filterKey: 'sm-12',
  },
  {
    id: 13,
    pokemon: null,
    location: "Kala'e Bay",
    status: null,
    filterKey: 'sm-13',
  },
  {
    id: 14,
    pokemon: null,
    location: 'Ten Carat Hill',
    status: null,
    filterKey: 'sm-14',
  },
  {
    id: 15,
    pokemon: null,
    location: 'Route 4',
    status: null,
    filterKey: 'sm-15',
  },
  {
    id: 16,
    pokemon: null,
    location: 'Paniola Town',
    status: null,
    filterKey: 'sm-16',
  },
  {
    id: 17,
    pokemon: null,
    location: 'Paniola Ranch',
    status: null,
    filterKey: 'sm-17',
  },
  {
    id: 18,
    pokemon: null,
    location: 'Route 5',
    status: null,
    filterKey: 'sm-18',
  },
  {
    id: 19,
    pokemon: null,
    location: 'Route 10',
    status: null,
    filterKey: 'sm-19',
  },
  {
    id: 21,
    pokemon: null,
    location: 'Brooklet Hill',
    status: null,
    filterKey: 'sm-21',
  },
  {
    id: 32,
    pokemon: null,
    location: 'Melemele Sea',
    status: null,
    filterKey: 'sm-32',
  },
  {
    id: 22,
    pokemon: null,
    location: 'Route 6',
    status: null,
    filterKey: 'sm-22',
  },
  {
    id: 23,
    pokemon: null,
    location: 'Route 7',
    status: null,
    filterKey: 'sm-23',
  },
  {
    id: 24,
    pokemon: null,
    location: 'Wela Volcano Park',
    status: null,
    filterKey: 'sm-24',
  },
  {
    id: 25,
    pokemon: null,
    location: 'Route 8',
    status: null,
    filterKey: 'sm-25',
  },
  {
    id: 26,
    pokemon: null,
    location: 'Lush Jungle',
    status: null,
    filterKey: 'sm-26',
  },
  {
    id: 27,
    pokemon: null,
    location: 'Digletts Tunnel',
    status: null,
    filterKey: 'sm-27',
  },
  {
    id: 28,
    pokemon: null,
    location: 'Route 9',
    status: null,
    filterKey: 'sm-28',
  },
  {
    id: 29,
    pokemon: null,
    location: 'Konikoni City',
    status: null,
    filterKey: 'sm-29',
  },
  {
    id: 30,
    pokemon: null,
    location: 'Memorial Hill',
    status: null,
    filterKey: 'sm-30',
  },
  {
    id: 31,
    pokemon: null,
    location: 'Akala Outskirts',
    status: null,
    filterKey: 'sm-31',
  },
  {
    id: 33,
    pokemon: null,
    location: 'Hano Beach',
    status: null,
    filterKey: 'sm-33',
  },
  {
    id: 34,
    pokemon: null,
    location: 'Malie City',
    status: null,
    filterKey: 'sm-34',
  },
  {
    id: 35,
    pokemon: null,
    location: 'Malie Garden',
    status: null,
    filterKey: 'sm-35',
  },
  {
    id: 36,
    pokemon: null,
    location: 'Mt. Hokulani',
    status: null,
    filterKey: 'sm-36',
  },
  {
    id: 37,
    pokemon: null,
    location: 'Route 11',
    status: null,
    filterKey: 'sm-37',
  },
  {
    id: 38,
    pokemon: null,
    location: 'Route 12',
    status: null,
    filterKey: 'sm-38',
  },
  {
    id: 39,
    pokemon: null,
    location: 'Secluded Shore',
    status: null,
    filterKey: 'sm-39',
  },
  {
    id: 40,
    pokemon: null,
    location: 'Blush Mountain',
    status: null,
    filterKey: 'sm-40',
  },
  {
    id: 41,
    pokemon: null,
    location: 'Route 13',
    status: null,
    filterKey: 'sm-41',
  },
  {
    id: 42,
    pokemon: null,
    location: 'Tapu Village',
    status: null,
    filterKey: 'sm-42',
  },
  {
    id: 43,
    pokemon: null,
    location: 'Route 14',
    status: null,
    filterKey: 'sm-43',
  },
  {
    id: 44,
    pokemon: null,
    location: 'Route 15',
    status: null,
    filterKey: 'sm-44',
  },
  {
    id: 45,
    pokemon: null,
    location: 'Thrify Megamart',
    status: null,
    filterKey: 'sm-45',
  },
  {
    id: 46,
    pokemon: null,
    location: 'Route 16',
    status: null,
    filterKey: 'sm-46',
  },
  {
    id: 47,
    pokemon: null,
    location: "Ula'ula Meadow",
    status: null,
    filterKey: 'sm-47',
  },
  {
    id: 48,
    pokemon: null,
    location: 'Route 17',
    status: null,
    filterKey: 'sm-48',
  },
  {
    id: 49,
    pokemon: null,
    location: 'Seafolk Village',
    status: null,
    filterKey: 'sm-49',
  },
  {
    id: 50,
    pokemon: null,
    location: 'Poni Wilds',
    status: null,
    filterKey: 'sm-50',
  },
  {
    id: 51,
    pokemon: null,
    location: 'Ancient Poni Path',
    status: null,
    filterKey: 'sm-51',
  },
  {
    id: 52,
    pokemon: null,
    location: 'Poni Breaker Coast',
    status: null,
    filterKey: 'sm-52',
  },
  {
    id: 53,
    pokemon: null,
    location: 'Exeggutor Island',
    status: null,
    filterKey: 'sm-53',
  },
  {
    id: 54,
    pokemon: null,
    location: 'Vast Poni Canyon',
    status: null,
    filterKey: 'sm-54',
  },
  {
    id: 55,
    pokemon: null,
    location: 'Altar of the Sunne/Moone',
    status: null,
    filterKey: 'sm-55',
  },
  {
    id: 56,
    pokemon: null,
    location: 'Mount Lanakila',
    status: null,
    filterKey: 'sm-56',
  },
];

export default S_M;
