import { TEncounter } from 'constants/types';

const S_M: TEncounter[] = [
  {
    filter: ['Rowlet', 'Litten', 'Popplio'],
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    filter: ['Rattata (Alolan)', 'Slowpoke', 'Wingull', 'Yungoos', 'Tentacool', 'Finneon'],
    id: 1,
    pokemon: null,
    location: "Hau'oli Outskirts",
    status: null,
  },
  {
    filter: ['Rowlet', 'Litten', 'Popplio'],
    id: 2,
    pokemon: null,
    location: 'Iki Town',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Rattata (Alolan)',
      'Ledyba',
      'Spinark',
      'Pikipek',
      'Yungoos',
      'Pichu',
      'Pikachu',
      'Happiny',
      'Grubbin',
      'Metapod',
      'Bonsly',
      'Sudowoodo',
      'Munchlax',
      'Snorlax',
    ],
    id: 3,
    pokemon: null,
    location: 'Route 1',
    status: null,
  },
  {
    filter: ['Meowth (Alolan)', 'Magnemite', 'Grimer (Alolan)'],
    id: 4,
    pokemon: null,
    location: "Route 1 (Trainer's School)",
    status: null,
  },
  {
    filter: [
      'Rattata (Alolan)',
      'Abra',
      'Magnemite',
      'Grimer (Alolan)',
      'Pichu',
      'Pikachu',
      'Happiny',
      'Wingull',
      'Yungoos',
      'Klink',
      'Tentacool',
      'Finneon',
    ],
    id: 5,
    pokemon: null,
    location: "Hau'oli City",
    status: null,
  },
  {
    filter: [
      'Rattata (Alolan)',
      'Meowth (Alolan)',
      'Abra',
      'Drowzee',
      'Smeargle',
      'Yungoos',
      'Spearow',
      'Growlithe',
      'Cutiefly',
      'Makuhita',
      'Crabrawler',
      'Machop',
      'Chikorita',
    ],
    id: 6,
    pokemon: null,
    location: 'Route 2',
    status: null,
  },
  {
    filter: ['Zubat', 'Diglett (Alolan)', 'Rattata (Alolan)', 'Yungoos', 'Pheromosa'],
    id: 8,
    pokemon: null,
    location: 'Verdant Cavern',
    status: null,
  },
  {
    filter: ['Zubat', 'Gastly', 'Misdreavus', 'Drifloon', 'Litwick'],
    id: 9,
    pokemon: null,
    location: "Hau'oli Cemetery",
    status: null,
  },
  {
    filter: [
      'Rattata (Alolan)',
      'Spearow',
      'Mankey',
      'Delibird',
      'Yungoos',
      'Cutiefly',
      'Bagon',
      'Salamence',
      'Rufflet',
      'Vullaby',
      'Crabrawler',
      'Cyndaquil',
    ],
    id: 10,
    pokemon: null,
    location: 'Route 3',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Cottonee',
      'Petilil',
      'Oricorio',
      'Cutiefly',
      'Buzzwole',
    ],
    id: 11,
    pokemon: null,
    location: 'Melemele Meadow',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Diglett (Alolan)',
      'Psyduck',
      'Magikarp',
      'Gyarados',
      'Barboach',
      'Whiscash',
      'Totodile',
    ],
    id: 12,
    pokemon: null,
    location: 'Seaward Cave',
    status: null,
  },
  {
    filter: [
      'Rattata (Alolan)',
      'Slowpoke',
      'Slowbro',
      'Wingull',
      'Bagon',
      'Shelgon',
      'Yungoos',
      'Tentacool',
      'Finneon',
      'Shellder',
      'Magikarp',
      'Gyarados',
      'Wishiwashi',
      'Horsea',
    ],
    id: 13,
    pokemon: null,
    location: "Kala'e Bay",
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Diglett (Alolan)',
      'Roggenrola',
      'Carbink',
      'Sableye',
      'Psyduck',
      'Deino',
      'Machop',
      'Spinda',
      'Carbink',
      'Rockruff',
      'Necrozma',
    ],
    id: 14,
    pokemon: null,
    location: 'Ten Carat Hill',
    status: null,
  },
  {
    filter: [
      'Rattata (Alolan)',
      'Eevee',
      'Espeon',
      'Umbreon',
      'Igglybuff',
      'Jigglypuff',
      'Happiny',
      'Lillipup',
      'Pikipek',
      'Yungoos',
      'Grubbin',
      'Mudbray',
      'Crabrawler',
      'Venipede',
    ],
    id: 15,
    pokemon: null,
    location: 'Route 4',
    status: null,
  },
  {
    filter: ['Magikarp', 'Barboach', 'Gyarados', 'Whiscash'],
    id: 16,
    pokemon: null,
    location: 'Paniola Town',
    status: null,
  },
  {
    filter: ['Tauros', 'Miltank', 'Lillipup', 'Mudbray', 'Eevee'],
    id: 17,
    pokemon: null,
    location: 'Paniola Ranch',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Lillipup',
      'Pikipek',
      'Grubbin',
      'Fomantis',
      'Crabrawler',
      'Bounsweet',
      'Bellsprout',
      'Bonsly',
      'Sudowoodo',
      'Happiny',
      'Trumbeak',
      'Diglett (Alolan)',
    ],
    id: 18,
    pokemon: null,
    location: 'Route 5',
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Fearow',
      'Ledian',
      'Ariados',
      'Skarmory',
      'Pancham',
      'Pangoro',
      'Gumshoos',
      'Crabrawler',
      'Staravia',
    ],
    id: 19,
    pokemon: null,
    location: 'Route 10',
    status: null,
  },
  {
    filter: [
      'Paras',
      'Psyduck',
      'Poliwag',
      'Wingull',
      'Surskit',
      'Lillipup',
      'Dewpider',
      'Morelull',
      'Goldeen',
      'Seaking',
      'Gyarados',
      'Magikarp',
      'Feebas',
      'Wishiwashi',
      'Marill',
      'Tentacool',
      'Finneon',
      'Alomomola',
    ],
    id: 21,
    pokemon: null,
    location: 'Brooklet Hill',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Wingull',
      'Finneon',
      'Magikarp',
      'Gyarados',
      'Corsola',
      'Mareanie',
      'Luvdisc',
      'Wishiwashi',
    ],
    id: 32,
    pokemon: null,
    location: 'Melemele Sea',
    status: null,
  },
  {
    filter: [
      'Rattata (Alolan)',
      'Eevee',
      'Espeon',
      'Umbreon',
      'Igglybuff',
      'Jigglypuff',
      'Happiny',
      'Lillipup',
      'Pikipek',
      'Yungoos',
      'Grubbin',
      'Mudbray',
      'Oricorio',
      'Gothita',
    ],
    id: 22,
    pokemon: null,
    location: 'Route 6',
    status: null,
  },
  {
    filter: [
      'Diglett (Alolan)',
      'Tentacool',
      'Wingull',
      'Finneon',
      'Pyukumuku',
      'Staryu',
      'Starmie',
      'Magikarp',
      'Gyarados',
      'Wishiwashi',
      'Spheal',
    ],
    id: 23,
    pokemon: null,
    location: 'Route 7',
    status: null,
  },
  {
    filter: ['Cubone', 'Kangaskhan', 'Magby', 'Magmar', 'Fletchling', 'Salandit', 'Nihilego'],
    id: 24,
    pokemon: null,
    location: 'Wela Volcano Park',
    status: null,
  },
  {
    filter: [
      'Rattata (Alolan)',
      'Fletchinder',
      'Trumbeak',
      'Pikipek',
      'Yungoos',
      'Salandit',
      'Stufful',
      'Crabrawler',
      'Wimpod',
      'Tentacool',
      'Wingull',
      'Finneon',
      'Magikarp',
      'Gyarados',
      'Chinchou',
      'Wishiwashi',
      'Luxio',
      'Cranidos',
      'Shieldon',
      'Tirtouga',
      'Archen',
    ],
    id: 25,
    pokemon: null,
    location: 'Route 8',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Paras',
      'Bonsly',
      'Sudowoodo',
      'Happiny',
      'Trumbeak',
      'Fomantis',
      'Morelull',
      'Comfey',
      'Oranguru',
      'Passimian',
      'Goomy',
      'Castform',
      'Bounsweet',
      'Zubat',
      'Diglett (Alolan)',
    ],
    id: 26,
    pokemon: null,
    location: 'Lush Jungle',
    status: null,
  },
  {
    filter: ['Zubat', 'Diglett (Alolan)'],
    id: 27,
    pokemon: null,
    location: 'Digletts Tunnel',
    status: null,
  },
  {
    filter: ['Magikarp', 'Gyarados', 'Corsola', 'Mareanie', 'Luvdisc', 'Wishiwashi'],
    id: 28,
    pokemon: null,
    location: 'Route 9',
    status: null,
  },
  {
    filter: ['Poliwhirl'],
    id: 29,
    pokemon: null,
    location: 'Konikoni City',
    status: null,
  },
  {
    filter: ['Zubat', 'Gastly', 'Phantump'],
    id: 30,
    pokemon: null,
    location: 'Memorial Hill',
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Wingull',
      'Nosepass',
      'Gumshoos',
      'Stufful',
      'Magikarp',
      'Gyarados',
      'Chinchou',
      'Wishiwashi',
      'Honedge',
    ],
    id: 31,
    pokemon: null,
    location: 'Akala Outskirts',
    status: null,
  },
  {
    filter: ['Staryu', 'Sandygast', 'Tentacool', 'Wingull', 'Finneon', 'Pyukumuku'],
    id: 33,
    pokemon: null,
    location: 'Hano Beach',
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Magnemite',
      'Grimer (Alolan)',
      'Trubbish',
      'Garbodor',
      'Gumshoos',
    ],
    id: 34,
    pokemon: null,
    location: 'Malie City',
    status: null,
  },
  {
    filter: [
      'Mewoth (Alolan)',
      'Psyduck',
      'Poliwag',
      'Ledian',
      'Ariados',
      'Masquerain',
      'Cottonee',
      'Petilil',
      'Araquanid',
      'Poliwhirl',
      'Poliwrath',
      'Politoed',
      'Castform',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Gyarados',
    ],
    id: 35,
    pokemon: null,
    location: 'Malie Garden',
    status: null,
  },
  {
    filter: [
      'Fearow',
      'Ditto',
      'Cleffa',
      'Clefairy',
      'Chansey',
      'Skarmory',
      'Beldum',
      'Minior',
      'Axew',
    ],
    id: 36,
    pokemon: null,
    location: 'Mt. Hokulani',
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Paras',
      'Ledian',
      'Ariados',
      'Pancham',
      'Pangoro',
      'Trumbeak',
      'Gumshoos',
      'Morelull',
      'Komala',
      'Vigoroth',
    ],
    id: 37,
    pokemon: null,
    location: 'Route 11',
    status: null,
  },
  {
    filter: ['Geodude (Alolan)', 'Elekid', 'Electabuzz', 'Chansey', 'Torkoal', 'Mudbray'],
    id: 38,
    pokemon: null,
    location: 'Route 12',
    status: null,
  },
  {
    filter: [
      'Finneon',
      'Tentacool',
      'Pelipper',
      'Magikarp',
      'Wishiwashi',
      'Bruxish',
      'Gyarados',
      'Crabrawler',
    ],
    id: 39,
    pokemon: null,
    location: 'Secluded Shore',
    status: null,
  },
  {
    filter: [
      'Geodude (Alolan)',
      'Elekid',
      'Electabuzz',
      'Chansey',
      'Torkoal',
      'Charjabug',
      'Mudbray',
      'Turtonator',
      'Togedemaru',
      'Rhyhorn',
    ],
    id: 40,
    pokemon: null,
    location: 'Blush Mountain',
    status: null,
  },
  {
    filter: ['Magikarp', 'Gyarados', 'Wishiwashi', 'Bruxish'],
    id: 41,
    pokemon: null,
    location: 'Route 13',
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Sandshrew (Alolan)',
      'Vulpix (Alolan)',
      'Pelipper',
      'Absol',
      'Snorunt',
      'Gumshoos',
      'Vanillite',
      'Castform',
      'Graveler (Alolan)',
      'Swinub',
    ],
    id: 42,
    pokemon: null,
    location: 'Tapu Village',
    status: null,
  },
  {
    filter: ['Magikarp', 'Gyarados', 'Pelipper', 'Finneon', 'Wishiwashi', 'Bruxish'],
    id: 43,
    pokemon: null,
    location: 'Route 14',
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Slowpoke',
      'Pelipper',
      'Gumshoos',
      'Tentacool',
      'Finneon',
      'Magikarp',
      'Gyarados',
      'Wishiwashi',
      'Bruxish',
    ],
    id: 44,
    pokemon: null,
    location: 'Route 15',
    status: null,
  },
  {
    filter: ['Golbat', 'Haunter', 'Gengar', 'Klefki', 'Mimikyu'],
    id: 45,
    pokemon: null,
    location: 'Thrify Megamart',
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Slowpoke',
      'Pelipper',
      'Gumshoos',
      'Crabrawler',
      'Zygarde',
      'Duosion',
    ],
    id: 46,
    pokemon: null,
    location: 'Route 16',
    status: null,
  },
  {
    filter: ['Ledian', 'Ariados', 'Cottonee', 'Petilil', 'Oricorio', 'Ribombee', 'Roselia'],
    id: 47,
    pokemon: null,
    location: "Ula'ula Meadow",
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Fearow',
      'Ledian',
      'Ariados',
      'Pancham',
      'Pangoro',
      'Gumshoos',
      'Graveler (Alolan)',
      'Skarmory',
      'Castform',
      'Goomy',
      'Crabrawler',
    ],
    id: 48,
    pokemon: null,
    location: 'Route 17',
    status: null,
  },
  {
    filter: ['Magikarp', 'Gyarados', 'Wailmer', 'Wailord', 'Dhelmise', 'Aerodactyl', 'Steenee'],
    id: 49,
    pokemon: null,
    location: 'Seafolk Village',
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Exeggcute',
      'Granbull',
      'Pelipper',
      'Gastrodon',
      'Gumshoos',
      'Crabrawler',
      'Wimpod',
      'Tentacruel',
      'Lumineon',
      'Lapras',
      'Wailmer',
      'Wailord',
      'Relicanth',
      'Samurott',
    ],
    id: 50,
    pokemon: null,
    location: 'Poni Wilds',
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Exeggcute',
      'Granbull',
      'Pelipper',
      'Gastrodon',
      'Gumshoos',
      'Emboar',
    ],
    id: 51,
    pokemon: null,
    location: 'Ancient Poni Path',
    status: null,
  },
  {
    filter: ['Wimpod', 'Magikarp', 'Gyarados', 'Wailmer', 'Wailord', 'Sharpedo'],
    id: 52,
    pokemon: null,
    location: 'Poni Breaker Coast',
    status: null,
  },
  {
    filter: [
      'Exeggcute',
      'Exeggutor (Alolan)',
      'Pelipper',
      'Gastrodon',
      'Sliggoo',
      'Castform',
      'Serperior',
    ],
    id: 53,
    pokemon: null,
    location: 'Exeggutor Island',
    status: null,
  },
  {
    filter: [
      'Machoke',
      'Murkrow',
      'Skarmory',
      'Boldore',
      'Carbink',
      'Lycanroc',
      'Jangmo-o',
      'Konmmo-o',
      'Hakamo-o',
      'Golbat',
      'Dugtrio (Alolan)',
      'Golduck',
      'Magikarp',
      'Gyarados',
      'Dratini',
      'Dragonair',
      'Barboach',
      'Whiscash',
    ],
    id: 54,
    pokemon: null,
    location: 'Vast Poni Canyon',
    status: null,
  },
  {
    filter: ['Solgaleo', 'Lunala'],
    id: 55,
    pokemon: null,
    location: 'Altar of the Sunne/Moone',
    status: null,
  },
  {
    filter: [
      'Sandshrew (Alolan)',
      'Vulpix (Alolan)',
      'Sneasel',
      'Absol',
      'Snorunt',
      'Glalie',
      'Vanillish',
      'Castform',
      'Golbat',
      'Drampa',
    ],
    id: 56,
    pokemon: null,
    location: 'Mount Lanakila',
    status: null,
  },
];

export default S_M;
