import { TEncounter } from 'constants/types';

const SW_SH: TEncounter[] = [
  {
    filter: ['Grookey', 'Scorbunny', 'Sobble'],
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    filter: [
      'Hoothoot',
      'Grubbin',
      'Skwovet',
      'Rookidee',
      'Blipbug',
      'Butterfree',
      'Weezing (Galarian)',
      'Munna',
      'Stunfisk (Galarian)',
      'Corviknight',
      'Orbeetle',
      'Magikarp',
      'Barboach',
      'Whiscash',
    ],
    id: 1,
    pokemon: null,
    location: 'Slumbering Weald',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Hoothoot',
      'Grubbin',
      'Skwovet',
      'Blipbug',
      'Nickit',
      'Wooloo',
      'Rookidee',
    ],
    id: 2,
    pokemon: null,
    location: 'Route 1',
    status: null,
  },
  {
    filter: ['Slowpoke (Galarian)'],
    id: 3,
    pokemon: null,
    location: 'Wedgehurst',
    status: null,
  },
  {
    filter: [
      'Hoothoot',
      'Lotad',
      'Seedot',
      'Purrloin',
      'Rookidee',
      'Blipbug',
      'Magikarp',
      'Chewtle',
      'Arrokuda',
      'Zigzagoon (Galarian)',
      'Skwovet',
      'Nickit',
      'Yamper',
      'Feebas',
      'Magikarp',
      'Gyarados',
      'Barrskewda',
      'Lapras',
      'Drednaw',
      'Obstagoon',
    ],
    id: 4,
    pokemon: null,
    location: 'Route 2',
    status: null,
  },
  {
    filter: [
      'Metapod',
      'Vulpix',
      'Oddish',
      'Growlithe',
      'Natu',
      'Swinub',
      'Delibird',
      'Lotad',
      'Nuzleaf',
      'Wingull',
      'Electrike',
      'Baltoy',
      'Snorunt',
      'Budew',
      'Munna',
      'Dwebble',
      'Minccino',
      'Vanillite',
      'Joltik',
      'Golett',
      'Bunnelby',
      'Mudbray',
      'Bounsweet',
      'Cherubi',
      'Skowvet',
      'Tyrogue',
      'Ralts',
      'Combee',
      'Pancham',
      'Diglett',
      'Roggenrola',
      'Butterfree',
      'Pidove',
      'Onix',
      'Pelipper',
      'Kirilia',
      'Manectric',
      'Vespiquen',
      'Diggersby',
      'Ninjask',
      'Pikachu',
      'Roselia',
      'Mime Jr.',
      'Piloswine',
      'Gardevoir',
      'Crustle',
      'Pangoro',
      'Haunter',
      'Mudsdale',
    ],
    id: 5,
    pokemon: null,
    location: 'Wild Area: Rolling Fields',
    status: null,
  },
  {
    filter: [
      'Vulpix',
      'Growlithe',
      'Lotad',
      'Seedot',
      'Ralts',
      'Baltoy',
      'Snorunt',
      'Budew',
      'Stunky',
      'Snover',
      'Purrloin',
      'Tympole',
      'Vanillite',
      'Joltik',
      'Klink',
      'Golett',
      'Bunnelby',
      'Grubbin',
      'Mudbray',
      'Stufful',
      'Bounsweet',
      'Cherubi',
      'Skwovet',
      'Oddish',
      'Hoothoot',
      'Tyrogue',
      'Lombre',
      'Nuzleaf',
      'Ralts',
      'Electrike',
      'Orbeetle',
      'Vileplume',
      'Claydol',
      'Seimsitoad',
      'Vanillish',
      'Bewear',
      'Ludicolo',
      'Shiftry',
      'Pangoro',
    ],
    id: 6,
    pokemon: null,
    location: 'Wild Area: Dappled Grove',
    status: null,
  },
  {
    filter: [
      'Vulpix',
      'Growlithe',
      'Krabby',
      'Natu',
      'Wooper',
      'Delibird',
      'Tyrogue',
      'Wingull',
      'Ralts',
      'Nincada',
      'Electrike',
      'Baltoy',
      'Snorunt',
      'Tympole',
      'Vanillite',
      'Joltik',
      'Klink',
      'Bunnelby',
      'Pancham',
      'Mudbray',
      'Bounsweet',
      'Goldeen',
      'Magikarp',
      'Remoraid',
      'Wishiwashi',
      'Lotad',
      'Seedot',
      'Budew',
      'Purrloin',
      'Dwebble',
      'Shellder',
      'Chinchou',
      'Frillish',
      'Kingler',
      'Pelipper',
      'Palpitoad',
      'Diggersby',
      'Quagsire',
      'Drednaw',
      'Seaking',
      'Vanilluxe',
      'Jellicent',
      'Gyarados',
      'Grappoloct',
      'Cloyster',
      'Lanturn',
      'Lapras',
    ],
    id: 7,
    pokemon: null,
    location: 'Wild Area: West Lake Axewell',
    status: null,
  },
  {
    filter: [
      'Vulpix',
      'Oddish',
      'Growlithe',
      'Onix',
      'Wingull',
      'Electrike',
      'Baltoy',
      'Snorunt',
      'Budew',
      'Snover',
      'Purrloin',
      'Munna',
      'Pidove',
      'Dwebble',
      'Minccino',
      'Vanillite',
      'Joltik',
      'Bunnelby',
      'Grubbin',
      'Mudbray',
      'Stufful',
      'Shellder',
      'Goldeen',
      'Magikarp',
      'Wishiwashi',
      'Pancham',
      'Stufful',
      'Bounsweet',
      'Butterfree',
      'Vanillite',
      'Frillish',
      'Chinchou',
      'Xatu',
      'Pelipper',
      'Weezing (Galarian)',
      'Piloswine',
      'Bronzong',
      'Garbodor',
      'Mudsdale',
      'Gyarados',
      'Seaking',
      'Vanilluxe',
      'Jellicent',
      'Lanturn',
      'Cloyster',
    ],
    id: 8,
    pokemon: null,
    location: 'WildArea: East Lake Axewell',
    status: null,
  },
  {
    filter: [
      'Machop',
      'Gastly',
      'Natu',
      'Delibird',
      'Ralts',
      'Baltoy',
      'Snorunt',
      'Stunky',
      'Snover',
      'Pidove',
      'Tympole',
      'Dwebble',
      'Joltik',
      'Diggersby',
      'Grubbin',
      'Mudbray',
      'Stufful',
      'Cherubi',
      'Skwovet',
      'Magikarp',
      'Barboach',
      'Basculin',
      'Vulpix',
      'Gloom',
      'Growlithe',
      'Drifloon',
      'Palpitoad',
      'Vanillite',
      'Klink',
      'Golett',
      'Bunnelby',
      'Frillish',
      'Goldeen',
      'Corviknight',
      'Boltund',
      'Drifblim',
      'Skuntank',
      'Lucario',
      'Seismitoad',
      'Vanillish',
      'Xatu',
      'Liepard',
      'Gyarados',
      'Lapras',
      'Seaking',
      'Whiscash',
      'Vanilluxe',
    ],
    id: 9,
    pokemon: null,
    location: 'Wild Area: North Lake Miloch',
    status: null,
  },
  {
    filter: [
      'Vulpix',
      'Growlithe',
      'Machop',
      'Natu',
      'Wooper',
      'Tyrogue',
      'Wingull',
      'Ralts',
      'Nincada',
      'Electrike',
      'Roselia',
      'Corphish',
      'Baltoy',
      'Snorunt',
      'Snover',
      'Tympole',
      'Vanillite',
      'Joltik',
      'Klink',
      'Magikarp',
      'Remoraid',
      'Barboach',
      'Pyukumuku',
      'Tyrogue',
      'Stunky',
      'Bronzor',
      'Dwebble',
      'Krabby',
      'Delibird',
      'Lombre',
      'Nuzleaf',
      'Drifloon',
      'Mudbray',
      'Goldeen',
      'Galavantula',
      'Machoke',
      'Thievul',
      'Skuntank',
      'Palpitoad',
      'Crustle',
      'Kingler',
      'Drifblim',
      'Crawdaunt',
      'Pelipper',
      'Whiscash',
      'Vanilluxe',
      'Seaking',
      'Lanturn',
      'Jellicent',
      'Gyarados',
      'Milotic',
      'Octillery',
    ],
    id: 10,
    pokemon: null,
    location: 'Wild Area: South Lake Miloch',
    status: null,
  },
  {
    filter: [
      'Vulpix',
      'Growlithe',
      'Machop',
      'Gastly',
      'Wingull',
      'Electrike',
      'Duskull',
      'Snorunt',
      'Drifloon',
      'Snover',
      'Purrloin',
      'Pidove',
      'Tympole',
      'Dwebble',
      'Golett',
      'Grubbin',
      'Bounsweet',
      'Skwovet',
      'Oddish',
      'Shuckle',
      'Delibird',
      'Ralts',
      'Woobat',
      'Noibat',
      'Corviknight',
      'Haunter',
      'Drifblim',
      'Dusclops',
      'Glalie',
      'Golurk',
    ],
    id: 11,
    pokemon: null,
    location: 'Wild Area: Watchtower Ruins',
    status: null,
  },
  {
    filter: [
      'Machoke',
      'Haunter',
      'Onix',
      'Xatu',
      'Quagsire',
      'Swinub',
      'Delibird',
      'Lombre',
      'Nuzleaf',
      'Manectric',
      'Crawdaunt',
      'Bronzor',
      'Liepard',
      'Tranquill',
      'Dwebble',
      'Diggersby',
      'Mudsdale',
      'Bewear',
      'Cherubi',
      'Greedent',
      'Shellder',
      'Cloyster',
      'Gyarados',
      'Pyukumuku',
      'Machop',
      'Vulpix',
      'Growlithe',
      'Gastly',
      'Natu',
      'Wooper',
      'Tyrogue',
      'Duskull',
      'Munna',
      'Snover',
      'Palpitoad',
      'Golett',
      'Mudbray',
      'Stufful',
      'Steelix',
      'Rhydon',
      'Bronzong',
      'Abomasnow',
      'Golurk',
      'Bisharp',
      'Musharna',
      'Galvantula',
      'Vikavolt',
    ],
    id: 12,
    pokemon: null,
    location: "Wild Area: Giant's Seat",
    status: null,
  },
  {
    filter: [
      'Vulpix',
      'Gloom',
      'Growlithe',
      'Delibird',
      'Pelipper',
      'Manectric',
      'Roselia',
      'Crawdaunt',
      'Baltoy',
      'Snover',
      'Liepard',
      'Munna',
      'Unfezant',
      'Crustle',
      'Vanillish',
      'Klink',
      'Diggersby',
      'Charjabug',
      'Mudsdale',
      'Bewear',
      'Steenee',
      'Cherubi',
      'Greedent',
      'Magikarp',
      'Gyarados',
      'Octillery',
      'Wishiwashi',
      'Machoke',
      'Kingler',
      'Claydol',
      'Drifblim',
      'Bronzong',
      'Seismitoad',
      'Axew',
      'Abomasnow',
      'Haxorus',
    ],
    id: 36,
    pokemon: null,
    location: "Wild Area: Axew's Eye",
    status: null,
  },
  {
    filter: ['Magikarp', 'Barboach', 'Chewtle', 'Skwovet'],
    id: 13,
    pokemon: null,
    location: 'Motostoke',
    status: null,
  },
  {
    filter: [
      'Machop',
      'Klink',
      'Pancham',
      'Mudbray',
      'Rookidee',
      'Sizzlipede',
      'Cherubi',
      'Skwovet',
      'Vulpix',
      'Growlithe',
      'Tyrogue',
      'Zigzagoon (Galarian)',
      'Stunky',
      'Trubbish',
      'Gossifleur',
      'Rolycoly',
      'Corvisquire',
    ],
    id: 14,
    pokemon: null,
    location: 'Route 3',
    status: null,
  },
  {
    filter: ['Diglett', 'Roggenrola', 'Woobat', 'Drilbur', 'Timburr', 'Rolycoly', 'Carkol'],
    id: 15,
    pokemon: null,
    location: 'Galar Mine',
    status: null,
  },
  {
    filter: [
      'Meowth (Galarian)',
      'Budew',
      'Joltik',
      'Ferroseed',
      'Cutiefly',
      'Wooloo',
      'Milcery',
      'Skwovet',
      'Goldeen',
      'Magikarp',
      'Chewtle',
      'Pikachu',
      'Eevee',
      'Electrike',
      'Pumpkaboo',
      'Yamper',
      'Diglett',
    ],
    id: 16,
    pokemon: null,
    location: 'Route 4',
    status: null,
  },
  {
    filter: [
      'Lombre',
      'Nuzleaf',
      'Nincada',
      'Espurr',
      'Spritzee',
      'Swirlix',
      'Dewpider',
      'Dottler',
      'Applin',
      'Goldeen',
      'Magikarp',
      'Chewtle',
      'Skwovet',
      "Farfetch'd (Galarian)",
      'Wobbuffet',
      'Drifloon',
      'Minccino',
      'Stufful',
      'Eldegoss',
      'Toxel',
    ],
    id: 17,
    pokemon: null,
    location: 'Route 5',
    status: null,
  },
  {
    filter: ['Chinchou', 'Basculin', 'Wishiwashi', 'Chewtle', 'Arrokuda', 'Cottonee'],
    id: 18,
    pokemon: null,
    location: 'Hulbury',
    status: null,
  },
  {
    filter: [
      'Shuckle',
      'Shellos',
      'Croagunk',
      'Scraggy',
      'Binacle',
      'Noibat',
      'Wimpod',
      'Chewtle',
      'Barboach',
      'Corphish',
      'Stunfisk (Galarian)',
      'Gastrodon',
      'Drednaw',
    ],
    id: 19,
    pokemon: null,
    location: 'Galar Mine No. 2',
    status: null,
  },
  {
    filter: [
      'Croagunk',
      'Roggenrola',
      'Scraggy',
      'Pawniard',
      'Chewtle',
      'Impidimp',
      'Koffing',
      'Noctowl',
      'Sudowoodo',
      'Throh',
      'Sawk',
      'Salandit',
      'Hatenna',
    ],
    id: 21,
    pokemon: null,
    location: 'Motostoke Outskirts',
    status: null,
  },
  {
    filter: ['Vulpix', 'Litwick', 'Sizzlipede'],
    id: 22,
    pokemon: null,
    location: 'Motostoke Stadium',
    status: null,
  },
  {
    filter: [
      'Onix',
      'Rhyhorn',
      'Noctowl',
      'Sneasel',
      'Shellos',
      'Skorupi',
      'Sigilyph',
      'Vanillite',
      'Karrablast',
      'Ferroseed',
      'Elgyem',
      'Litwick',
      'Shelmet',
      'Pawniard',
      'Espurr',
      'Binacle',
      'Wimpod',
      'Corvisquire',
      'Eldegoss',
      'Dubwool',
      'Boltund',
      'Cherubi',
      'Skwovet',
      'Greedent',
      'Basculin',
      'Mareanie',
      'Arrokuda',
      'Barraskewda',
      'Clefairy',
      'Koffing',
      'Sudowoodo',
      'Wobbuffet',
      'Torkoal',
      'Duskull',
      'Munchlax',
      'Purrloin',
      'Throh',
      'Sawk',
      'Cutiefly',
      'Dewpider',
      'Salandit',
      'Wimpod',
      'Rookidee',
      'Gossifleur',
      'Wooloo',
      'Yamper',
      'Rolycoly',
      'Toxel',
      'Mantyke',
      'Clefable',
      'Snorlax',
      'Drapion',
      'Rhydon',
      'Conkeldurr',
      'Bisharp',
      'Corviknight',
    ],
    id: 23,
    pokemon: null,
    location: 'Wild Area: Motostoke Riverbank',
    status: null,
  },
  {
    filter: [
      'Rhyorn',
      'Togepi',
      'Sudowoodo',
      'Wobbuffet',
      'Sneasel',
      'Mawile',
      'Shellos',
      'Liepard',
      'Palpitoad',
      'Vanillite',
      'Karrablast',
      'Ferroseed',
      'Elgyem',
      'Litwick',
      'Cubchoo',
      'Shelmet',
      'Rufflet',
      'Vullaby',
      'Diggersby',
      'Inkay',
      'Binacle',
      'Noibat',
      'Wimpod',
      'Thievul',
      'Carkol',
      'Milcery',
      'Cherubi',
      'Greedent',
      'Magikarp',
      'Gyarados',
      'Lanturn',
      'Qwilfish',
      'Drednaw',
      'Zigzagoon (Galarian)',
      'Baltoy',
      'Bronzor',
      'Bonsly',
      'Croagunk',
      'Munna',
      'Throh',
      'Sawk',
      'Maractus',
      'Scraggy',
      'Frillish',
      'Cutiefly',
      'Stufful',
      'Cramorant',
      'Toxel',
      'Cufant',
      'Tranquill',
      'Woobat',
      'Goldeen',
      'Linoone (Galarian)',
      'Rimbombee',
      'Bewear',
      'Garbodor',
      'Rhydon',
      'Drapion',
      'Vanilluxe',
      'Golisopod',
      'Mimikyu',
      'Claydol',
      'Bronzong',
      'Beheeyem',
      'Noctowl',
      'Noivern',
      'Pangoro',
      'Ferrothorn',
      'Seaking',
      'Jellicent',
      'Weavile',
      'Gallade',
      'Beartic',
      'Musharna',
    ],
    id: 24,
    pokemon: null,
    location: 'Wild Area: Bridge Field',
    status: null,
  },
  {
    filter: [
      'Pikachu',
      'Rhyhorn',
      'Togetic',
      'Shuckle',
      'Sneasel',
      'Barboach',
      'Shellos',
      'Boldore',
      'Drilbur',
      'Gurdurr',
      'Cottonee',
      'Cubchoo',
      'Pawniard',
      'Spritzee',
      'Swirlix',
      'Ribombee',
      'Dottler',
      'Thievul',
      'Eldegoss',
      'Carkol',
      'Applin',
      'Toxel',
      'Impidimp',
      'Machop',
      'Tyrogue',
      'Bonsly',
      'Croagunk',
      'Munna',
      'Maractus',
      'Dwebble',
      'Scraggy',
      'Ferroseed',
      'Dewpider',
      'Salandit',
      'Bounsweet',
      'Nickit',
      'Cramorant',
      'Hatenna',
      'Machoke',
      'Zigzagoon (Galarian)',
      'Ninjask',
      'Baltoy',
      'Bronzor',
      'Yamper',
      'Toxicroak',
      'Roggenrola',
      'Rufflet',
      'Vullaby',
      'Tranquill',
      'Sigilyph',
      'Golurk',
      'Dusknoir',
      'Claydol',
      'Bronzong',
      'Araquanid',
      'Tsareena',
      'Rhydon',
      'Unfezant',
      'Crustle',
    ],
    id: 25,
    pokemon: null,
    location: 'Wild Area: Stony Wilderness',
    status: null,
  },
  {
    filter: [
      'Dugtrio',
      'Rhydon',
      'Sudowoodo',
      'Piloswine',
      'Pelipper',
      'Gardevoir',
      'Roselia',
      'Skuntank',
      'Bronzong',
      'Abomasnow',
      'Gurdurr',
      'Ferrothorn',
      'Klang',
      'Stunfisk (Galarian)',
      'Meowstic',
      'Barbarcle',
      'Charjabug',
      'Mudsdale',
      'Corviknight',
      'Eldegoss',
      'Dubwool',
      'Drednaw',
      'Boltund',
      'Coalossal',
      'Applin',
      'Hattrem',
      'Gyarados',
      'Lanturn',
      'Qwilfish',
      'Barraskewda',
      'Vulpix',
      'Growlithe',
      'Hitmonlee',
      'Hitmonchan',
      'Koffing',
      'Wobbuffet',
      'Shuckle',
      'Sneasel',
      'Swinub',
      'Delibird',
      'Sableye',
      'Mawile',
      'Electrike',
      'Duskull',
      'Hippopotas',
      'Croagunk',
      'Snover',
      'Drilbur',
      'Palpitoad',
      'Scraggy',
      'Gothorita',
      'Duosion',
      'Vanillish',
      'Cubchoo',
      'Nickit',
      'Togekiss',
      'Braviary',
      'Mandibuzz',
      'Shellos',
      'Vanillite',
      'Frillish',
      'Inkay',
      'Dusclops',
      'Seismitoad',
      'Gigalith',
      'Golurk',
      'Flygon',
      'Sigilyph',
      'Claydol',
      'Tyranitar',
      'Barbaracle',
      'Kommo-o',
      'Gastrodon',
    ],
    id: 26,
    pokemon: null,
    location: 'Wild Area: Dusty Bowl',
    status: null,
  },
  {
    filter: [
      'Vulpix',
      'Dugtrio',
      'Growlithe',
      'Machoke',
      'Swinub',
      'Delibird',
      'Pelipper',
      'Baltoy',
      'Snorunt',
      'Drilbur',
      'Dwebble',
      'Vanillite',
      'Karrablast',
      'Klink',
      'Shelmet',
      'Espurr',
      'Honedge',
      'Inkay',
      'Hawlucha',
      'Charjabug',
      'Corvisquire',
      'Thievul',
      'Dubwool',
      'Toxel',
      'Hatenna',
      'Impidimp',
      'Cherubi',
      'Greedent',
      'Gastly',
      'Sudowoodo',
      'Wobbuffet',
      'Sneasel',
      'Trapinch',
      'Palpitoad',
      'Maractus',
      'Axew',
      'Cubchoo',
      'Pumpkaboo',
      'Morelull',
      'Stufful',
      'Wimpod',
      'Unfezant',
      'Corviknight',
      'Vileplume',
      'Roserade',
      'Abomasnow',
      'Klang',
      'Klinklang',
      'Gourgeist',
    ],
    id: 27,
    pokemon: null,
    location: 'Wild Area: Hammerlocke Hills',
    status: null,
  },
  {
    filter: [
      'Dugtrio',
      'Delibird',
      'Lombre',
      'Nuzleaf',
      'Baltoy',
      'Duskull',
      'Snorunt',
      'Shellos',
      'Stunky',
      'Snover',
      'Munna',
      'Drilbur',
      'Palpitoad',
      'Karrablast',
      'Joltik',
      'Shelmet',
      'Golett',
      'Pawniard',
      'Mudbray',
      'Dottler',
      'Eldegoss',
      'Toxel',
      'Cherubi',
      'Greedent',
      'Krabby',
      'Goldeen',
      'Gyarados',
      'Corphish',
      'Clefairy',
      'Gloom',
      'Noctowl',
      'Quagsire',
      'Shuckle',
      'Sneasel',
      'Linoone (Galarian)',
      'Manectric',
      'Torkoal',
      'Riolu',
      'Croagunk',
      'Liepard',
      'Scraggy',
      'Minccino',
      'Gothita',
      'Solosis',
      'Vanillite',
      'Diggersby',
      'Drednaw',
      'Carkol',
      'Clefairy',
      'Gloom',
      'Wooper',
      'Shuckle',
      'Sneasel',
      'Zigzagoon (Galarian)',
      'Torkoal',
      'Bunnelby',
      'Blipbug',
      'Chewtle',
      'Rolycoly',
      'Wooper',
      'Hoothoot',
      'Dottler',
      'Lunatone',
      'Solrock',
      'Gengar',
      'Golisopod',
      'Beartic',
      'Coalossal',
      'Corviknight',
      'Glalie',
      'Excadrill',
      'Seismitoad',
      'Cinccino',
      'Galvantula',
      'Orbeetle',
      'Doublade',
      'Aegislash',
    ],
    id: 28,
    pokemon: null,
    location: "Wild Area: Giant's Cap",
    status: null,
  },
  {
    filter: [
      'Diglett',
      'Machop',
      'Koffing',
      'Swinub',
      'Roselia',
      'Torkoal',
      'Budew',
      'Shellos',
      'Hippowdon',
      'Skorupi',
      'Snover',
      'Joltik',
      'Cubchoo',
      'Diggersby',
      'Mimikyu',
      'Dottler',
      'Applin',
      'Impidimp',
      'Milcery',
      'Cherubi',
      'Greedent',
      'Gyarados',
      'Chinchou',
      'Mareanie',
      'Drednaw',
      'Butterfree',
      'Gloom',
      "Farfetch'd (Galarian)",
      'Rhyhorn',
      'Natu',
      'Corsola (Galarian)',
      'Delibird',
      'Tranquill',
      'Woobat',
      'Drilbur',
      'Palpitoad',
      'Throh',
      'Sawk',
      'Vanillite',
      'Pawniard',
      'Heatmor',
      'Durant',
      'Spritzee',
      'Swirlix',
      'Helioptile',
      'Pumpkaboo',
      'Cutiefly',
      'Morelull',
      'Wimpod',
      'Nickit',
      'Chewtle',
      'Yamper',
      'Dugtrio',
      'Boldore',
      'Excadrill',
      'Corvisquire',
      'Frillish',
      'Inkay',
      'Steelix',
      'Perrserker',
      'Machamp',
      'Abomasnow',
      'Seismitoad',
      'Xatu',
      'Unfezant',
      'Vileplume',
      'Bellossom',
      'Gastrodon',
    ],
    id: 29,
    pokemon: null,
    location: "Wild Area: Giant's Mirror",
    status: null,
  },
  {
    filter: [
      'Dugtrio',
      'Rhydon',
      'Mr. Mime (Galarian)',
      'Ditto',
      'Quagsire',
      'Piloswine',
      'Larvitar',
      'Pupitar',
      'Pelipper',
      'Gardevoir',
      'Claydol',
      'Skuntank',
      'Bronzong',
      'Hippowdon',
      'Jellicent',
      'Stunfisk (Galarian)',
      'Deino',
      'Zweilous',
      'Pangoro',
      'Doublade',
      'Barbaracle',
      'Goomy',
      'Sliggoo',
      'Bewear',
      'Turtonator',
      'Togedmaru',
      'Drampa',
      'Jangmo-o',
      'Hakam-o',
      'Corviknight',
      'Orbeetle',
      'Drednaw',
      'Boltund',
      'Coalossal',
      'Sandaconda',
      'Cramorant',
      'Grimmsnarl',
      'Obstagoon',
      'Perrserker',
      'Falinks',
      'Snom',
      'Stonjourner',
      'Eiscue',
      'Indeedee',
      'Duraludon',
      'Dreepy',
      'Cherubi',
      'Greedent',
      'Gyarados',
      'Lanturn',
      'Qwilfish',
      'Barraskewda',
      'Ninetales',
      'Arcanine',
      'Weezing (Galarian)',
      'Wobbuffet',
      'Hitmontop',
      'Flygon',
      'Glalie',
      'Drapion',
      'Abomasnow',
      'Rotom',
      'Boldore',
      'Excadrill',
      'Seismitoad',
      'Sigilyph',
      'Garbodor',
      'Gothitelle',
      'Reuniclus',
      'Vanilluxe',
      'Galvantula',
      'Klinklang',
      'Beheeyem',
      'Lampent',
      'Haxorus',
      'Golurk',
      'Bisharp',
      'Braviary',
      'Mandibuzz',
      'Heatmor',
      'Durant',
      'Bergmite',
      'Noivern',
      'Araquanid',
      'Golisopod',
      'Hatterne',
      'Morpeko',
      'Copperajah',
      'Drakloak',
      'Mantine',
      'Mantyke',
      'Vanillite',
      'Barraskweda',
      'Seaking',
      'Milotic',
      'Lapras',
      'Grapploct',
      'Vaporeon',
      'Jolteon',
      'Flareon',
      'Espeon',
      'Umbreon',
      'Leafeon',
      'Glaceon',
      'Sylveon',
      'Chandelure',
      'Avalugg',
      'Shiinotic',
    ],
    id: 30,
    pokemon: null,
    location: 'Wild Area: Lake of Outrage',
    status: null,
  },
  {
    filter: [
      'Torkoal',
      'Duskull',
      'Hippopotas',
      'Skorupi',
      'Heatmor',
      'Durant',
      'Hawlucha',
      'Silicobra',
      'Greedent',
      'Goldeen',
      'Magikarp',
      'Drednaw',
      'Dugtrio',
      'Trapinch',
      'Maractus',
      'Yamask',
      'Axew',
      'Helioptile',
      'Dracozolt',
      'Arctozolt',
      'Dracovish',
      'Arctovish',
    ],
    id: 31,
    pokemon: null,
    location: 'Route 6',
    status: null,
  },
  {
    filter: [
      'Ponyta (Galarian)',
      'Spritzee',
      'Swirilix',
      'Phantump',
      'Shiinotic',
      'Oranguru',
      'Passimian',
      'Sinistea',
      'Hattrem',
      'Morgrem',
      'Indeedee',
      'Impidimp',
    ],
    id: 32,
    pokemon: null,
    location: 'Glimwood Tangle',
    status: null,
  },
  {
    filter: [
      'Liepard',
      'Seismitoad',
      'Karrablast',
      'Shelmet',
      'Meowstic',
      'Corviknight',
      'Toxel',
      'Greedent',
      'Galvantula',
      'Inkay',
      'Thievul',
      'Perrserker',
      'Morpeko',
    ],
    id: 33,
    pokemon: null,
    location: 'Route 7',
    status: null,
  },
  {
    filter: [
      'Haunter',
      'Rhyhorn',
      'Dusclops',
      'Bronzong',
      'Hippowdon',
      'Drapion',
      'Sandaconda',
      'Falinks',
      'Lunatone',
      'Solrock',
      'Boldore',
      'Gurdurr',
      'Golett',
      'Pawniard',
      'Rufflet',
      'Vullaby',
      'Togedemaru',
      'Crustle',
      'Sneasel',
      'Delibird',
      'Snover',
      'Darumaka (Galarian)',
      'Snom',
      'Snorunt',
      'Throh',
      'Sawk',
      'Vanillish',
    ],
    id: 34,
    pokemon: null,
    location: 'Route 8',
    status: null,
  },
  {
    filter: [
      'Kingler',
      'Octillery',
      'Cramorant',
      'Pincurchin',
      'Wishiwashi',
      'Pyukumuku',
      'Pelipper',
      'Gastrodon',
      'Jellicent',
      'Mareanie',
      'Qwilfish',
      'Mantyke',
      'Glalie',
      'Inkay',
      'Greedent',
      'Lapras',
      'Mantine',
      'Wailmer',
      'Wailord',
      'Barbaracle',
      'Bergmite',
      'Toxapex',
      'Dhelmise',
      'Clobbopus',
      'Remoraid',
      'Grapploct',
      'Liepard',
      'Thievul',
      'Perrserker',
      'Morpeko',
    ],
    id: 35,
    pokemon: null,
    location: 'Route 9',
    status: null,
  },
  {
    filter: [
      'Rhydon',
      'Darumaka (Galarian)',
      'Vanillish',
      'Klang',
      'Snom',
      'Mr. Mime (Galarian)',
      'Glalie',
      'Snover',
      'Vanilluxe',
      'Cubchoo',
      'Abomasnow',
      'Beartic',
      'Stonjourner',
      'Eiscue',
    ],
    id: 37,
    pokemon: null,
    location: 'Route 10',
    status: null,
  },
  {
    filter: ['Eternatus'],
    id: 38,
    pokemon: null,
    location: 'Energy Plant',
    status: null,
  },
];

export default SW_SH;
