import { TEncounter } from 'constants/types';

const SW_SH: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    id: 1,
    pokemon: null,
    location: 'Slumbering Weald',
    status: null,
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 1',
    status: null,
  },
  {
    id: 3,
    pokemon: null,
    location: 'Wedgehurst',
    status: null,
  },
  {
    id: 4,
    pokemon: null,
    location: 'Route 2',
    status: null,
  },
  {
    id: 5,
    pokemon: null,
    location: 'Wild Area: Rolling Fields',
    status: null,
  },
  {
    id: 6,
    pokemon: null,
    location: 'Wild Area: Dappled Grove',
    status: null,
  },
  {
    id: 7,
    pokemon: null,
    location: 'Wild Area: West Lake Axewell',
    status: null,
  },
  {
    id: 8,
    pokemon: null,
    location: 'WildArea: East Lake Axewell',
    status: null,
  },
  {
    id: 9,
    pokemon: null,
    location: 'Wild Area: North Lake Miloch',
    status: null,
  },
  {
    id: 10,
    pokemon: null,
    location: 'Wild Area: South Lake Miloch',
    status: null,
  },
  {
    id: 11,
    pokemon: null,
    location: 'Wild Area: Watchtower Ruins',
    status: null,
  },
  {
    id: 12,
    pokemon: null,
    location: "Wild Area: Giant's Seat",
    status: null,
  },
  {
    id: 36,
    pokemon: null,
    location: "Wild Area: Axew's Eye",
    status: null,
  },
  {
    id: 13,
    pokemon: null,
    location: 'Motostoke',
    status: null,
  },
  {
    id: 14,
    pokemon: null,
    location: 'Route 3',
    status: null,
  },
  {
    id: 15,
    pokemon: null,
    location: 'Galar Mine',
    status: null,
  },
  {
    id: 16,
    pokemon: null,
    location: 'Route 4',
    status: null,
  },
  {
    id: 17,
    pokemon: null,
    location: 'Route 5',
    status: null,
  },
  {
    id: 18,
    pokemon: null,
    location: 'Hulbury',
    status: null,
  },
  {
    id: 19,
    pokemon: null,
    location: 'Galar Mine No. 2',
    status: null,
  },
  {
    id: 21,
    pokemon: null,
    location: 'Motostoke Outskirts',
    status: null,
  },
  {
    id: 22,
    pokemon: null,
    location: 'Motostoke Stadium',
    status: null,
  },
  {
    id: 23,
    pokemon: null,
    location: 'Wild Area: Motostoke Riverbank',
    status: null,
  },
  {
    id: 24,
    pokemon: null,
    location: 'Wild Area: Bridge Field',
    status: null,
  },
  {
    id: 25,
    pokemon: null,
    location: 'Wild Area: Stony Wilderness',
    status: null,
  },
  {
    id: 26,
    pokemon: null,
    location: 'Wild Area: Dusty Bowl',
    status: null,
  },
  {
    id: 27,
    pokemon: null,
    location: 'Wild Area: Hammerlocke Hills',
    status: null,
  },
  {
    id: 28,
    pokemon: null,
    location: "Wild Area: Giant's Cap",
    status: null,
  },
  {
    id: 29,
    pokemon: null,
    location: "Wild Area: Giant's Mirror",
    status: null,
  },
  {
    id: 30,
    pokemon: null,
    location: 'Wild Area: Lake of Outrage',
    status: null,
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 6',
    status: null,
  },
  {
    id: 32,
    pokemon: null,
    location: 'Glimwood Tangle',
    status: null,
  },
  {
    id: 33,
    pokemon: null,
    location: 'Route 7',
    status: null,
  },
  {
    id: 34,
    pokemon: null,
    location: 'Route 8',
    status: null,
  },
  {
    id: 35,
    pokemon: null,
    location: 'Route 9',
    status: null,
  },
  {
    id: 37,
    pokemon: null,
    location: 'Route 10',
    status: null,
  },
  {
    id: 38,
    pokemon: null,
    location: 'Energy Plant',
    status: null,
  },
];

export default SW_SH;
