import type { TEncounter } from 'constants/types';

const SW_SH: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
    filterKey: 'swsh-0',
  },
  {
    id: 1,
    pokemon: null,
    location: 'Slumbering Weald',
    status: null,
    filterKey: 'swsh-1',
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 1',
    status: null,
    filterKey: 'swsh-2',
  },
  {
    id: 3,
    pokemon: null,
    location: 'Wedgehurst',
    status: null,
    filterKey: 'swsh-3',
  },
  {
    id: 4,
    pokemon: null,
    location: 'Route 2',
    status: null,
    filterKey: 'swsh-4',
  },
  {
    id: 39,
    pokemon: null,
    location: 'Wild Area Station',
    status: null,
    filterKey: 'swsh-39',
  },
  {
    id: 5,
    pokemon: null,
    location: 'Wild Area: Rolling Fields',
    status: null,
    filterKey: 'swsh-5',
  },
  {
    id: 6,
    pokemon: null,
    location: 'Wild Area: Dappled Grove',
    status: null,
    filterKey: 'swsh-6',
  },
  {
    id: 7,
    pokemon: null,
    location: 'Wild Area: West Lake Axewell',
    status: null,
    filterKey: 'swsh-7',
  },
  {
    id: 8,
    pokemon: null,
    location: 'WildArea: East Lake Axewell',
    status: null,
    filterKey: 'swsh-8',
  },
  {
    id: 9,
    pokemon: null,
    location: 'Wild Area: North Lake Miloch',
    status: null,
    filterKey: 'swsh-9',
  },
  {
    id: 10,
    pokemon: null,
    location: 'Wild Area: South Lake Miloch',
    status: null,
    filterKey: 'swsh-10',
  },
  {
    id: 11,
    pokemon: null,
    location: 'Wild Area: Watchtower Ruins',
    status: null,
    filterKey: 'swsh-11',
  },
  {
    id: 12,
    pokemon: null,
    location: "Wild Area: Giant's Seat",
    status: null,
    filterKey: 'swsh-12',
  },
  {
    id: 36,
    pokemon: null,
    location: "Wild Area: Axew's Eye",
    status: null,
    filterKey: 'swsh-36',
  },
  {
    id: 13,
    pokemon: null,
    location: 'Motostoke',
    status: null,
    filterKey: 'swsh-13',
  },
  {
    id: 14,
    pokemon: null,
    location: 'Route 3',
    status: null,
    filterKey: 'swsh-14',
  },
  {
    id: 15,
    pokemon: null,
    location: 'Galar Mine',
    status: null,
    filterKey: 'swsh-15',
  },
  {
    id: 16,
    pokemon: null,
    location: 'Route 4',
    status: null,
    filterKey: 'swsh-16',
  },
  {
    id: 17,
    pokemon: null,
    location: 'Route 5',
    status: null,
    filterKey: 'swsh-17',
  },
  {
    id: 18,
    pokemon: null,
    location: 'Hulbury',
    status: null,
    filterKey: 'swsh-18',
  },
  {
    id: 19,
    pokemon: null,
    location: 'Galar Mine No. 2',
    status: null,
    filterKey: 'swsh-19',
  },
  {
    id: 21,
    pokemon: null,
    location: 'Motostoke Outskirts',
    status: null,
    filterKey: 'swsh-21',
  },
  {
    id: 22,
    pokemon: null,
    location: 'Motostoke Stadium',
    status: null,
    filterKey: 'swsh-22',
  },
  {
    id: 23,
    pokemon: null,
    location: 'Wild Area: Motostoke Riverbank',
    status: null,
    filterKey: 'swsh-23',
  },
  {
    id: 24,
    pokemon: null,
    location: 'Wild Area: Bridge Field',
    status: null,
    filterKey: 'swsh-24',
  },
  {
    id: 25,
    pokemon: null,
    location: 'Wild Area: Stony Wilderness',
    status: null,
    filterKey: 'swsh-25',
  },
  {
    id: 26,
    pokemon: null,
    location: 'Wild Area: Dusty Bowl',
    status: null,
    filterKey: 'swsh-26',
  },
  {
    id: 27,
    pokemon: null,
    location: 'Wild Area: Hammerlocke Hills',
    status: null,
    filterKey: 'swsh-27',
  },
  {
    id: 28,
    pokemon: null,
    location: "Wild Area: Giant's Cap",
    status: null,
    filterKey: 'swsh-28',
  },
  {
    id: 29,
    pokemon: null,
    location: "Wild Area: Giant's Mirror",
    status: null,
    filterKey: 'swsh-29',
  },
  {
    id: 30,
    pokemon: null,
    location: 'Wild Area: Lake of Outrage',
    status: null,
    filterKey: 'swsh-30',
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 6',
    status: null,
    filterKey: 'swsh-31',
  },
  {
    id: 32,
    pokemon: null,
    location: 'Glimwood Tangle',
    status: null,
    filterKey: 'swsh-32',
  },
  {
    id: 33,
    pokemon: null,
    location: 'Route 7',
    status: null,
    filterKey: 'swsh-33',
  },
  {
    id: 34,
    pokemon: null,
    location: 'Route 8',
    status: null,
    filterKey: 'swsh-34',
  },
  {
    id: 35,
    pokemon: null,
    location: 'Route 9',
    status: null,
    filterKey: 'swsh-35',
  },
  {
    id: 37,
    pokemon: null,
    location: 'Route 10',
    status: null,
    filterKey: 'swsh-37',
  },
  {
    id: 38,
    pokemon: null,
    location: 'Energy Plant',
    status: null,
    filterKey: 'swsh-38',
  },
];

export default SW_SH;
