import type { TEncounter } from 'constants/types';

const US_UM: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
    filterKey: 'usum-0',
  },
  {
    id: 1,
    pokemon: null,
    location: "Hau'oli Outskirts",
    status: null,
    filterKey: 'usum-1',
  },
  {
    id: 2,
    pokemon: null,
    location: 'Iki Town',
    status: null,
    filterKey: 'usum-2',
  },
  {
    id: 3,
    pokemon: null,
    location: 'Route 1',
    status: null,
    filterKey: 'usum-3',
  },
  {
    id: 4,
    pokemon: null,
    location: "Route 1 (Trainer's School)",
    status: null,
    filterKey: 'usum-4',
  },
  {
    id: 5,
    pokemon: null,
    location: "Hau'oli City",
    status: null,
    filterKey: 'usum-5',
  },
  {
    id: 6,
    pokemon: null,
    location: 'Route 2',
    status: null,
    filterKey: 'usum-6',
  },
  {
    id: 8,
    pokemon: null,
    location: 'Verdant Cavern',
    status: null,
    filterKey: 'usum-8',
  },
  {
    id: 9,
    pokemon: null,
    location: "Hau'oli Cemetery",
    status: null,
    filterKey: 'usum-9',
  },
  {
    id: 59,
    pokemon: null,
    location: 'Berry Fields',
    status: null,
    filterKey: 'usum-59',
  },
  {
    id: 10,
    pokemon: null,
    location: 'Route 3',
    status: null,
    filterKey: 'usum-10',
  },
  {
    id: 11,
    pokemon: null,
    location: 'Melemele Meadow',
    status: null,
    filterKey: 'usum-11',
  },
  {
    id: 12,
    pokemon: null,
    location: 'Seaward Cave',
    status: null,
    filterKey: 'usum-12',
  },
  {
    id: 13,
    pokemon: null,
    location: "Kala'e Bay",
    status: null,
    filterKey: 'usum-13',
  },
  {
    id: 14,
    pokemon: null,
    location: 'Ten Carat Hill',
    status: null,
    filterKey: 'usum-14',
  },
  {
    id: 60,
    pokemon: null,
    location: 'Sandy Cave',
    status: null,
    filterKey: 'usum-60',
  },
  {
    id: 15,
    pokemon: null,
    location: 'Route 4',
    status: null,
    filterKey: 'usum-15',
  },
  {
    id: 16,
    pokemon: null,
    location: 'Paniola Town',
    status: null,
    filterKey: 'usum-16',
  },
  {
    id: 17,
    pokemon: null,
    location: 'Paniola Ranch',
    status: null,
    filterKey: 'usum-17',
  },
  {
    id: 18,
    pokemon: null,
    location: 'Route 5',
    status: null,
    filterKey: 'usum-18',
  },
  {
    id: 19,
    pokemon: null,
    location: 'Route 10',
    status: null,
    filterKey: 'usum-19',
  },
  {
    id: 21,
    pokemon: null,
    location: 'Brooklet Hill',
    status: null,
    filterKey: 'usum-21',
  },
  {
    id: 32,
    pokemon: null,
    location: 'Melemele Sea',
    status: null,
    filterKey: 'usum-32',
  },
  {
    id: 22,
    pokemon: null,
    location: 'Route 6',
    status: null,
    filterKey: 'usum-22',
  },
  {
    id: 51,
    pokemon: null,
    location: 'Royal Avenue',
    status: null,
    filterKey: 'usum-51',
  },
  {
    id: 23,
    pokemon: null,
    location: 'Route 7',
    status: null,
    filterKey: 'usum-23',
  },
  {
    id: 24,
    pokemon: null,
    location: 'Wela Volcano Park',
    status: null,
    filterKey: 'usum-24',
  },
  {
    id: 52,
    pokemon: null,
    location: 'Dividing Peak Tunnel',
    status: null,
    filterKey: 'usum-52',
  },
  {
    id: 25,
    pokemon: null,
    location: 'Route 8',
    status: null,
    filterKey: 'usum-25',
  },
  {
    id: 26,
    pokemon: null,
    location: 'Lush Jungle',
    status: null,
    filterKey: 'usum-26',
  },
  {
    id: 27,
    pokemon: null,
    location: "Diglett's Tunnel",
    status: null,
    filterKey: 'usum-27',
  },
  {
    id: 28,
    pokemon: null,
    location: 'Route 9',
    status: null,
    filterKey: 'usum-28',
  },
  {
    id: 29,
    pokemon: null,
    location: 'Konikoni City',
    status: null,
    filterKey: 'usum-29',
  },
  {
    id: 30,
    pokemon: null,
    location: 'Memorial Hill',
    status: null,
    filterKey: 'usum-30',
  },
  {
    id: 31,
    pokemon: null,
    location: 'Akala Outskirts',
    status: null,
    filterKey: 'usum-31',
  },
  {
    id: 33,
    pokemon: null,
    location: 'Hano Beach',
    status: null,
    filterKey: 'usum-33',
  },
  {
    id: 34,
    pokemon: null,
    location: 'Malie City',
    status: null,
    filterKey: 'usum-34',
  },
  {
    id: 35,
    pokemon: null,
    location: 'Malie Garden',
    status: null,
    filterKey: 'usum-35',
  },
  {
    id: 36,
    pokemon: null,
    location: 'Mt. Hokulani',
    status: null,
    filterKey: 'usum-36',
  },
  {
    id: 37,
    pokemon: null,
    location: 'Route 11',
    status: null,
    filterKey: 'usum-37',
  },
  {
    id: 38,
    pokemon: null,
    location: 'Route 12',
    status: null,
    filterKey: 'usum-38',
  },
  {
    id: 39,
    pokemon: null,
    location: 'Blush Mountain',
    status: null,
    filterKey: 'usum-39',
  },
  {
    id: 40,
    pokemon: null,
    location: "Ula'ula Beach",
    status: null,
    filterKey: 'usum-40',
  },
  {
    id: 41,
    pokemon: null,
    location: 'Route 13',
    status: null,
    filterKey: 'usum-41',
  },
  {
    id: 42,
    pokemon: null,
    location: 'Tapu Village',
    status: null,
    filterKey: 'usum-42',
  },
  {
    id: 43,
    pokemon: null,
    location: 'Route 14',
    status: null,
    filterKey: 'usum-43',
  },
  {
    id: 44,
    pokemon: null,
    location: 'Route 15',
    status: null,
    filterKey: 'usum-44',
  },
  {
    id: 45,
    pokemon: null,
    location: 'Thrify Megamart',
    status: null,
    filterKey: 'usum-45',
  },
  {
    id: 53,
    pokemon: null,
    location: 'Haina Desert',
    status: null,
    filterKey: 'usum-53',
  },
  {
    id: 46,
    pokemon: null,
    location: 'Route 16',
    status: null,
    filterKey: 'usum-46',
  },
  {
    id: 47,
    pokemon: null,
    location: "Ula'ula Meadow",
    status: null,
    filterKey: 'usum-47',
  },
  {
    id: 48,
    pokemon: null,
    location: 'Route 17',
    status: null,
    filterKey: 'usum-48',
  },
  {
    id: 54,
    pokemon: null,
    location: 'Seafolk Village',
    status: null,
    filterKey: 'usum-54',
  },
  {
    id: 61,
    pokemon: null,
    location: 'Poni Wilds',
    status: null,
    filterKey: 'usum-61',
  },
  {
    id: 55,
    pokemon: null,
    location: 'Exeggutor Island',
    status: null,
    filterKey: 'usum-55',
  },
  {
    id: 56,
    pokemon: null,
    location: 'Vast Poni Canyon',
    status: null,
    filterKey: 'usum-56',
  },
  {
    id: 57,
    pokemon: null,
    location: 'Mount Lanakila',
    status: null,
    filterKey: 'usum-57',
  },
  {
    id: 58,
    pokemon: null,
    location: 'Mahalo Trail',
    status: null,
    filterKey: 'usum-58',
  },
];

export default US_UM;
