import { TEncounter } from 'constants/types';

const US_UM: TEncounter[] = [
  {
    filter: ['Rowlet', 'Litten', 'Popplio'],
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    filter: ['Slowpoke', 'Wingull', 'Inkay', 'Tentacool', 'Finneon', 'Mantyke'],
    id: 1,
    pokemon: null,
    location: "Hau'oli Outskirts",
    status: null,
  },
  {
    filter: ['Rowlet', 'Litten', 'Popplio'],
    id: 2,
    pokemon: null,
    location: 'Iki Town',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Rattata (Alolan)',
      'Ledyba',
      'Spinark',
      'Pikipek',
      'Yungoos',
      'Pichu',
      'Pikachu',
      'Happiny',
      'Grubbin',
      'Metapod',
      'Bonsly',
      'Sudowoodo',
      'Munchlax',
      'Snorlax',
      'Buneary',
      'Rockruff',
    ],
    id: 3,
    pokemon: null,
    location: 'Route 1',
    status: null,
  },
  {
    filter: ['Meowth (Alolan)', 'Magnemite', 'Grimer (Alolan), Zorua, Gastly, Drifloon'],
    id: 4,
    pokemon: null,
    location: "Route 1 (Trainer's School)",
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Wingull',
      'Finneon',
      'Mantyke',
      'Remoraid',
      'Meowth (Alolan)',
      'Abra',
      'Magnemite',
      'Grimer (Alolan)',
      'Mime Jr.',
      'Mr. Mime',
      'Happiny',
      'Furfrou',
      'Bewear',
      'Hypno',
      'Scatterbug',
    ],
    id: 5,
    pokemon: null,
    location: "Hau'oli City",
    status: null,
  },
  {
    filter: [
      'Rattata (Alolan)',
      'Ekans',
      'Meowth (Alolan)',
      'Abra',
      'Drowzee',
      'Smeargle',
      'Yungoos',
      'Spearow',
      'Growlithe',
      'Cutiefly',
      'Makuhita',
      'Crabrawler',
      'Bulbasaur',
      'Furfrou',
      'Dunsparce',
      'Hawlucha',
    ],
    id: 6,
    pokemon: null,
    location: 'Route 2',
    status: null,
  },
  {
    filter: ['Zubat', 'Diglett (Alolan)', 'Rattata (Alolan)', 'Yungoos', 'Noibat'],
    id: 8,
    pokemon: null,
    location: 'Verdant Cavern',
    status: null,
  },
  {
    filter: ['Zubat', 'Gastly', 'Murkrow', 'Drifloon', 'Litwick'],
    id: 9,
    pokemon: null,
    location: "Hau'oli Cemetery",
    status: null,
  },
  {
    filter: [
      'Spearow',
      'Mankey',
      'Hawlucha',
      'Cutiefly',
      'Bagon',
      'Salamence',
      'Rufflet',
      'Vullaby',
      'Crabrawler',
      'Charmander',
    ],
    id: 10,
    pokemon: null,
    location: 'Route 3',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Cottonee',
      'Petilil',
      'Oricorio',
      'Cutiefly',
      'Flabébé',
    ],
    id: 11,
    pokemon: null,
    location: 'Melemele Meadow',
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Psyduck',
      'Delibird',
      'Smoochum',
      'Jynx',
      'Happiny',
      'Seel',
      'Magikarp',
      'Gyarados',
      'Barboach',
      'Whiscash',
      'Squirtle',
    ],
    id: 12,
    pokemon: null,
    location: 'Seaward Cave',
    status: null,
  },
  {
    filter: [
      'Rattata (Alolan)',
      'Slowpoke',
      'Slowbro',
      'Wingull',
      'Bagon',
      'Shelgon',
      'Yungoos',
      'Tentacool',
      'Finneon',
      'Mantyke',
      'Remoraid',
      'Octillery',
      'Shellder',
      'Magikarp',
      'Gyarados',
      'Wishiwashi',
      'Horsea',
    ],
    id: 13,
    pokemon: null,
    location: "Kala'e Bay",
    status: null,
  },
  {
    filter: [
      'Zubat',
      'Roggenrola',
      'Carbink',
      'Sableye',
      'Psyduck',
      'Onix',
      'Machop',
      'Spinda',
      'Carbink',
      'Rockruff',
    ],
    id: 14,
    pokemon: null,
    location: 'Ten Carat Hill',
    status: null,
  },
  {
    id: 50,
    pokemon: null,
    location: 'Big Wave Beach',
    status: null,
  },
  {
    filter: [
      'Rattata (Alolan)',
      'Eevee',
      'Espeon',
      'Umbreon',
      'Igglybuff',
      'Jigglypuff',
      'Happiny',
      'Lillipup',
      'Pikipek',
      'Yungoos',
      'Grubbin',
      'Mudbray',
      'Crabrawler',
      'Beedrill',
    ],
    id: 15,
    pokemon: null,
    location: 'Route 4',
    status: null,
  },
  {
    filter: ['Magikarp', 'Barboach', 'Gyarados', 'Whiscash'],
    id: 16,
    pokemon: null,
    location: 'Paniola Town',
    status: null,
  },
  {
    filter: ['Tauros', 'Miltank', 'Mareep', 'Lillipup', 'Mudbray', 'Eevee'],
    id: 17,
    pokemon: null,
    location: 'Paniola Ranch',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Lillipup',
      'Pikipek',
      'Grubbin',
      'Fomantis',
      'Crabrawler',
      'Noibat',
      'Groyvle',
      'Bonsly',
      'Sudowoodo',
      'Happiny',
      'Trumbeak',
      'Diglett (Alolan)',
    ],
    id: 18,
    pokemon: null,
    location: 'Route 5',
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Fearow',
      'Ledian',
      'Ariados',
      'Skarmory',
      'Pancham',
      'Pangoro',
      'Pineco',
      'Gumshoos',
      'Crabrawler',
      'Pidgeot',
    ],
    id: 19,
    pokemon: null,
    location: 'Route 10',
    status: null,
  },
  {
    filter: [
      'Paras',
      'Psyduck',
      'Poliwag',
      'Wingull',
      'Surskit',
      'Lillipup',
      'Dewpider',
      'Morelull',
      'Goldeen',
      'Seaking',
      'Gyarados',
      'Magikarp',
      'Feebas',
      'Basculin',
      'Wishiwashi',
      'Marshtomp',
      'Tentacool',
      'Finneon',
      'Alomomola',
    ],
    id: 21,
    pokemon: null,
    location: 'Brooklet Hill',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Wingull',
      'Mantyke',
      'Remoraid',
      'Octillery',
      'Clamperl',
      'Gorebyss',
      'Huntail',
      'Finneon',
      'Magikarp',
      'Gyarados',
      'Corsola',
      'Mareanie',
      'Luvdisc',
      'Wishiwashi',
    ],
    id: 32,
    pokemon: null,
    location: 'Melemele Sea',
    status: null,
  },
  {
    filter: [
      'Rattata (Alolan)',
      'Eevee',
      'Espeon',
      'Umbreon',
      'Igglybuff',
      'Jigglypuff',
      'Happiny',
      'Lillipup',
      'Pikipek',
      'Yungoos',
      'Grubbin',
      'Mudbray',
      'Oricorio',
      'Ralts',
    ],
    id: 22,
    pokemon: null,
    location: 'Route 6',
    status: null,
  },
  {
    id: 51,
    pokemon: null,
    location: 'Royal Avenue',
    status: null,
  },
  {
    filter: [
      'Diglett (Alolan)',
      'Tentacool',
      'Wingull',
      'Finneon',
      'Pyukumuku',
      'Staryu',
      'Starmie',
      'Magikarp',
      'Gyarados',
      'Wishiwashi',
      'Spheal',
    ],
    id: 23,
    pokemon: null,
    location: 'Route 7',
    status: null,
  },
  {
    filter: [
      'Cubone',
      'Kangaskhan',
      'Magby',
      'Magmar',
      'Happiny',
      'Fletchling',
      'Fletchinder',
      'Salandit',
      'Salazzle',
    ],
    id: 24,
    pokemon: null,
    location: 'Wela Volcano Park',
    status: null,
  },
  {
    filter: ['Kecleon', 'Wimpod'],
    id: 52,
    pokemon: null,
    location: 'Dividing Peak Tunnel',
    status: null,
  },
  {
    filter: [
      'Rattata (Alolan)',
      'Raticate (Alolan)',
      'Fletchling',
      'Fletchinder',
      'Trumbeak',
      'Yungoos',
      'Gumshoos',
      'Salandit',
      'Stufful',
      'Crabrawler',
      'Wimpod',
      'Tentacool',
      'Wingull',
      'Finneon',
      'Mantyke',
      'Remoraid',
      'Octillery',
      'Magikarp',
      'Gyarados',
      'Chinchou',
      'Lanturn',
      'Wishiwashi',
      'Arbok',
      'Combusken',
      'Omanyte',
      'Kabuto',
      'Lileep',
      'Anorith',
      'Amaura',
      'Tyrunt',
      'Cranidos',
      'Shieldon',
      'Tirtouga',
      'Archen',
    ],
    id: 25,
    pokemon: null,
    location: 'Route 8',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Butterfree',
      'Paras',
      'Pinsir',
      'Bonsly',
      'Sudowoodo',
      'Happiny',
      'Trumbeak',
      'Fomantis',
      'Steenee',
      'Morelull',
      'Comfey',
      'Oranguru',
      'Passimian',
      'Goomy',
      'Castform',
      'Zubat',
      'Diglett (Alolan)',
      'Crobat',
      'Golbat',
      'Dugtrio (Alolan)',
      'Larvesta',
      'Volcarona',
      'Salandit',
      'Salazzle',
    ],
    id: 26,
    pokemon: null,
    location: 'Lush Jungle',
    status: null,
  },
  {
    filter: ['Zubat', 'Golbat', 'Diglett (Alolan)', 'Larvitar'],
    id: 27,
    pokemon: null,
    location: "Diglett's Tunnel",
    status: null,
  },
  {
    filter: ['Magikarp', 'Gyarados', 'Corsola', 'Mareanie', 'Luvdisc', 'Wishiwashi', 'Ditto'],
    id: 28,
    pokemon: null,
    location: 'Route 9',
    status: null,
  },
  {
    filter: ['Ditto'],
    id: 29,
    pokemon: null,
    location: 'Konikoni City',
    status: null,
  },
  {
    filter: ['Zubat', 'Golbat', 'Gastly', 'Phantump'],
    id: 30,
    pokemon: null,
    location: 'Memorial Hill',
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Natu',
      'Xatu',
      'Lanturn',
      'Wingull',
      'Nosepass',
      'Gumshoos',
      'Stufful',
      'Magikarp',
      'Gyarados',
      'Chinchou',
      'Wishiwashi',
      'Honedge',
    ],
    id: 31,
    pokemon: null,
    location: 'Akala Outskirts',
    status: null,
  },
  {
    filter: ['Staryu', 'Sandygast', 'Tentacool', 'Wingull', 'Finneon', 'Pyukumuku'],
    id: 33,
    pokemon: null,
    location: 'Hano Beach',
    status: null,
  },
  {
    filter: ['Magnemite', 'Grimer (Alolan)', 'Trubbish', 'Minccino'],
    id: 34,
    pokemon: null,
    location: 'Malie City',
    status: null,
  },
  {
    filter: [
      'Mewoth (Alolan)',
      'Psyduck',
      'Poliwag',
      'Ledian',
      'Ariados',
      'Masquerain',
      'Cottonee',
      'Petilil',
      'Araquanid',
      'Poliwhirl',
      'Poliwrath',
      'Politoed',
      'Castform',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Gyarados',
      'Basculin',
    ],
    id: 35,
    pokemon: null,
    location: 'Malie Garden',
    status: null,
  },
  {
    filter: [
      'Fearow',
      'Ditto',
      'Cleffa',
      'Clefairy',
      'Happiny',
      'Skarmory',
      'Elekid',
      'Electabuzz',
      'Elgyem',
      'Beldum',
      'Minior',
      'Axew',
    ],
    id: 36,
    pokemon: null,
    location: 'Mt. Hokulani',
    status: null,
  },
  {
    filter: [
      'Parasect',
      'Ledian',
      'Ariados',
      'Pancham',
      'Pangoro',
      'Trumbeak',
      'Shiinotic',
      'Komala',
      'Monferno',
    ],
    id: 37,
    pokemon: null,
    location: 'Route 11',
    status: null,
  },
  {
    filter: ['Graveler (Alolan)', 'Houndoom', 'Manectric', 'Torkoal', 'Mudbray', 'Mudsdale'],
    id: 38,
    pokemon: null,
    location: 'Route 12',
    status: null,
  },
  {
    filter: [
      'Graveler (Alolan)',
      'Elekid',
      'Electabuzz',
      'Happiny',
      'Torkoal',
      'Dedenne',
      'Charjabug',
      'Mudbray',
      'Mudsdale',
      'Turtonator',
      'Togedemaru',
      'Rhyhorn',
    ],
    id: 39,
    pokemon: null,
    location: 'Blush Mountain',
    status: null,
  },
  {
    filter: ['Crabrawler'],
    id: 40,
    pokemon: null,
    location: "Ula'ula Beach",
    status: null,
  },
  {
    filter: ['Magikarp', 'Gyarados', 'Wishiwashi', 'Bruxish'],
    id: 41,
    pokemon: null,
    location: 'Route 13',
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Sandshrew (Alolan)',
      'Vulpix (Alolan)',
      'Pelipper',
      'Absol',
      'Snorunt',
      'Gumshoos',
      'Vanillite',
      'Castform',
      'Phantump',
      'Swinub',
    ],
    id: 42,
    pokemon: null,
    location: 'Tapu Village',
    status: null,
  },
  {
    filter: [
      'Magikarp',
      'Gyarados',
      'Tentacruel',
      'Frillish',
      'Pelipper',
      'Finneon',
      'Wishiwashi',
      'Bruxish',
    ],
    id: 43,
    pokemon: null,
    location: 'Route 14',
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Slowpoke',
      'Tentacruel',
      'Pelipper',
      'Gumshoos',
      'Clamperl',
      'Gorebyss',
      'Huntail',
      'Finneon',
      'Magikarp',
      'Gyarados',
      'Wishiwashi',
      'Bruxish',
      'Sandygast',
    ],
    id: 44,
    pokemon: null,
    location: 'Route 15',
    status: null,
  },
  {
    filter: ['Golbat', 'Haunter', 'Shuppet', 'Gengar', 'Klefki', 'Mimikyu'],
    id: 45,
    pokemon: null,
    location: 'Thrify Megamart',
    status: null,
  },
  {
    filter: ['Dugtrio (Alolan)', 'Golett', 'Baltoy', 'Krokorok', 'Trapinch', 'Gabite', 'Castform'],
    id: 53,
    pokemon: null,
    location: 'Haina Desert',
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Slowpoke',
      'Pelipper',
      'Scraggy',
      'Gumshoos',
      'Crabrawler',
      'Zygarde',
      'Prinplup',
    ],
    id: 46,
    pokemon: null,
    location: 'Route 16',
    status: null,
  },
  {
    filter: [
      'Ledian',
      'Ariados',
      'Cottonee',
      'Petilil',
      'Floette',
      'Oricorio',
      'Ribombee',
      'Grotle',
    ],
    id: 47,
    pokemon: null,
    location: "Ula'ula Meadow",
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Fearow',
      'Ledian',
      'Ariados',
      'Scraggy',
      'Bisharp',
      'Pawniard',
      'Gumshoos',
      'Graveler (Alolan)',
      'Skarmory',
      'Castform',
      'Goomy',
      'Crabrawler',
    ],
    id: 48,
    pokemon: null,
    location: 'Route 17',
    status: null,
  },
  {
    filter: ['Magikarp', 'Gyarados', 'Wailmer', 'Wailord', 'Dhelmise', 'Aerodactyl', 'Shellos'],
    id: 54,
    pokemon: null,
    location: 'Seafolk Village',
    status: null,
  },
  {
    filter: [
      'Exeggcute',
      'Exeggutor (Alolan)',
      'Pinsir',
      'Tropius',
      'Pelipper',
      'Gastrodon',
      'Sliggoo',
      'Castform',
      'Chesnaught',
    ],
    id: 55,
    pokemon: null,
    location: 'Exeggutor Island',
    status: null,
  },
  {
    filter: [
      'Machoke',
      'Skarmory',
      'Boldore',
      'Mienfoo',
      'Carbink',
      'Lycanroc',
      'Jangmo-o',
      'Konmmo-o',
      'Hakamo-o',
      'Golbat',
      'Dugtrio (Alolan)',
      'Golduck',
      'Magikarp',
      'Gyarados',
      'Corphish',
      'Crawdaunt',
      'Basculin',
      'Dratini',
      'Dragonair',
      'Barboach',
      'Whiscash',
    ],
    id: 56,
    pokemon: null,
    location: 'Vast Poni Canyon',
    status: null,
  },
  {
    filter: [
      'Raticate (Alolan)',
      'Sandshrew (Alolan)',
      'Vulpix (Alolan)',
      'Sneasel',
      'Absol',
      'Snorunt',
      'Glalie',
      'Gumshoos',
      'Vanillish',
      'Vanilluxe',
      'Castform',
      'Golbat',
      'Drampa',
    ],
    id: 57,
    pokemon: null,
    location: 'Mount Lanakila',
    status: null,
  },
  {
    filter: ['Solgaleo', 'Lunala'],
    id: 58,
    pokemon: null,
    location: 'Mahalo Trail',
    status: null,
  },
];

export default US_UM;
