import { TEncounter } from 'constants/types';

const X_Y: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    id: 1,
    pokemon: null,
    location: 'Aquacorde Town',
    status: null,
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 2',
    status: null,
  },
  {
    id: 3,
    pokemon: null,
    location: 'Santalune Forest',
    status: null,
  },
  {
    id: 4,
    pokemon: null,
    location: 'Santalune City',
    status: null,
  },
  {
    id: 5,
    pokemon: null,
    location: 'Route 3',
    status: null,
  },
  {
    id: 6,
    pokemon: null,
    location: 'Route 22',
    status: null,
  },
  {
    id: 7,
    pokemon: null,
    location: 'Route 4',
    status: null,
  },
  {
    id: 8,
    pokemon: null,
    location: 'Lumiose City',
    status: null,
  },
  {
    id: 9,
    pokemon: null,
    location: 'Route 5',
    status: null,
  },
  {
    id: 10,
    pokemon: null,
    location: 'Route 6',
    status: null,
  },
  {
    id: 11,
    pokemon: null,
    location: 'Route 7',
    status: null,
  },
  {
    id: 12,
    pokemon: null,
    location: 'Route 8',
    status: null,
  },
  {
    id: 13,
    pokemon: null,
    location: 'Camphrier Town',
    status: null,
  },
  {
    id: 14,
    pokemon: null,
    location: 'Connecting Cave',
    status: null,
  },
  {
    id: 15,
    pokemon: null,
    location: 'Route 9',
    status: null,
  },
  {
    id: 16,
    pokemon: null,
    location: 'Ambrette Town',
    status: null,
  },
  {
    id: 17,
    pokemon: null,
    location: 'Glittering Cave',
    status: null,
  },
  {
    id: 18,
    pokemon: null,
    location: 'Cyallage City',
    status: null,
  },
  {
    id: 19,
    pokemon: null,
    location: 'Route 10',
    status: null,
  },
  {
    id: 21,
    pokemon: null,
    location: 'Route 11',
    status: null,
  },
  {
    id: 22,
    pokemon: null,
    location: 'Reflection Cave',
    status: null,
  },
  {
    id: 23,
    pokemon: null,
    location: 'Geosenge Town',
    status: null,
  },
  {
    id: 24,
    pokemon: null,
    location: 'Route 12',
    status: null,
  },
  {
    id: 25,
    pokemon: null,
    location: 'Tower of Mastery',
    status: null,
  },
  {
    id: 26,
    pokemon: null,
    location: 'Shalour City',
    status: null,
  },
  {
    id: 27,
    pokemon: null,
    location: 'Azure Bay',
    status: null,
  },
  {
    id: 28,
    pokemon: null,
    location: 'Courmarine City',
    status: null,
  },
  {
    id: 29,
    pokemon: null,
    location: "Sea Spirit's Den",
    status: null,
  },
  {
    id: 30,
    pokemon: null,
    location: 'Route 13',
    status: null,
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 14',
    status: null,
  },
  {
    id: 32,
    pokemon: null,
    location: 'Lavarre City',
    status: null,
  },
  {
    id: 33,
    pokemon: null,
    location: 'Route 15',
    status: null,
  },
  {
    id: 34,
    pokemon: null,
    location: 'Lost Hotel',
    status: null,
  },
  {
    id: 35,
    pokemon: null,
    location: 'Frost Cavern',
    status: null,
  },
  {
    id: 36,
    pokemon: null,
    location: 'Route 17',
    status: null,
  },
  {
    id: 37,
    pokemon: null,
    location: 'Route 18',
    status: null,
  },
  {
    id: 38,
    pokemon: null,
    location: 'Couriway Town',
    status: null,
  },
  {
    id: 39,
    pokemon: null,
    location: 'Route 19',
    status: null,
  },
  {
    id: 40,
    pokemon: null,
    location: 'Snowbelle City',
    status: null,
  },
  {
    id: 41,
    pokemon: null,
    location: 'Route 20',
    status: null,
  },
  {
    id: 42,
    pokemon: null,
    location: 'Pokemon Village',
    status: null,
  },
  {
    id: 43,
    pokemon: null,
    location: 'Route 21',
    status: null,
  },
  {
    id: 44,
    pokemon: null,
    location: 'Victory Road',
    status: null,
  },
  {
    id: 45,
    pokemon: null,
    location: 'Terminus Cave',
    status: null,
  },
];

export default X_Y;
