import { TEncounter } from 'constants/types';

const X_Y: TEncounter[] = [
  {
    filter: ['Chespin', 'Fennekin', 'Froakie'],
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
  },
  {
    filter: ['Chespin', 'Fennekin', 'Froakie'],
    id: 1,
    pokemon: null,
    location: 'Aquacorde Town',
    status: null,
  },
  {
    filter: ['Caterpie', 'Weedle', 'Pidgey', 'Zigzagoon', 'Bunnelby', 'Fletchling', 'Scatterbug'],
    id: 2,
    pokemon: null,
    location: 'Route 2',
    status: null,
  },
  {
    filter: [
      'Caterpie',
      'Metapod',
      'Weedle',
      'Kakuna',
      'Pikachu',
      'Pansage',
      'Pansear',
      'Panpour',
      'Fletchling',
      'Scatterbug',
    ],
    id: 3,
    pokemon: null,
    location: 'Santalune Forest',
    status: null,
  },
  {
    filter: ["Farfetch'd"],
    id: 4,
    pokemon: null,
    location: 'Santalune City',
    status: null,
  },
  {
    filter: [
      'Pidgey',
      'Pikachu',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Gyarados',
      'Marill',
      'Dunsparce',
      'Masquerain',
      'Azurill',
      'Corphish',
      'Crawdaunt',
      'Bidoof',
      'Burmy',
      'Bunnelby',
      'Fletchling',
    ],
    id: 5,
    pokemon: null,
    location: 'Route 3',
    status: null,
  },
  {
    filter: [
      'Psyduck',
      'Farfetchd',
      'Goldeen',
      'Seaking',
      'Magikarp',
      'Gyarados',
      'Azumarill',
      'Dunsparce',
      'Azurill',
      'Carvanha',
      'Sharpedo',
      'Bidoof',
      'Bibarel',
      'Riolu',
      'Bunnelby',
      'Diggersby',
      'Litleo',
    ],
    id: 6,
    pokemon: null,
    location: 'Route 22',
    status: null,
  },
  {
    filter: ['Ledyba', 'Ralts', 'Skitty', 'Budew', 'Combee', 'Flabebe'],
    id: 7,
    pokemon: null,
    location: 'Route 4',
    status: null,
  },
  {
    filter: ['Bulbasaur', 'Charmander', 'Squirtle'],
    id: 8,
    pokemon: null,
    location: 'Lumiose City',
    status: null,
  },
  {
    filter: [
      'Abra',
      'Doduo',
      'Plusle',
      'Minun',
      'Gulpin',
      'Bunnelby',
      'Skiddo',
      'Pancham',
      'Furfrou',
    ],
    id: 9,
    pokemon: null,
    location: 'Route 5',
    status: null,
  },
  {
    filter: ['Oddish', 'Sentret', 'Nincada', 'Kecleon', 'Espurr', 'Honedge'],
    id: 10,
    pokemon: null,
    location: 'Route 6',
    status: null,
  },
  {
    filter: [
      'Smeargle',
      'Volbeat',
      'Illumise',
      'Roselia',
      'Croagunk',
      'Ducklett',
      'Flabebe',
      'Spritzee',
      'Swirlix',
    ],
    id: 11,
    pokemon: null,
    location: 'Route 7',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Shellder',
      'Cloyster',
      'Staryu',
      'Starmie',
      'Qwilfish',
      'Wailmer',
      'Spoink',
      'Zangoose',
      'Seviper',
      'Absol',
      'Luvdisc',
      'Bagon',
      'Drifloon',
      'Dwebble',
      'Mienfoo',
      'Inkay',
      'Binacle',
      'Skrelp',
      'Dragalge',
      'Clauncher',
      'Clawitzer',
    ],
    id: 12,
    pokemon: null,
    location: 'Route 8',
    status: null,
  },
  {
    filter: ['Gyarados', 'Eevee'],
    id: 13,
    pokemon: null,
    location: 'Camphrier Town',
    status: null,
  },
  {
    filter: ['Zubat', 'Whismur', 'Meditite', 'Axew'],
    id: 14,
    pokemon: null,
    location: 'Connecting Cave',
    status: null,
  },
  {
    filter: ['Hippopotas', 'Sandile', 'Helioptile'],
    id: 15,
    pokemon: null,
    location: 'Route 9',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Horsea',
      'Seadra',
      'Wailmer',
      'Relicanth',
      'Luvdisc',
      'Dwebble',
      'Binacle',
      'Skrelp',
      'Dragalge',
      'Clauncher',
      'Clawitzer',
    ],
    id: 16,
    pokemon: null,
    location: 'Ambrette Town',
    status: null,
  },
  {
    filter: [
      'Machop',
      'Onix',
      'Cubone',
      'Rhyhorn',
      'Kangaskhan',
      'Mawile',
      'Lunatone',
      'Solrock',
      'Woobat',
      'Ferroseed',
      'Onix',
      'Dwebble',
    ],
    id: 17,
    pokemon: null,
    location: 'Glittering Cave',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Onix',
      'Horsea',
      'Seadra',
      'Wailmer',
      'Relicanth',
      'Luvdisc',
      'Dwebble',
      'Binacle',
      'Skrelp',
      'Dragalge',
      'Clauncher',
      'Clawitzer',
    ],
    id: 18,
    pokemon: null,
    location: 'Cyallage City',
    status: null,
  },
  {
    filter: [
      'Eevee',
      'Snubbull',
      'Houndour',
      'Electrike',
      'Sigilyph',
      'Emolga',
      'Golett',
      'Hawlucha',
    ],
    id: 19,
    pokemon: null,
    location: 'Route 10',
    status: null,
  },
  {
    filter: [
      'Nidorina',
      'Nidorino',
      'Hariyama',
      'Staravia',
      'Chingling',
      'Stunky',
      'Throh',
      'Sawk',
      'Dedenne',
    ],
    id: 21,
    pokemon: null,
    location: 'Route 11',
    status: null,
  },
  {
    filter: [
      'Mr. Mime',
      'Wobbuffet',
      'Sableye',
      'Chingling',
      'Roggenrola',
      'Solosis',
      'Carbink',
      'Mime Jr.',
      'Woobat',
      'Ferroseed',
    ],
    id: 22,
    pokemon: null,
    location: 'Reflection Cave',
    status: null,
  },
  {
    filter: ['Gyarados', 'Eevee'],
    id: 23,
    pokemon: null,
    location: 'Geosenge Town',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Slowpoke',
      'Exeggcute',
      'Pinsir',
      'Tauros',
      'Lapras',
      'Heracross',
      'Corsola',
      'Remoraid',
      'Octillery',
      'Miltank',
      'Clamperl',
      'Huntail',
      'Gorebyss',
      'Luvdisc',
      'Pachirisu',
      'Chatot',
      'Mantyke',
      'Dwebble',
      'Binacle',
    ],
    id: 24,
    pokemon: null,
    location: 'Route 12',
    status: null,
  },
  {
    filter: ['Lucario'],
    id: 25,
    pokemon: null,
    location: 'Tower of Mastery',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Chinchou',
      'Lanturn',
      'Remoraid',
      'Octillery',
      'Luvdisc',
      'Mantyke',
      'Alomomola',
    ],
    id: 26,
    pokemon: null,
    location: 'Shalour City',
    status: null,
  },
  {
    filter: [
      'Tentacool',
      'Slowpoke',
      'Exeggcute',
      'Lapras',
      'Chinchou',
      'Lanturn',
      'Remoraid',
      'Octillery',
      'Luvdisc',
      'Chatot',
      'Mantyke',
      'Dwebble',
      'Alomomola',
      'Inkay',
      'Binacle',
    ],
    id: 27,
    pokemon: null,
    location: 'Azure Bay',
    status: null,
  },
  {
    filter: ['Gyarados', 'Eevee'],
    id: 28,
    pokemon: null,
    location: 'Courmarine City',
    status: null,
  },
  {
    filter: ['Moltres', 'Zapdos', 'Articuno'],
    id: 29,
    pokemon: null,
    location: "Sea Spirit's Den",
    status: null,
  },
  {
    filter: ['Dugtrio', 'Graveler', 'Slugma', 'Trapinch', 'Gible'],
    id: 30,
    pokemon: null,
    location: 'Route 13',
    status: null,
  },
  {
    filter: [
      'Poliwag',
      'Poliwhirl',
      'Weepinbell',
      'Haunter',
      'Quagsire',
      'Barboach',
      'Whiscash',
      'Skorupi',
      'Carnivine',
      'Karrablast',
      'Shelmet',
      'Stunfisk',
      'Goomy',
    ],
    id: 31,
    pokemon: null,
    location: 'Route 14',
    status: null,
  },
  {
    filter: ['Poliwag', 'Poliwhirl', 'Basculin'],
    id: 32,
    pokemon: null,
    location: 'Laverre City',
    status: null,
  },
  {
    filter: [
      'Poliwag',
      'Poliwhirl',
      'Mightyena',
      'Lombre',
      'Floatzel',
      'Skorupi',
      'Watchog',
      'Liepard',
      'Basculin',
      'Foongus',
      'Pawniard',
      'Klefki',
    ],
    id: 33,
    pokemon: null,
    location: 'Route 15',
    status: null,
  },
  {
    filter: ['Magneton', 'Electrode', 'Litwick', 'Pawniard', 'Klefki'],
    id: 34,
    pokemon: null,
    location: 'Lost Hotel',
    status: null,
  },
  {
    filter: [
      'Haunter',
      'Jynx',
      'Piloswine',
      'Beartic',
      'Cryogonal',
      'Bergmite',
      'Smoochum',
      'Vanillite',
      'Cubchoo',
      'Poliwhirl',
      'Floatzel',
      'Basculin',
      'Poliwag',
    ],
    id: 35,
    pokemon: null,
    location: 'Frost Cavern',
    status: null,
  },
  {
    filter: ['Sneasel', 'Delibird', 'Snover', 'Abomasnow'],
    id: 36,
    pokemon: null,
    location: 'Route 17',
    status: null,
  },
  {
    filter: [
      'Sandslash',
      'Graveler',
      'Shuckle',
      'Pupitar',
      'Lairon',
      'Torkoal',
      'Gurdurr',
      'Heatmor',
      'Durant',
    ],
    id: 37,
    pokemon: null,
    location: 'Route 18',
    status: null,
  },
  {
    filter: ['Poliwag', 'Poliwhirl', 'Lombre', 'Floatzel', 'Basculin'],
    id: 38,
    pokemon: null,
    location: 'Couriway Town',
    status: null,
  },
  {
    filter: [
      'Poliwag',
      'Poliwhirl',
      'Weepinbell',
      'Haunter',
      'Politoed',
      'Quagsire',
      'Barboach',
      'Whiscash',
      'Drapion',
      'Carnivine',
      'Karrablast',
      'Shelmet',
      'Stunfisk',
      'Sliggoo',
    ],
    id: 39,
    pokemon: null,
    location: 'Route 19',
    status: null,
  },
  {
    filter: ['Bisharp'],
    id: 40,
    pokemon: null,
    location: 'Snowbelle City',
    status: null,
  },
  {
    filter: ['Jigglypuff', 'Noctowl', 'Zoroark', 'Gothorita', 'Amoonguss', 'Trevenant'],
    id: 41,
    pokemon: null,
    location: 'Route 20',
    status: null,
  },
  {
    filter: [
      'Jigglypuff',
      'Poliwag',
      'Poliwhirl',
      'Ditto',
      'Noctowl',
      'Lombre',
      'Basculin',
      'Zoroark',
      'Gothorita',
      'Amoonguss',
    ],
    id: 42,
    pokemon: null,
    location: 'Pokemon Village',
    status: null,
  },
  {
    filter: [
      'Poliwag',
      'Poliwhirl',
      'Scyther',
      'Dratini',
      'Dragonair',
      'Ursaring',
      'Lombre',
      'Spinda',
      'Altaria',
      'Floatzel',
      'Basculin',
    ],
    id: 43,
    pokemon: null,
    location: 'Route 21',
    status: null,
  },
  {
    filter: [
      'Graveler',
      'Haunter',
      'Lickitung',
      'Gurdurr',
      'Druddigon',
      'Zweilous',
      'Geodude',
      'Floatzel',
      'Shuckle',
      'Ariados',
      'Noibat',
      'Fearow',
      'Skarmory',
      'Hydreigon',
      'Lombre',
      'Poliwhirl',
      'Poliwag',
      'Basculin',
    ],
    id: 44,
    pokemon: null,
    location: 'Victory Road',
    status: null,
  },
  {
    filter: [
      'Sandslash',
      'Graveler',
      'Pupitar',
      'Lairon',
      'Durant',
      'Geodude',
      'Larvitar',
      'Aron',
      'Durant',
      'Shuckle',
      'Ariados',
      'Noibat',
      'Zygarde',
    ],
    id: 45,
    pokemon: null,
    location: 'Terminus Cave',
    status: null,
  },
];

export default X_Y;
