import type { TEncounter } from 'constants/types';

const X_Y: TEncounter[] = [
  {
    id: 0,
    pokemon: null,
    location: 'Starter',
    status: null,
    filter: null,
    filterKey: 'xy-0',
  },
  {
    id: 1,
    pokemon: null,
    location: 'Aquacorde Town',
    status: null,
    filter: null,
    filterKey: 'xy-1',
  },
  {
    id: 2,
    pokemon: null,
    location: 'Route 2',
    status: null,
    filter: null,
    filterKey: 'xy-2',
  },
  {
    id: 3,
    pokemon: null,
    location: 'Santalune Forest',
    status: null,
    filter: null,
    filterKey: 'xy-3',
  },
  {
    id: 4,
    pokemon: null,
    location: 'Santalune City',
    status: null,
    filter: null,
    filterKey: 'xy-4',
  },
  {
    id: 5,
    pokemon: null,
    location: 'Route 3',
    status: null,
    filter: null,
    filterKey: 'xy-5',
  },
  {
    id: 6,
    pokemon: null,
    location: 'Route 22',
    status: null,
    filter: null,
    filterKey: 'xy-6',
  },
  {
    id: 7,
    pokemon: null,
    location: 'Route 4',
    status: null,
    filter: null,
    filterKey: 'xy-7',
  },
  {
    id: 8,
    pokemon: null,
    location: 'Lumiose City',
    status: null,
    filter: null,
    filterKey: 'xy-8',
  },
  {
    id: 9,
    pokemon: null,
    location: 'Route 5',
    status: null,
    filter: null,
    filterKey: 'xy-9',
  },
  {
    id: 10,
    pokemon: null,
    location: 'Route 6',
    status: null,
    filter: null,
    filterKey: 'xy-10',
  },
  {
    id: 11,
    pokemon: null,
    location: 'Route 7',
    status: null,
    filter: null,
    filterKey: 'xy-11',
  },
  {
    id: 12,
    pokemon: null,
    location: 'Route 8',
    status: null,
    filter: null,
    filterKey: 'xy-12',
  },
  {
    id: 13,
    pokemon: null,
    location: 'Camphrier Town',
    status: null,
    filter: null,
    filterKey: 'xy-13',
  },
  {
    id: 14,
    pokemon: null,
    location: 'Connecting Cave',
    status: null,
    filter: null,
    filterKey: 'xy-14',
  },
  {
    id: 15,
    pokemon: null,
    location: 'Route 9',
    status: null,
    filter: null,
    filterKey: 'xy-15',
  },
  {
    id: 16,
    pokemon: null,
    location: 'Ambrette Town',
    status: null,
    filter: null,
    filterKey: 'xy-16',
  },
  {
    id: 17,
    pokemon: null,
    location: 'Glittering Cave',
    status: null,
    filter: null,
    filterKey: 'xy-17',
  },
  {
    id: 18,
    pokemon: null,
    location: 'Cyllage City',
    status: null,
    filter: null,
    filterKey: 'xy-18',
  },
  {
    id: 19,
    pokemon: null,
    location: 'Route 10',
    status: null,
    filter: null,
    filterKey: 'xy-19',
  },
  {
    id: 47,
    pokemon: null,
    location: 'Parfum Palace',
    status: null,
    filter: null,
    filterKey: 'xy-47',
  },
  {
    id: 21,
    pokemon: null,
    location: 'Route 11',
    status: null,
    filter: null,
    filterKey: 'xy-21',
  },
  {
    id: 22,
    pokemon: null,
    location: 'Reflection Cave',
    status: null,
    filter: null,
    filterKey: 'xy-22',
  },
  {
    id: 23,
    pokemon: null,
    location: 'Geosenge Town',
    status: null,
    filter: null,
    filterKey: 'xy-23',
  },
  {
    id: 24,
    pokemon: null,
    location: 'Route 12',
    status: null,
    filter: null,
    filterKey: 'xy-24',
  },
  {
    id: 25,
    pokemon: null,
    location: 'Tower of Mastery',
    status: null,
    filter: null,
    filterKey: 'xy-25',
  },
  {
    id: 26,
    pokemon: null,
    location: 'Shalour City',
    status: null,
    filter: null,
    filterKey: 'xy-26',
  },
  {
    id: 27,
    pokemon: null,
    location: 'Azure Bay',
    status: null,
    filter: null,
    filterKey: 'xy-27',
  },
  {
    id: 28,
    pokemon: null,
    location: 'Coumarine City',
    status: null,
    filter: null,
    filterKey: 'xy-28',
  },
  {
    id: 29,
    pokemon: null,
    location: "Sea Spirit's Den",
    status: null,
    filter: null,
    filterKey: 'xy-29',
  },
  {
    id: 30,
    pokemon: null,
    location: 'Route 13',
    status: null,
    filter: null,
    filterKey: 'xy-30',
  },
  {
    id: 31,
    pokemon: null,
    location: 'Route 14',
    status: null,
    filter: null,
    filterKey: 'xy-31',
  },
  {
    id: 32,
    pokemon: null,
    location: 'Laverre City',
    status: null,
    filter: null,
    filterKey: 'xy-32',
  },
  {
    id: 33,
    pokemon: null,
    location: 'Route 15',
    status: null,
    filter: null,
    filterKey: 'xy-33',
  },
  {
    id: 34,
    pokemon: null,
    location: 'Lost Hotel',
    status: null,
    filter: null,
    filterKey: 'xy-34',
  },
  {
    id: 46,
    pokemon: null,
    location: 'Route 16',
    status: null,
    filter: null,
    filterKey: 'xy-46',
  },
  {
    id: 35,
    pokemon: null,
    location: 'Frost Cavern',
    status: null,
    filter: null,
    filterKey: 'xy-35',
  },
  {
    id: 36,
    pokemon: null,
    location: 'Route 17',
    status: null,
    filter: null,
    filterKey: 'xy-36',
  },
  {
    id: 37,
    pokemon: null,
    location: 'Route 18',
    status: null,
    filter: null,
    filterKey: 'xy-37',
  },
  {
    id: 38,
    pokemon: null,
    location: 'Couriway Town',
    status: null,
    filter: null,
    filterKey: 'xy-38',
  },
  {
    id: 39,
    pokemon: null,
    location: 'Route 19',
    status: null,
    filter: null,
    filterKey: 'xy-39',
  },
  {
    id: 40,
    pokemon: null,
    location: 'Snowbelle City',
    status: null,
    filter: null,
    filterKey: 'xy-40',
  },
  {
    id: 41,
    pokemon: null,
    location: 'Route 20',
    status: null,
    filter: null,
    filterKey: 'xy-41',
  },
  {
    id: 42,
    pokemon: null,
    location: 'Pokemon Village',
    status: null,
    filter: null,
    filterKey: 'xy-42',
  },
  {
    id: 43,
    pokemon: null,
    location: 'Route 21',
    status: null,
    filter: null,
    filterKey: 'xy-43',
  },
  {
    id: 44,
    pokemon: null,
    location: 'Victory Road',
    status: null,
    filter: null,
    filterKey: 'xy-44',
  },
  {
    id: 45,
    pokemon: null,
    location: 'Terminus Cave',
    status: null,
    filter: null,
    filterKey: 'xy-45',
  },
];

export default X_Y;
