name: Cypress
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.17.1-chrome-138.0.7204.157-1-ff-140.0.4-edge-138.0.3351.83-1
      options: --user 1001
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🌲 Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
      # report machine parameters
      - run: npx cypress info
      - run: node -p 'os.cpus()'
      - run: npm run build

      - name: 📁 Save build folder
        uses: actions/upload-artifact@v4.3.1
        with:
          name: build
          if-no-files-found: error
          path: dist

  Vitest-Lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🎓 Install dependencies
        run: npm install --ignore-platform

      - name: 🧹 Run linting
        run: npm run lint

      - name: 🃏 Run Vitest
        run: npm run test -- --ci --coverage

      - name: ✅ Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  ui-chrome-tests-main:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.18.0-chrome90-ff88
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # runs copies of the current job in parallel
        containers: [1, 2, 3, 4]
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Download the build folders
        uses: actions/download-artifact@v4.1.4
        with:
          name: build
          path: dist

      - name: 💻 'UI Tests - Chrome'
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: http://localhost:5173
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome - Main'
          spec: 'cypress/e2e/main/*'
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ✅ Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  ui-chrome-tests-other:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node-22.17.1-chrome-138.0.7204.157-1-ff-140.0.4-edge-138.0.3351.83-1
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # runs copies of the current job in parallel
        containers: [1, 2, 3, 4]
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Download the build folders
        uses: actions/download-artifact@v4.1.4
        with:
          name: build
          path: dist

      - name: 💻 'UI Tests - Chrome'
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: http://localhost:5173
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome - Other'
          spec: 'cypress/e2e/other/*'
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ✅ Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  ui-firefox-tests-main:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.17.1-chrome-138.0.7204.157-1-ff-140.0.4-edge-138.0.3351.83-1
      options: --user 1001
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4]
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Download the build folders
        uses: actions/download-artifact@v4.1.4
        with:
          name: build
          path: dist

      - name: 💻 'UI Tests - Firefox'
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 120
          browser: firefox
          record: true
          parallel: true
          group: 'UI - Firefox - Main'
          spec: 'cypress/e2e/main/*'
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ✅ Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  ui-firefox-tests-other:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.17.1-chrome-138.0.7204.157-1-ff-140.0.4-edge-138.0.3351.83-1
      options: --user 1001
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4]
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Download the build folders
        uses: actions/download-artifact@v4.1.4
        with:
          name: build
          path: dist

      - name: 💻 'UI Tests - Firefox'
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 120
          browser: firefox
          record: true
          parallel: true
          group: 'UI - Firefox - Other'
          spec: 'cypress/e2e/other/*'
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ✅ Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
